project:
  type: website

website:
  title: "IS415"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
        - text: "Hands-on Exercise 1: Introduction to Geospatial Analytics"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exercise 2: GeoVisualisation and Analytical Mapping"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
        - text: "Hands-on Exercise 3: Spatial Point Patterns Analysis"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
        - text: "Hands-on Exercise 4: Advanced Spatial Point Patterns Analysis"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
        - text: "Hands-on Exercise 5: Spatial Weights and Applications"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html"
        - text: "Hands-on Exercise 6: Measures of Global and Local Spatial Association"
          href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
        - text: "Hands-on Exercise 7: Shiny for Building Web-enabled Geospatial Analytics Application"
          href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html"
        - text: "Hands-on Exercise 8: Hierarchical Clustering for Multivariate Geographically Referenced Data"
          href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.html"
        - text: "Hands-on Exercise 9: Spatially Constrained Cluster Analysis"
          href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.html"
        - text: "Hands-on Exercise 10: Regression Modelling of Geographically Reference Data"
          href: "Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10.html"
        - text: "Hands-on Exercise 11: Geographically Weighted Regression"
          href: "Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10.html"
        - text: "Hands-on Exercise 12: Geographically Weighted Predictive Modelling"
          href: "Hands-on_Ex/Hands-on_Ex12/Hands-on_Ex12.html"
    - text: "In-Class Exercise"
      menu:
        - text: "In-Class Exercise 1: Introduction to Geospatial Analytics"
          href: "In-Class_Ex/In-Class_Ex01/In-Class_Ex01.html"
        - text: "In-Class Exercise 2: GeoVisualisation and Analytical Mapping"
          href: "In-Class_Ex/In-Class_Ex02/In-Class_Ex02.html"
        - text: "In-Class Exercise 3: Spatial Point Patterns Analysis"
          href: "In-Class_Ex/In-Class_Ex03/In-Class_Ex03.html"
        - text: "In-Class Exercise 4: Advanced Spatial Point Patterns Analysis"
          href: "In-Class_Ex/In-Class_Ex04/In-Class_Ex04.html"
        - text: "In-Class Exercise 5: Spatial Weights and Applications"
          href: "In-Class_Ex/In-Class_Ex05/In-Class_Ex05.html"
        - text: "In-Class Exercise 6: Measures of Global and Local Spatial Association"
          href: "In-Class_Ex/In-Class_Ex06/In-Class_Ex06.html"
        - text: "In-Class Exercise 7: Shiny for Building Web-enabled Geospatial Analytics Application"
          href: "In-Class_Ex/In-Class_Ex07/In-Class_Ex07.html"
        - text: "In-Class Exercise 8: Hierarchical Clustering for Multivariate Geographically Referenced Data"
          href: "In-Class_Ex/In-Class_Ex08/In-Class_Ex08.html"
        - text: "In-Class Exercise 9: Spatially Constrained Cluster Analysis"
          href: "In-Class_Ex/In-Class_Ex09/In-Class_Ex09.html"
        - text: "In-Class Exercise 10: Regression Modelling of Geographically Reference Data"
          href: "In-Class_Ex/In-Class_Ex10/In-Class_Ex10.html"
        - text: "In-Class Exercise 11: Geographically Weighted Regression"
          href: "In-Class_Ex/In-Class_Ex11/In-Class_Ex11.html"
        - text: "In-Class Exercise 12: Geographically Weighted Predictive Modelling"
          href: "In-Class_Ex/In-Class_Ex12/In-Class_Ex12.html"
    - text: "Takehome Exercise"
      menu:
        - text: "Takehome Exercise 1: Unveiling the Spatial and Temporal Dynamics of Armed Conflict in Myanmar"
          href: "Takehome_Ex/Takehome_Ex1/Takehome_Ex1.qmd"
        - text: "Takehome Exercise 2: Application of Geospatial Analysis Methods to Discover Thailand Drug Abuse at the Province Level"
          href: "Takehome_Ex/Takehome_Ex2/Takehome_Ex2.qmd"

        - text: "Takehome Exercise 3: "

    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual