project:
  type: website

website:
  title: "IS415"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
        - text: "Hands-on Exercise 1: Introduction to Geospatial Analytics"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exercise 2: GeoVisualisation and Analytical Mapping"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
        - text: "Hands-on Exercise 3: Spatial Point Patterns Analysis"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
        - text: "Hands-on Exercise 4: Advanced Spatial Point Patterns Analysis"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
        - text: "Hands-on Exercise 5: Spatial Weights and Applications"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html"
        - text: "Hands-on Exercise 6: Measures of Global and Local Spatial Association"
          href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
        - text: "Hands-on Exercise 7: Shiny for Building Web-enabled Geospatial Analytics Application"
          href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html"
        - text: "Hands-on Exercise 8: Geographic Segmentation"
          href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.html"
        - text: "Hands-on Exercise 9: Geographically Weighted Regression"
          href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09.html"
        - text: "Hands-on Exercise 10: Geographically Weighted Predictive Modelling"
          href: "Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10.html"
        - text: "Hands-on Exercise 11: Modelling Geographic of Accessibility"
          href: "Hands-on_Ex/Hands-on_Ex11/Hands-on_Ex11.html"
        - text: "Hands-on Exercise 12: Spatial Interaction Models"
          href: "Hands-on_Ex/Hands-on_Ex12/Hands-on_Ex12.html"

    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

