---
title: "Home Page"
author: "Chong Zhi Cheng"
date: "August 17, 2024"
date-modified: "last-modified"
---

In this website, you will find my relevant coursework for IS415 Geospatial Analytics and Applications.

<!-- [Hands-on Exercise 1](/Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html) -->

<!-- [In-Class Exercise 1](/In-Class_Ex/In-Class_Ex01/In-Class_Ex01.html)-->

<!-- Use create link. ctrl k or insert. -->

[Hands-on Exercise 1](/Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html)

[In-Class Exercise 1](/In-Class_Ex/In-Class_Ex01/In-Class_Ex01.html)

[Hands-on Exercise 2](/Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html)

[In-Class Exercise 2](/In-Class_Ex/In-Class_Ex02/In-Class_Ex02.html)

Personal Notes below:

To manually change the epsg code without transforming

```         
# To manually change the epsg code without transforming
mpsz3414 <- st_set_crs(mpsz, 3414)
# To transform; WGS84 -> SVY21
preschool3414 <- st_transform(preschool, 
                              crs = 3414)
                              
# CSV files ; 4326 is WGS84, 3414 is SCY21
listings_sf <- st_as_sf(listings, 
                       coords = c("longitude", "latitude"),
                       crs=4326) %>%
  st_transform(crs = 3414)
```

### Interesting Website

<https://epsg.io/> - provides a list of country coordinates system such as svy21

<https://colorbrewer2.org/>

#### Data Sources:

<https://data.gov.sg/>

<https://www.singstat.gov.sg/>

<https://datamall.lta.gov.sg/content/datamall/en.html>

<https://insideairbnb.com/get-the-data/>

General Notes. Placeholder for now.

GCS is the base. Convert to PCS to project since GCS is not appropriate for distance and area measurements.

### Geographical Coordinate Systems

GCS define locations on the earth using a three-dimensional spherical surface. For example, WGS84.

They provides accuracy position information. Unit of measurement will be in either decimal degree or degree-minute-second format.

GCS, however, are not appropriate for distance and area measurements. In this figure, it is clear that 1 degree distance at the north pole is relatively shorter than 1 degree at the equator.

### Projected Coordinate Systems (PCS)

Based on a map projection such as transverse Mercator, Albers equal area, or Robinson.

PCS provides consistent length and area measurement across space. Hence, it is important to transform a geospatial data from GCS to PCS before performing geospatial analysis.

Sample ESRI shapefile code chunk:

```         
sf_mpsz = st_read(dsn = "data/geospatial", layer = "MP14_SUBZONE")
```

```         
st_write(st_poly, "data/my_poly.shp")
```

Sample code chunk to import kml file:

```         
sf_preschool = st_read("data/geospatial/pre-schools-location-kml.kml")
```

Placeholder - Please Ignore for now.

[Hands-on Exercise 3](/Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html)

[In-Class Exercise 3](/In-Class_Ex/In-Class_Ex03/In-Class_Ex03.html)

[Hands-on Exercise 4](/Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html) [In-Class Exercise 4](/In-Class_Ex/In-Class_Ex04/In-Class_Ex04.html) [Hands-on Exercise 5](/Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html) [In-Class Exercise 5](/In-Class_Ex/In-Class_Ex05/In-Class_Ex05.html) [Hands-on Exercise 6](/Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html) [In-Class Exercise 6](/In-Class_Ex/In-Class_Ex06/In-Class_Ex06.html)

[Hands-on Exercise 7](/Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html)

[In-Class Exercise 7](/In-Class_Ex/In-Class_Ex07/In-Class_Ex07.html) [Hands-on Exercise 8](/Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.html) [In-Class Exercise 8](/In-Class_Ex/In-Class_Ex08/In-Class_Ex08.html)

[Hands-on Exercise 9](/Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09.html) [In-Class Exercise 9](/In-Class_Ex/In-Class_Ex09/In-Class_Ex09.html) [Hands-on Exercise 10](/Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10.html) [In-Class Exercise 10](/In-Class_Ex/In-Class_Ex10/In-Class_Ex10.html) [Hands-on Exercise 11](/Hands-on_Ex/Hands-on_Ex11/Hands-on_Ex11.html) [In-Class Exercise 11](/In-Class_Ex/In-Class_Ex11/In-Class_Ex11.html) [Hands-on Exercise 12](/Hands-on_Ex/Hands-on_Ex12/Hands-on_Ex12.html) [In-Class Exercise 12](/In-Class_Ex/In-Class_Ex12/In-Class_Ex12.html)
