{
  "hash": "c52eb5ba58ea37f8e9a3b4b7545054d2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Application of Geospatial Analysis Methods to Discover Thailand Drug Abuse at the Province Level\"\nauthor: \"Chong Zhi Cheng\"\ndate: \"September 30, 2024\"\ndate-modified: \"last-modified\"\nexecute:\n  eval: true\n  echo: true\n  freeze: true\n  warning: false\n---\n\n\n# **Introduction**\n\nDrug abuse is associated with significant negative health, financial and social consequences. Yet, illicit drug consumption remains highly prevalent and continues to be a growing problem worldwide. In 2021, 1 in 17 people aged 15–64 in the world had used a drug in the past 12 months. Notwithstanding population growth, the estimated number of drug users grew from 240 million in 2011 to 296 million in 2021.\n\nThe geopolitics of Thailand which is near the [Golden Triangle](https://en.wikipedia.org/wiki/Golden_Triangle_(Southeast_Asia)) of Indochina, the largest drug production site in Asia, and the constant transportation infrastructure development made Thailand became market and transit routes for drug trafficking to the third countries.\n\nIn Thailand, drug abuse is one of the major social issue. There are about 2.7 million youths using drugs in Thailand. Among youths aged between 15 and 19 years, there are about 300,000 who have needs for drug treatment. Most of Thai youths involved with drugs are vocational-school students, which nearly doubles in number compared to secondary-school students.\n\nThis report aims to investigate three key aspects of drug abuse in Thailand:\n\n1.  Spatial Dependency: We will examine whether key indicators of drug abuse in Thailand are independent of geographical location or exhibit spatial patterns.\n2.  Cluster and Outlier Analysis: If spatial dependency is confirmed, we will identify and analyze clusters of high drug abuse rates and any outliers in the data.\n3.  Temporal Evolution: We will investigate how these spatial patterns and clusters have changed over time.\n\n**Initial Hypothesis**\n\nWe hypothesize that key indicators of drug abuse in Thailand are spatially dependent, with clusters of high drug use cases likely concentrated near the Golden Triangle and urban centers.\n\n**Rationale**:\n\n1.  Proximity to the Golden Triangle: Thailand's location near this major drug production area suggests higher drug abuse rates in border regions due to easier access and established trafficking routes.\n2.  Urban Concentration: Drug abuse is expected to cluster in urban areas due to higher population density, diverse social networks, and potentially greater drug availability.\n\nTo test this hypothesis, we will begin with an exploratory data analysis (EDA) of the overall dataset.\n\n# **Datasets**\n\n## **Thailand Drug Offenses \\[2017-2022\\]**\n\nThis dataset presents statistics related to different types of drug offenses in Thailand, categorized by fiscal year. The data provides insights into the prevalence of various drug-related cases and their distribution across different provinces.\n\nSourced from the [Office of the Narcotics Control Board](https://data.oncb.go.th/casePer)\n\n**Column Descriptions:**\n\n| **Column**             | **Description**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |\n|----------------|--------------------------------------------------------|\n| fiscal_year            | The fiscal year during which the drug offenses were recorded.                                                                                                                                                                                                                                                                                                                                                                                                                                                         |\n| types_of_drug_offenses | The specific type or category of drug offense being reported. The types include drug use cases, suspects in drug use cases, possession cases, suspects in possession cases, possession with intent to distribute cases, suspects in possession with intent to distribute cases, trafficking cases, suspects in trafficking cases, production cases, suspects in production cases, import cases, suspects in import cases, export cases, suspects in export cases, conspiracy cases, and suspects in conspiracy cases. |\n| no_cases               | The total number of cases recorded for the specific combination of fiscal year, type of drug offense, and province.                                                                                                                                                                                                                                                                                                                                                                                                   |\n| province_th            | The name of the province in Thailand, written in Thai.                                                                                                                                                                                                                                                                                                                                                                                                                                                                |\n| province_en            | The name of the province in Thailand, written in English.                                                                                                                                                                                                                                                                                                                                                                                                                                                             |\n\n## **Thailand - Subnational Administrative Boundaries**\n\nFor this analysis, we will utilize the Thailand Subnational Administrative Boundaries dataset, which provides detailed geographical information at various administrative levels, obtained from <https://data.humdata.org/dataset/cod-ab-tha?>\n\nThis comprehensive dataset was developed and vetted by Information Technology Outreach Services (ITOS) with funding from USAID, ensuring its reliability and accuracy for research purposes.\n\n**Focus on Provincial Level**\n\nOur analysis will primarily concentrate on Administrative Level 1, which corresponds to Thailand's provincial boundaries. This level of granularity provides an optimal balance between detail and manageability for our spatial analysis of drug abuse patterns across the country.\n\n# **Data Wrangling & Overall Exploratory Data Analysis**\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, spdep, tmap, tidyverse, lubridate, scales, sfdep, dplyr,patchwork,plotly)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nadm1 <- st_read(dsn = \"data/adm\", layer = \"tha_admbnda_adm1_rtsd_20220121\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `tha_admbnda_adm1_rtsd_20220121' from data source \n  `C:\\zcchong\\IS415\\Takehome_Ex\\Takehome_Ex2\\data\\adm' using driver `ESRI Shapefile'\nSimple feature collection with 77 features and 16 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 97.34336 ymin: 5.613038 xmax: 105.637 ymax: 20.46507\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nst_crs(adm1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 \n  wkt:\nGEOGCRS[\"WGS 84\",\n    DATUM[\"World Geodetic System 1984\",\n        ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n            LENGTHUNIT[\"metre\",1]]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"latitude\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"longitude\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    ID[\"EPSG\",4326]]\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nadm1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 77 features and 16 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 97.34336 ymin: 5.613038 xmax: 105.637 ymax: 20.46507\nGeodetic CRS:  WGS 84\nFirst 10 features:\n   Shape_Leng Shape_Area                  ADM1_EN       ADM1_TH ADM1_PCODE\n1    2.417227 0.13133873                  Bangkok  กรุงเทพมหานคร       TH10\n2    1.695100 0.07926199             Samut Prakan    สมุทรปราการ       TH11\n3    1.251111 0.05323766               Nonthaburi         นนทบุรี       TH12\n4    1.884945 0.12698345             Pathum Thani        ปทุมธานี       TH13\n5    3.041716 0.21393797 Phra Nakhon Si Ayutthaya พระนครศรีอยุธยา       TH14\n6    1.739908 0.07920961                Ang Thong        อ่างทอง       TH15\n7    5.693342 0.54578838                 Lop Buri          ลพบุรี       TH16\n8    1.778326 0.06872655                Sing Buri         สิงห์บุรี       TH17\n9    2.896316 0.20907828                 Chai Nat         ชัยนาท       TH18\n10   4.766446 0.29208711                 Saraburi         สระบุรี       TH19\n   ADM1_REF ADM1ALT1EN ADM1ALT2EN ADM1ALT1TH ADM1ALT2TH  ADM0_EN   ADM0_TH\n1      <NA>       <NA>       <NA>       <NA>       <NA> Thailand ประเทศไทย\n2      <NA>       <NA>       <NA>       <NA>       <NA> Thailand ประเทศไทย\n3      <NA>       <NA>       <NA>       <NA>       <NA> Thailand ประเทศไทย\n4      <NA>       <NA>       <NA>       <NA>       <NA> Thailand ประเทศไทย\n5      <NA>       <NA>       <NA>       <NA>       <NA> Thailand ประเทศไทย\n6      <NA>       <NA>       <NA>       <NA>       <NA> Thailand ประเทศไทย\n7      <NA>       <NA>       <NA>       <NA>       <NA> Thailand ประเทศไทย\n8      <NA>       <NA>       <NA>       <NA>       <NA> Thailand ประเทศไทย\n9      <NA>       <NA>       <NA>       <NA>       <NA> Thailand ประเทศไทย\n10     <NA>       <NA>       <NA>       <NA>       <NA> Thailand ประเทศไทย\n   ADM0_PCODE       date    validOn    validTo                       geometry\n1          TH 2019-02-18 2022-01-22 -001-11-30 MULTIPOLYGON (((100.6139 13...\n2          TH 2019-02-18 2022-01-22 -001-11-30 MULTIPOLYGON (((100.7306 13...\n3          TH 2019-02-18 2022-01-22 -001-11-30 MULTIPOLYGON (((100.3415 14...\n4          TH 2019-02-18 2022-01-22 -001-11-30 MULTIPOLYGON (((100.8916 14...\n5          TH 2019-02-18 2022-01-22 -001-11-30 MULTIPOLYGON (((100.5131 14...\n6          TH 2019-02-18 2022-01-22 -001-11-30 MULTIPOLYGON (((100.3332 14...\n7          TH 2019-02-18 2022-01-22 -001-11-30 MULTIPOLYGON (((101.3453 15...\n8          TH 2019-02-18 2022-01-22 -001-11-30 MULTIPOLYGON (((100.3691 15...\n9          TH 2019-02-18 2022-01-22 -001-11-30 MULTIPOLYGON (((100.1199 15...\n10         TH 2019-02-18 2022-01-22 -001-11-30 MULTIPOLYGON (((101.3994 15...\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load the dataset\ndata <- read_csv(\"data/thai_drug_offenses_2017_2022.csv\")\n\n# 1. Basic information about the dataset\nstr(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nspc_tbl_ [7,392 × 5] (S3: spec_tbl_df/tbl_df/tbl/data.frame)\n $ fiscal_year           : num [1:7392] 2017 2017 2017 2017 2017 ...\n $ types_of_drug_offenses: chr [1:7392] \"drug_use_cases\" \"drug_use_cases\" \"drug_use_cases\" \"drug_use_cases\" ...\n $ no_cases              : num [1:7392] 11871 200 553 450 378 ...\n $ province_th           : chr [1:7392] \"กรุงเทพมหานคร\" \"ชัยนาท\" \"นนทบุรี\" \"ปทุมธานี\" ...\n $ province_en           : chr [1:7392] \"Bangkok\" \"Chai Nat\" \"Nonthaburi\" \"Pathum Thani\" ...\n - attr(*, \"spec\")=\n  .. cols(\n  ..   fiscal_year = col_double(),\n  ..   types_of_drug_offenses = col_character(),\n  ..   no_cases = col_double(),\n  ..   province_th = col_character(),\n  ..   province_en = col_character()\n  .. )\n - attr(*, \"problems\")=<externalptr> \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  fiscal_year   types_of_drug_offenses    no_cases       province_th       \n Min.   :2017   Length:7392            Min.   :    0.0   Length:7392       \n 1st Qu.:2018   Class :character       1st Qu.:    1.0   Class :character  \n Median :2020   Mode  :character       Median :   70.0   Mode  :character  \n Mean   :2020                          Mean   :  535.3                     \n 3rd Qu.:2021                          3rd Qu.:  623.0                     \n Max.   :2022                          Max.   :17131.0                     \n province_en       \n Length:7392       \n Class :character  \n Mode  :character  \n                   \n                   \n                   \n```\n\n\n:::\n\n```{.r .cell-code}\n# 2. Distribution of cases across years\nyearly_cases <- data %>%\n  group_by(fiscal_year) %>%\n  summarize(Total_Cases = sum(no_cases))\n\nggplot(yearly_cases, aes(x = fiscal_year, y = Total_Cases, group = 1)) +\n  geom_line(color = \"skyblue\", size = 1) +\n  geom_point(color = \"darkblue\", size = 3) +\n  labs(title = \"Trend of Total Drug Offense Cases by Fiscal Year\",\n       x = \"Fiscal Year\", y = \"Total Cases\") +\n  theme_minimal() +\n  scale_y_continuous(labels = comma) +\n  scale_x_continuous(breaks = yearly_cases$fiscal_year) +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex2_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# 3. Types of drug offenses\noffense_types <- data %>%\n  group_by(types_of_drug_offenses) %>%\n  summarize(Total_Cases = sum(no_cases)) %>%\n  arrange(desc(Total_Cases))\n\nggplot(offense_types, aes(x = reorder(types_of_drug_offenses, -Total_Cases), y = Total_Cases)) +\n  geom_bar(stat = \"identity\", fill = \"lightgreen\") +\n  labs(title = \"Total Cases by Type of Drug Offense\",\n       x = \"Type of Offense\", y = \"Total Cases\") +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +\n  scale_y_continuous(labels = comma)\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex2_files/figure-html/unnamed-chunk-5-2.png){width=672}\n:::\n\n```{.r .cell-code}\n# 4. Geographical distribution of cases\nprovince_cases <- data %>%\n  group_by(province_en) %>%\n  summarize(Total_Cases = sum(no_cases)) %>%\n  arrange(desc(Total_Cases))\n\ntop_10_provinces <- head(province_cases, 10)\n\nggplot(top_10_provinces, aes(x = reorder(province_en, -Total_Cases), y = Total_Cases)) +\n  geom_bar(stat = \"identity\", fill = \"salmon\") +\n  labs(title = \"Top 10 Provinces by Total Drug Offense Cases\",\n       x = \"Province\", y = \"Total Cases\") +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +\n  scale_y_continuous(labels = comma)\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex2_files/figure-html/unnamed-chunk-5-3.png){width=672}\n:::\n\n```{.r .cell-code}\n# 5. Trends over time for top offenses\ntop_5_offenses <- head(offense_types$types_of_drug_offenses, 5)\n\ntrends_data <- data %>%\n  filter(types_of_drug_offenses %in% top_5_offenses) %>%\n  group_by(fiscal_year, types_of_drug_offenses) %>%\n  summarize(Total_Cases = sum(no_cases))\n\nggplot(trends_data, aes(x = fiscal_year, y = Total_Cases, color = types_of_drug_offenses)) +\n  geom_line() +\n  geom_point() +\n  labs(title = \"Trends of Top 5 Drug Offenses Over Time\",\n       x = \"Fiscal Year\", y = \"Total Cases\") +\n  theme_minimal() +\n  scale_y_continuous(labels = comma)\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex2_files/figure-html/unnamed-chunk-5-4.png){width=672}\n:::\n:::\n\n\n1.  Trend of Total Drug Offense Cases by Fiscal Year:\n\n-   There's a general upward trend in total drug offense cases from 2017 to 2021, with a sharp increase in 2021.\n-   The number of cases rose from about 550,000 in 2017 to a peak of nearly 850,000 in 2021.\n-   However, there's a dramatic drop in 2022, falling to approximately 450,000 cases. This sudden decrease might be due to policy changes, reporting adjustments, or external factors like the COVID-19 pandemic.\n\n2.  Total Cases by Type of Drug Offense:\n\n-   Drug use and possession are the most common offenses, each accounting for over 750,000 cases.\n-   There's a significant drop-off after the top two categories, with \"suspects in possession\" and \"possession with intent to distribute\" being the next most frequent offenses.\n-   Trafficking, production, conspiracy, import, and export cases are comparatively rare.\n\n3.  Top 10 Provinces by Total Drug Offense Cases:\n\n-   Bangkok has by far the highest number of cases, with nearly 300,000 - more than double the next highest province.\n-   Nakhon Si Thammarat, Songkhla, and Surat Thani follow, each with over 100,000 cases.\n\n4.  Trends of Top 5 Drug Offenses Over Time:\n\n-   All major offense types show similar trends, with a sharp spike in 2021 followed by a significant drop in 2022.\n\n-   Drug use and possession cases are consistently the highest, often overlapping on the graph.\n\n-   \"Suspects in possession with intent to distribute\" cases show a less dramatic increase in 2021 compared to other offense types.\n\n-   The 2022 decrease is consistent across all offense types, supporting the idea of a systemic change rather than a category-specific shift.\n\nFollowing which, we will verify the consistency between the province names in the shapefile and those in the CSV dataset.\n\nThis crucial step ensures accurate spatial analysis by confirming that our geographical data (shapefile) aligns properly with our drug offense statistics (CSV file). Any discrepancies in naming conventions or data structure will need to be addressed before proceeding with more advanced spatial analyses.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get unique province names from both datasets\nshapefile_provinces <- unique(adm1$ADM1_EN)\ndata_provinces <- unique(data$province_en)\n\n# Create a comparison dataframe\ncomparison <- data.frame(\n  shapefile_provinces = sort(shapefile_provinces),\n  data_provinces = sort(data_provinces)\n)\n\n# Check for exact matches\ncomparison$exact_match <- comparison$shapefile_provinces == comparison$data_provinces\n\n# Print provinces that don't match exactly\nmismatches <- comparison[!comparison$exact_match, ]\nprint(\"Provinces that don't match exactly:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Provinces that don't match exactly:\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(mismatches)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   shapefile_provinces data_provinces exact_match\n4            Bueng Kan        buogkan       FALSE\n21                Loei         Loburi       FALSE\n22            Lop Buri           Loei       FALSE\n```\n\n\n:::\n\n```{.r .cell-code}\n# Function to calculate string similarity\nstring_similarity <- function(a, b) {\n  agrepl(a, b, max.distance = 0.1)\n}\n\n# Check for similar names among mismatches\nif(nrow(mismatches) > 0) {\n  for(i in 1:nrow(mismatches)) {\n    similar <- sapply(data_provinces, function(x) string_similarity(mismatches$shapefile_provinces[i], x))\n    if(any(similar)) {\n      cat(\"Possible match for\", mismatches$shapefile_provinces[i], \":\", data_provinces[similar], \"\\n\")\n    }\n  }\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPossible match for Loei : Loei \n```\n\n\n:::\n\n```{.r .cell-code}\n# Check for provinces in one dataset but not in the other\nin_shapefile_not_in_data <- setdiff(shapefile_provinces, data_provinces)\nin_data_not_in_shapefile <- setdiff(data_provinces, shapefile_provinces)\n\ncat(\"\\nProvinces in shapefile but not in data:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nProvinces in shapefile but not in data:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(in_shapefile_not_in_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Lop Buri\"  \"Bueng Kan\"\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nProvinces in data but not in shapefile:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nProvinces in data but not in shapefile:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(in_data_not_in_shapefile)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Loburi\"  \"buogkan\"\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Function to update province names\nupdate_province_name <- function(name) {\n  case_when(\n    name == \"Loburi\" ~ \"Lop Buri\",\n    name == \"buogkan\" ~ \"Bueng Kan\",\n    TRUE ~ name\n  )\n}\n\n# Update the province_en column\ndata$province_en <- sapply(data$province_en, update_province_name)\n\n# Verify the changes\nprint(data %>% \n  filter(province_en %in% c(\"Lop Buri\", \"Bueng Kan\", \"Loei\")) %>% \n  select(province_en) %>% \n  distinct())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 1\n  province_en\n  <chr>      \n1 Lop Buri   \n2 Bueng Kan  \n3 Loei       \n```\n\n\n:::\n\n```{.r .cell-code}\n# Get unique province names from both datasets\nshapefile_provinces <- unique(adm1$ADM1_EN)\ndata_provinces <- unique(data$province_en)\n\n# Check for any remaining mismatches\nmismatches <- setdiff(data_provinces, shapefile_provinces)\ncat(\"\\nAny remaining mismatches between data provinces and shapefile:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nAny remaining mismatches between data provinces and shapefile:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(mismatches)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncharacter(0)\n```\n\n\n:::\n\n```{.r .cell-code}\nif (length(mismatches) == 0) {\n  cat(\"\\nAll province names now match between the data file and the shapefile.\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nAll province names now match between the data file and the shapefile.\n```\n\n\n:::\n\n```{.r .cell-code}\n# Additional check for case sensitivity\ncase_sensitive_mismatches <- setdiff(tolower(data_provinces), tolower(shapefile_provinces))\nif (length(case_sensitive_mismatches) > 0) {\n  cat(\"\\nWarning: Some provinces match when ignoring case, but have different capitalization:\\n\")\n  print(case_sensitive_mismatches)\n}\n```\n:::\n\n\n# \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Aggregate total cases by province\nprovince_totals <- data %>%\n  group_by(province_en) %>%\n  summarize(total_cases = sum(no_cases))\n\n# Join the totals with the spatial data\nadm1_with_data <- adm1 %>%\n  left_join(province_totals, by = c(\"ADM1_EN\" = \"province_en\"))\n\n# Create the map with a red color scheme\nggplot(data = adm1_with_data) +\n  geom_sf(aes(fill = total_cases)) +\n  scale_fill_gradient(\n    low = \"pink\",\n    high = \"darkred\",\n    name = \"Total Cases\",\n    trans = \"log\",\n    labels = scales::comma_format()\n  ) +\n  theme_minimal() +\n  labs(title = \"Overview of Drug Offense Cases in Thailand\",\n       subtitle = \"Total cases by province (2017-2022)\",\n       caption = \"Data source: Office of the Narcotics Control Board\") +\n  theme(\n    legend.position = \"right\",\n    plot.title = element_text(size = 16, face = \"bold\"),\n    plot.subtitle = element_text(size = 12),\n    legend.title = element_text(size = 10),\n    legend.text = element_text(size = 8)\n  )\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex2_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Aggregate total cases by province and year\nprovince_year_totals <- data %>%\n  group_by(province_en, fiscal_year) %>%\n  summarize(total_cases = sum(no_cases), .groups = \"drop\")\n\n# Create a list of sf objects, one for each year\nadm1_with_data_by_year <- map(unique(province_year_totals$fiscal_year), function(year) {\n  year_data <- province_year_totals %>% \n    filter(fiscal_year == year)\n  \n  adm1 %>%\n    left_join(year_data, by = c(\"ADM1_EN\" = \"province_en\"))\n})\n\n# Combine all years into one sf object\nall_years_sf <- do.call(rbind, adm1_with_data_by_year)\n\n# Create the faceted map\nggplot(data = all_years_sf) +\n  geom_sf(aes(fill = total_cases)) +\n  scale_fill_gradient(\n    low = \"lightpink\",\n    high = \"darkred\",\n    name = \"Total Cases\",\n    trans = \"log\",\n    labels = scales::comma_format()\n  ) +\n  facet_wrap(~ fiscal_year, ncol = 3) +\n  theme_minimal() +\n  labs(title = \"Drug Offense Cases in Thailand by Year\",\n       subtitle = \"Total cases by province (2017-2022)\",\n       caption = \"Data source: Office of the Narcotics Control Board\") +\n  theme(\n    legend.position = \"right\",\n    plot.title = element_text(size = 16, face = \"bold\"),\n    plot.subtitle = element_text(size = 12),\n    legend.title = element_text(size = 10),\n    legend.text = element_text(size = 8),\n    axis.text.x = element_blank(),\n    axis.text.y = element_blank(),\n    axis.ticks = element_blank()\n  )\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex2_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nAn analysis of the overall drug offense cases reveal:\n\n1.  Spatial Distribution:\n    -   The maps reveal significant spatial variation in drug offense cases across Thailand's provinces.\n    -   Darker shades, indicating higher case numbers, are consistently observed in certain regions, particularly in the central, northern, and southern parts of the country.\n    -   Bangkok (the small, dark area in the central region) consistently shows the highest concentration of cases across all years.\n2.  Temporal Trends:\n    -   The series of maps from 2017 to 2022 shows a general intensification of colors, suggesting an overall increase in drug offense cases over time.\n    -   This trend is particularly noticeable from 2017 to 2021, with 2021 showing the darkest shades across most provinces.\n    -   However, there's a visible lightening of colors in 2022, indicating a decrease in cases compared to 2021.\n3.  Regional Patterns:\n    -   Northern provinces consistently show higher case numbers (darker shades) compared to northeastern provinces.\n    -   Southern provinces, especially those in the narrow peninsula, maintain relatively high case numbers throughout the years.\n    -   Central provinces surrounding Bangkok also exhibit consistently high case numbers.\n4.  Variation in Impact:\n    -   While some provinces remain consistently dark or light across the years, others show more variability, suggesting localized factors influencing drug offense rates.\n\nComparison to Initial Hypothesis:\n\nOur initial hypothesis stated: \"The key indicators of drug abuse in Thailand are spatially dependent, with clusters of high drug use cases likely to be found near borders and urban centers.\"\n\nThe results largely support this hypothesis:\n\n1.  Spatial Dependency: The maps clearly show that drug offense cases are not randomly distributed but follow distinct spatial patterns, confirming spatial dependency.\n\n2.  Urban Centers: Bangkok consistently shows the highest concentration of cases, supporting the hypothesis about urban centers.\n\n3.  Border Regions: Many border provinces show higher case numbers, aligning with the hypothesis about border regions.\n\n4.  Clustering: The maps reveal clear clustering of high-case provinces, particularly in the central, northern, and southern regions.\n\n# **Global Measures of Spatial Autocorrelation**\n\nIn this section, we delve deeper into the spatial patterns of drug offenses across Thailand using global measures of spatial autocorrelation.\n\n**Focus on 2021 Data**: Our analysis will concentrate on data from the fiscal year 2021. This decision is based on our initial exploratory data analysis, which revealed 2021 as the year with the highest number of reported drug offense cases. By focusing on this peak year, we aim to capture the most pronounced spatial patterns and relationships in our dataset.\n\n**Aggregation of Drug Offense Types**: For this analysis, we have aggregated all types of drug offenses into a single metric. This approach allows us to examine the overall drug epidemic landscape without the complexity of distinguishing between different offense categories. Our primary concern is to understand the spatial distribution of the drug problem as a whole, rather than the nuances of specific offense types.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrug_summary_2021 <- data %>%\n  filter(fiscal_year == 2021) %>%\n  group_by(province_en) %>%\n  summarize(total_cases = sum(no_cases, na.rm = TRUE)) %>%\n  arrange(desc(total_cases))\n\n# View the top 10 provinces\nprint(head(drug_summary_2021, 10))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 2\n   province_en         total_cases\n   <chr>                     <dbl>\n 1 Nakhon Si Thammarat       40983\n 2 Bangkok                   37318\n 3 Chiang Mai                28778\n 4 Surat Thani               28566\n 5 Songkhla                  28509\n 6 Ubon Ratchathani          28121\n 7 Khon Kaen                 25903\n 8 Si Sa Ket                 22484\n 9 Udon Thani                22449\n10 Nakhon Ratchasima         21949\n```\n\n\n:::\n\n```{.r .cell-code}\n# bar plot to visualize the top 10 provinces with the highest number of drug cases\ntop_10_provinces <- head(drug_summary_2021, 10)\n\nggplot(top_10_provinces, aes(x = reorder(province_en, total_cases), y = total_cases)) +\n  geom_bar(stat = \"identity\", fill = \"skyblue\") +\n  coord_flip() +\n  labs(title = \"Top 10 Provinces with Highest Drug Cases in 2021\",\n       x = \"Province\",\n       y = \"Total Number of Cases\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex2_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(drug_summary_2021, aes(x = total_cases)) +\n  geom_histogram(binwidth = 1000, fill = \"skyblue\", color = \"black\") +\n  labs(title = \"Distribution of Drug Cases Across Provinces in 2021\",\n       x = \"Total Number of Cases\",\n       y = \"Number of Provinces\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex2_files/figure-html/unnamed-chunk-10-2.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Join the drug data with the shapefile\nmap_data <- adm1 %>%\n  left_join(drug_summary_2021, by = c(\"ADM1_EN\" = \"province_en\"))\n\n# Create the map\ntmap_mode(\"plot\")  # Set tmap mode to static plot\n\nmap <- tm_shape(map_data) +\n  tm_fill(\"total_cases\", \n          style = \"quantile\", \n          palette = \"YlOrRd\",\n          title = \"Number of Drug Cases\") +\n  tm_borders() +\n  tm_layout(title = \"Drug Cases in Thailand (2021)\",\n            legend.outside = TRUE)\n\n# Display the map\nmap\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex2_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Ensure map_data is an sf object\nmap_data <- st_as_sf(map_data)\n\n# Create neighbor list\nnb <- st_contiguity(map_data)\n\n# Create weights\nweights <- st_weights(nb,allow_zero = TRUE)\n\n# Ensure total_cases is numeric\nmap_data$total_cases <- as.numeric(map_data$total_cases)\n\n# Calculate global Moran's I\nmoran_i <- global_moran_test(map_data$total_cases, nb, weights, zero.policy = TRUE)\nprint(moran_i)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  x  \nweights: listw  \nn reduced by no-neighbour observations  \n\nMoran I statistic standard deviate = 2.8146, p-value = 0.002442\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.198888805      -0.013333333       0.005685208 \n```\n\n\n:::\n:::\n\n\nBased on the results of the global Moran's I test, we can interpret the spatial autocorrelation of drug abuse cases in Thailand as follows:\n\n1.  Moran's I statistic: 0.198888805 This positive value indicates a positive spatial autocorrelation, suggesting that provinces with similar numbers of drug abuse cases tend to be clustered together.\n\n2.  p-value: 0.002442 This p-value is well below the typical significance level of 0.05, indicating strong evidence against the null hypothesis of spatial randomness.\n\nInterpretation: The Moran's I test results provide strong statistical evidence for positive spatial autocorrelation in drug cases across Thailand's provinces. This means that provinces with high numbers of drug cases tend to be located near other provinces with high numbers, and provinces with low numbers tend to be near other low-number provinces.\n\nThe low p-value (0.002442) indicates that this spatial pattern is statistically significant and very unlikely to have occurred by chance. This confirms our visual observations from the map and supports our initial hypothesis about the spatial dependency of drug offense patterns in Thailand.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Perform Monte Carlo simulation\nset.seed(123)  # for reproducibility\nmoran_mc_res <- global_moran_perm(\n  map_data$total_cases,\n  nb,\n  weights,\n  nsim = 999,\n  zero.policy = TRUE,\n  na.action = na.omit\n)\n\n# Print results of Monte Carlo simulation\nprint(moran_mc_res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.19889, observed rank = 996, p-value = 0.008\nalternative hypothesis: two.sided\n```\n\n\n:::\n\n```{.r .cell-code}\n# Create histogram\nggplot() + \n  aes(moran_mc_res$res[1:999]) + \n  geom_histogram(colour = \"black\", fill = \"lightblue\", bins = 30) + \n  geom_vline(aes(xintercept = moran_mc_res$statistic), \n             color = \"red\", linetype = \"dashed\", size = 1) +\n  labs(title = \"Histogram of Simulated Moran's I for Thailand Drug Abuse Cases\",\n       subtitle = paste(\"Observed Moran's I:\", round(moran_mc_res$statistic, 4),\n                        \"| p-value:\", round(moran_mc_res$p.value, 4)),\n       x = \"Simulated Moran's I\",\n       y = \"Occurrences\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex2_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\nConclusion:\n\nThe key indicators of drug abuse in Thailand show clear evidence of spatial dependence. The distribution of drug abuse cases across Thai provinces is not random but exhibits a statistically significant pattern of spatial clustering. Provinces with high numbers of drug abuse cases are more likely to be near other provinces with high numbers, and similarly for provinces with low numbers.\n\n# **Local Measures of Spatial Autocorrelation**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate Local Moran's I\nlocal_moran_results <- local_moran(\n  map_data$total_cases,\n  nb,\n  weights,\n  nsim = 999,\n  zero.policy = TRUE\n)\n# Add results to the map_data\nmap_data <- map_data %>%\n  mutate(\n    local_moran_i = local_moran_results$Ii,\n    local_moran_p = local_moran_results$p_folded_sim,\n    local_moran_z = local_moran_results$Z.Ii\n  )\n# Calculate LISA clusters\nmap_data <- map_data %>%\n  mutate(\n    case_lag = st_lag(total_cases, nb, weights),\n    case_scale = scale(total_cases),\n    lag_scale = scale(case_lag),\n    lisa_cluster = case_when(\n      local_moran_p > 0.05 ~ \"Not Significant\",\n      case_scale > 0 & lag_scale > 0 ~ \"High-High\",\n      case_scale < 0 & lag_scale < 0 ~ \"Low-Low\",\n      case_scale > 0 & lag_scale < 0 ~ \"High-Low\",\n      case_scale < 0 & lag_scale > 0 ~ \"Low-High\"\n    )\n  )\n# Create a map of LISA clusters\n\nggplot(map_data) +\n  geom_sf(aes(fill = lisa_cluster), color = \"white\", size = 0.1) +\n  scale_fill_manual(\n    values = c(\"High-High\" = \"red\", \"Low-Low\" = \"blue\", \n               \"Low-High\" = \"lightblue\", \"High-Low\" = \"lightpink\",\n               \"Not Significant\" = \"grey90\"),  # Changed from \"white\" to \"grey90\"\n    na.value = \"grey50\",\n    name = \"LISA Cluster Type\"\n  ) +\n  theme_minimal() +\n  labs(title = \"LISA Cluster Map of Drug Abuse Cases in Thailand\",\n       subtitle = \"Based on Local Moran's I\") +\n  theme(legend.position = \"right\")\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex2_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n1.  Cluster Types:\n\n    -   High-High (Red): Areas where provinces with high drug abuse cases are surrounded by other provinces with high cases.\n    -   Low-Low (Dark Blue): Areas where provinces with low drug abuse cases are surrounded by other provinces with low cases.\n    -   Low-High (Light Blue): Outliers where a province with low cases is surrounded by provinces with high cases.\n    -   Not Significant (Gray): Provinces where there is no significant local spatial autocorrelation.\n    -   NA: Phuket island\n\n2.  Spatial Distribution of Clusters:\n\n    a)  High-High Cluster:\n\n        -   A significant High-High cluster is observed in the southern region of Thailand.\n        -   This cluster could indicate a regional hotspot for drug-related issues.\n\n    b)  Low-Low Cluster:\n\n        -   A large Low-Low cluster is present in the western part of central Thailand.\n        -   It suggests that this region might have factors contributing to lower drug abuse rates or more effective prevention strategies.\n\n    c)  Low-High Outlier:\n\n        -   A single Low-High outlier is observed adjacent to the southern High-High cluster.\n        -   This represents a province with relatively low drug abuse cases surrounded by provinces with high cases.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate Local Gi*\ngi_stars <- local_g_perm(\n  map_data$total_cases,\n  nb,\n  weights,\n  nsim = 999\n)\n\n# Add Gi* results to the map_data\nmap_data$gi_star <- gi_stars$gi \nmap_data$gi_p_sim <- gi_stars$p_sim\nmap_data$gi_p_folded_sim <- gi_stars$p_folded_sim\n\n# Create a map displaying the actual Gi* values\nggplot(map_data) +\n  geom_sf(aes(fill = gi_star), color = \"white\", size = 0.1) +\n  scale_fill_gradient2(\n    low = \"blue\",       # Cold spots (negative Gi*)\n    mid = \"white\",      # Neutral spots (Gi* = 0)\n    high = \"red\",       # Hot spots (positive Gi*)\n    midpoint = 0,       # Midpoint at 0 for neutral\n    name = \"Gi* Value\"  # Legend title for Gi* values\n  ) +\n  theme_minimal() +\n  labs(\n    title = \"Gi* Value Map of Drug Abuse Cases in Thailand\",\n    subtitle = \"Displaying Getis-Ord Gi* Statistic\"\n  )\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex2_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n1.  Hot Spots (Red Areas):\n\n    -   Northeastern Region: There's a notable hot spot in the northeastern part of Thailand, with Gi\\* values around 1 to 2. This suggests a significant cluster of provinces with high numbers of drug abuse cases.\n    -   Southern Region: The southern peninsula shows another prominent hot spot, with some areas reaching the highest Gi\\* values (dark red). This indicates a very strong clustering of high drug abuse cases in this region.\n\n2.  Cold Spots (Purple Areas):\n\n    -   Western Region: A large cold spot is visible in the western part of Thailand, extending from the central region. This area shows negative Gi\\* values, indicating a significant cluster of provinces with lower drug abuse cases.\n    -   Northwestern Region: There's another cold spot in the northwestern part of the country, suggesting another area where drug abuse cases are consistently lower than the national average.\n\n3.  Transition Zones:\n\n    -   Central Region: The central part of Thailand shows a mix of light colors, indicating areas where the drug abuse cases are not significantly different from the national average or where there's no strong spatial clustering.\n\nOur comprehensive spatial analysis of drug abuse cases in Thailand has provided strong evidence for spatial dependency and revealed distinct patterns of clustering across the country. Here's a summary of our findings:\n\n1.  Spatial Dependency:\n    -   The Global Moran's I test (I = 0.1989, p-value = 0.008) confirmed significant positive spatial autocorrelation, indicating that drug abuse cases in Thailand are indeed spatially dependent.\n    -   This spatial dependency suggests that the distribution of drug abuse cases is not random, but influenced by geographical factors and neighborhood effects.\n2.  Clusters and Outliers (LISA Analysis):\n    -   High-High Cluster: A significant cluster of high drug abuse cases was identified in the southern region of Thailand, indicating a concentration of the problem in this area.\n    -   Low-Low Cluster: A large cluster of low drug abuse cases was found in the western part of central Thailand, suggesting a region with relatively lower drug-related issues.\n    -   Low-High Outlier: An interesting outlier was detected adjacent to the southern High-High cluster, representing a province with low cases surrounded by high-case areas.\n3.  Hotspots and Cold Spots (Getis-Ord Gi\\* Analysis):\n    -   Hotspots: Two major hotspots were identified:\n        a)  In the northeastern region, indicating a concentration of high drug abuse cases.\n        b)  In the southern peninsula, confirming and extending the High-High cluster from the LISA analysis.\n    -   Cold Spots: Significant cold spots were detected in:\n        a)  The western region, aligning with the Low-Low cluster from LISA analysis.\n        b)  The northwestern part of the country, revealing another area of consistently lower drug abuse cases.\n4.  Regional Variations:\n    -   The analyses consistently showed that drug abuse patterns vary significantly across different regions of Thailand.\n    -   The central and eastern regions generally showed less significant clustering, suggesting more heterogeneous patterns in these areas.\n\n# **Temporal Evolution of Spatial Patterns Thailand's Drug Offences**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrug_summary_2017 <- data %>% \n  filter(fiscal_year == 2017) %>% \n  group_by(province_en) %>% \n  summarize(total_cases = sum(no_cases, na.rm = TRUE)) %>% \n  arrange(desc(total_cases))\n\nmap_data_2017 <- adm1 %>% \n  left_join(drug_summary_2017, by = c(\"ADM1_EN\" = \"province_en\"))\n\n# Ensure map_data_2017 is an sf object\nmap_data_2017 <- st_as_sf(map_data_2017)\n\n# Create neighbor list for 2017\nnb_2017 <- st_contiguity(map_data_2017)\n\n# Create weights for 2017\nweights_2017 <- st_weights(nb_2017, allow_zero = TRUE)\n\n# Ensure total_cases is numeric\nmap_data_2017$total_cases <- as.numeric(map_data_2017$total_cases)\n\n# Calculate global Moran's I\nmoran_i_2017 <- global_moran_test(map_data_2017$total_cases, nb_2017, weights_2017, zero.policy = TRUE)\nprint(moran_i_2017)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  x  \nweights: listw  \nn reduced by no-neighbour observations  \n\nMoran I statistic standard deviate = 2.4598, p-value = 0.006951\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.133140650      -0.013333333       0.003545946 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Calculate Local Moran's I\nlocal_moran_results_2017 <- local_moran(\n  map_data_2017$total_cases, \n  nb_2017, \n  weights_2017, \n  nsim = 999, \n  zero.policy = TRUE\n)\n\n# Add results to the map_data_2017\nmap_data_2017 <- map_data_2017 %>%\n  mutate(\n    local_moran_i = local_moran_results_2017$Ii,\n    local_moran_p = local_moran_results_2017$p_folded_sim,\n    local_moran_z = local_moran_results_2017$Z.Ii\n  )\n\n# Calculate LISA clusters\nmap_data_2017 <- map_data_2017 %>%\n  mutate(\n    case_lag = st_lag(total_cases, nb_2017, weights_2017),\n    case_scale = scale(total_cases),\n    lag_scale = scale(case_lag),\n    lisa_cluster = case_when(\n      local_moran_p > 0.05 ~ \"Not Significant\",\n      case_scale > 0 & lag_scale > 0 ~ \"High-High\",\n      case_scale < 0 & lag_scale < 0 ~ \"Low-Low\",\n      case_scale > 0 & lag_scale < 0 ~ \"High-Low\",\n      case_scale < 0 & lag_scale > 0 ~ \"Low-High\"\n    )\n  )\n\n# Create a map of LISA clusters\nggplot(map_data_2017) +\n  geom_sf(aes(fill = lisa_cluster), color = \"white\", size = 0.1) +\n  scale_fill_manual(\n    values = c(\"High-High\" = \"red\", \"Low-Low\" = \"blue\", \"Low-High\" = \"lightblue\", \"High-Low\" = \"lightpink\", \"Not Significant\" = \"grey90\"),\n    na.value = \"grey50\",\n    name = \"LISA Cluster Type\"\n  ) +\n  theme_minimal() +\n  labs(title = \"LISA Cluster Map of Drug Abuse Cases in Thailand (2017)\",\n       subtitle = \"Based on Local Moran's I\") +\n  theme(legend.position = \"right\")\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex2_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Calculate Local Gi*\ngi_stars_2017 <- local_g_perm(\n  map_data_2017$total_cases,\n  nb_2017,\n  weights_2017,\n  nsim = 999\n)\n\n# Add Gi* results to the map_data_2017\nmap_data_2017$gi_star <- gi_stars_2017$gi\nmap_data_2017$gi_p_sim <- gi_stars_2017$p_sim\nmap_data_2017$gi_p_folded_sim <- gi_stars_2017$p_folded_sim\n\n# Create a map displaying the actual Gi* values\nggplot(map_data_2017) +\n  geom_sf(aes(fill = gi_star), color = \"white\", size = 0.1) +\n  scale_fill_gradient2(\n    low = \"blue\",\n    mid = \"white\",\n    high = \"red\",\n    midpoint = 0,\n    name = \"Gi* Value\"\n  ) +\n  theme_minimal() +\n  labs(\n    title = \"Gi* Value Map of Drug Abuse Cases in Thailand (2017)\",\n    subtitle = \"Displaying Getis-Ord Gi* Statistic\"\n  )\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex2_files/figure-html/unnamed-chunk-16-2.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndrug_summary_2018 <- data %>% \n  filter(fiscal_year == 2018) %>% \n  group_by(province_en) %>% \n  summarize(total_cases = sum(no_cases, na.rm = TRUE)) %>% \n  arrange(desc(total_cases))\n\nmap_data_2018 <- adm1 %>% \n  left_join(drug_summary_2018, by = c(\"ADM1_EN\" = \"province_en\"))\n\n# Ensure map_data_2018 is an sf object\nmap_data_2018 <- st_as_sf(map_data_2018)\n\n# Create neighbor list for 2018\nnb_2018 <- st_contiguity(map_data_2018)\n\n# Create weights for 2018\nweights_2018 <- st_weights(nb_2018, allow_zero = TRUE)\n\n# Ensure total_cases is numeric\nmap_data_2018$total_cases <- as.numeric(map_data_2018$total_cases)\n\n# Calculate global Moran's I\nmoran_i_2018 <- global_moran_test(map_data_2018$total_cases, nb_2018, weights_2018, zero.policy = TRUE)\nprint(moran_i_2018)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  x  \nweights: listw  \nn reduced by no-neighbour observations  \n\nMoran I statistic standard deviate = 2.1529, p-value = 0.01566\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.116368909      -0.013333333       0.003629353 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Calculate Local Moran's I\nlocal_moran_results_2018 <- local_moran(\n  map_data_2018$total_cases, \n  nb_2018, \n  weights_2018, \n  nsim = 999, \n  zero.policy = TRUE\n)\n\n# Add results to the map_data_2018\nmap_data_2018 <- map_data_2018 %>%\n  mutate(\n    local_moran_i = local_moran_results_2018$Ii,\n    local_moran_p = local_moran_results_2018$p_folded_sim,\n    local_moran_z = local_moran_results_2018$Z.Ii\n  )\n\n# Calculate LISA clusters\nmap_data_2018 <- map_data_2018 %>%\n  mutate(\n    case_lag = st_lag(total_cases, nb_2018, weights_2018),\n    case_scale = scale(total_cases),\n    lag_scale = scale(case_lag),\n    lisa_cluster = case_when(\n      local_moran_p > 0.05 ~ \"Not Significant\",\n      case_scale > 0 & lag_scale > 0 ~ \"High-High\",\n      case_scale < 0 & lag_scale < 0 ~ \"Low-Low\",\n      case_scale > 0 & lag_scale < 0 ~ \"High-Low\",\n      case_scale < 0 & lag_scale > 0 ~ \"Low-High\"\n    )\n  )\n\n# Create a map of LISA clusters\nggplot(map_data_2018) +\n  geom_sf(aes(fill = lisa_cluster), color = \"white\", size = 0.1) +\n  scale_fill_manual(\n    values = c(\"High-High\" = \"red\", \"Low-Low\" = \"blue\", \"Low-High\" = \"lightblue\", \"High-Low\" = \"lightpink\", \"Not Significant\" = \"grey90\"),\n    na.value = \"grey50\",\n    name = \"LISA Cluster Type\"\n  ) +\n  theme_minimal() +\n  labs(title = \"LISA Cluster Map of Drug Abuse Cases in Thailand (2018)\",\n       subtitle = \"Based on Local Moran's I\") +\n  theme(legend.position = \"right\")\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex2_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Calculate Local Gi*\ngi_stars_2018 <- local_g_perm(\n  map_data_2018$total_cases,\n  nb_2018,\n  weights_2018,\n  nsim = 999\n)\n\n# Add Gi* results to the map_data_2018\nmap_data_2018$gi_star <- gi_stars_2018$gi\nmap_data_2018$gi_p_sim <- gi_stars_2018$p_sim\nmap_data_2018$gi_p_folded_sim <- gi_stars_2018$p_folded_sim\n\n# Create a map displaying the actual Gi* values\nggplot(map_data_2018) +\n  geom_sf(aes(fill = gi_star), color = \"white\", size = 0.1) +\n  scale_fill_gradient2(\n    low = \"blue\",\n    mid = \"white\",\n    high = \"red\",\n    midpoint = 0,\n    name = \"Gi* Value\"\n  ) +\n  theme_minimal() +\n  labs(\n    title = \"Gi* Value Map of Drug Abuse Cases in Thailand (2018)\",\n    subtitle = \"Displaying Getis-Ord Gi* Statistic\"\n  )\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex2_files/figure-html/unnamed-chunk-17-2.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndrug_summary_2019 <- data %>% \n  filter(fiscal_year == 2019) %>% \n  group_by(province_en) %>% \n  summarize(total_cases = sum(no_cases, na.rm = TRUE)) %>% \n  arrange(desc(total_cases))\n\nmap_data_2019 <- adm1 %>% \n  left_join(drug_summary_2019, by = c(\"ADM1_EN\" = \"province_en\"))\n\n# Ensure map_data_2019 is an sf object\nmap_data_2019 <- st_as_sf(map_data_2019)\n\n# Create neighbor list for 2019\nnb_2019 <- st_contiguity(map_data_2019)\n\n# Create weights for 2019\nweights_2019 <- st_weights(nb_2019, allow_zero = TRUE)\n\n# Ensure total_cases is numeric\nmap_data_2019$total_cases <- as.numeric(map_data_2019$total_cases)\n\n# Calculate global Moran's I\nmoran_i_2019 <- global_moran_test(map_data_2019$total_cases, nb_2019, weights_2019, zero.policy = TRUE)\nprint(moran_i_2019)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  x  \nweights: listw  \nn reduced by no-neighbour observations  \n\nMoran I statistic standard deviate = 2.4911, p-value = 0.006367\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.155405262      -0.013333333       0.004588259 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Calculate Local Moran's I\nlocal_moran_results_2019 <- local_moran(\n  map_data_2019$total_cases, \n  nb_2019, \n  weights_2019, \n  nsim = 999, \n  zero.policy = TRUE\n)\n\n# Add results to the map_data_2019\nmap_data_2019 <- map_data_2019 %>%\n  mutate(\n    local_moran_i = local_moran_results_2019$Ii,\n    local_moran_p = local_moran_results_2019$p_folded_sim,\n    local_moran_z = local_moran_results_2019$Z.Ii\n  )\n\n# Calculate LISA clusters\nmap_data_2019 <- map_data_2019 %>%\n  mutate(\n    case_lag = st_lag(total_cases, nb_2019, weights_2019),\n    case_scale = scale(total_cases),\n    lag_scale = scale(case_lag),\n    lisa_cluster = case_when(\n      local_moran_p > 0.05 ~ \"Not Significant\",\n      case_scale > 0 & lag_scale > 0 ~ \"High-High\",\n      case_scale < 0 & lag_scale < 0 ~ \"Low-Low\",\n      case_scale > 0 & lag_scale < 0 ~ \"High-Low\",\n      case_scale < 0 & lag_scale > 0 ~ \"Low-High\"\n    )\n  )\n\n# Create a map of LISA clusters\nggplot(map_data_2019) +\n  geom_sf(aes(fill = lisa_cluster), color = \"white\", size = 0.1) +\n  scale_fill_manual(\n    values = c(\"High-High\" = \"red\", \"Low-Low\" = \"blue\", \"Low-High\" = \"lightblue\", \"High-Low\" = \"lightpink\", \"Not Significant\" = \"grey90\"),\n    na.value = \"grey50\",\n    name = \"LISA Cluster Type\"\n  ) +\n  theme_minimal() +\n  labs(title = \"LISA Cluster Map of Drug Abuse Cases in Thailand (2019)\",\n       subtitle = \"Based on Local Moran's I\") +\n  theme(legend.position = \"right\")\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex2_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Calculate Local Gi*\ngi_stars_2019 <- local_g_perm(\n  map_data_2019$total_cases,\n  nb_2019,\n  weights_2019,\n  nsim = 999\n)\n\n# Add Gi* results to the map_data_2019\nmap_data_2019$gi_star <- gi_stars_2019$gi\nmap_data_2019$gi_p_sim <- gi_stars_2019$p_sim\nmap_data_2019$gi_p_folded_sim <- gi_stars_2019$p_folded_sim\n\n# Create a map displaying the actual Gi* values\nggplot(map_data_2019) +\n  geom_sf(aes(fill = gi_star), color = \"white\", size = 0.1) +\n  scale_fill_gradient2(\n    low = \"blue\",\n    mid = \"white\",\n    high = \"red\",\n    midpoint = 0,\n    name = \"Gi* Value\"\n  ) +\n  theme_minimal() +\n  labs(\n    title = \"Gi* Value Map of Drug Abuse Cases in Thailand (2019)\",\n    subtitle = \"Displaying Getis-Ord Gi* Statistic\"\n  )\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex2_files/figure-html/unnamed-chunk-18-2.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndrug_summary_2020 <- data %>% \n  filter(fiscal_year == 2020) %>% \n  group_by(province_en) %>% \n  summarize(total_cases = sum(no_cases, na.rm = TRUE)) %>% \n  arrange(desc(total_cases))\n\nmap_data_2020 <- adm1 %>% \n  left_join(drug_summary_2020, by = c(\"ADM1_EN\" = \"province_en\"))\n\n# Ensure map_data_2020 is an sf object\nmap_data_2020 <- st_as_sf(map_data_2020)\n\n# Create neighbor list for 2020\nnb_2020 <- st_contiguity(map_data_2020)\n\n# Create weights for 2020\nweights_2020 <- st_weights(nb_2020, allow_zero = TRUE)\n\n# Ensure total_cases is numeric\nmap_data_2020$total_cases <- as.numeric(map_data_2020$total_cases)\n\n# Calculate global Moran's I\nmoran_i_2020 <- global_moran_test(map_data_2020$total_cases, nb_2020, weights_2020, zero.policy = TRUE)\nprint(moran_i_2020)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  x  \nweights: listw  \nn reduced by no-neighbour observations  \n\nMoran I statistic standard deviate = 1.9969, p-value = 0.02292\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.129597584      -0.013333333       0.005123377 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Calculate Local Moran's I\nlocal_moran_results_2020 <- local_moran(\n  map_data_2020$total_cases, \n  nb_2020, \n  weights_2020, \n  nsim = 999, \n  zero.policy = TRUE\n)\n\n# Add results to the map_data_2020\nmap_data_2020 <- map_data_2020 %>%\n  mutate(\n    local_moran_i = local_moran_results_2020$Ii,\n    local_moran_p = local_moran_results_2020$p_folded_sim,\n    local_moran_z = local_moran_results_2020$Z.Ii\n  )\n\n# Calculate LISA clusters\nmap_data_2020 <- map_data_2020 %>%\n  mutate(\n    case_lag = st_lag(total_cases, nb_2020, weights_2020),\n    case_scale = scale(total_cases),\n    lag_scale = scale(case_lag),\n    lisa_cluster = case_when(\n      local_moran_p > 0.05 ~ \"Not Significant\",\n      case_scale > 0 & lag_scale > 0 ~ \"High-High\",\n      case_scale < 0 & lag_scale < 0 ~ \"Low-Low\",\n      case_scale > 0 & lag_scale < 0 ~ \"High-Low\",\n      case_scale < 0 & lag_scale > 0 ~ \"Low-High\"\n    )\n  )\n\n# Create a map of LISA clusters\nggplot(map_data_2020) +\n  geom_sf(aes(fill = lisa_cluster), color = \"white\", size = 0.1) +\n  scale_fill_manual(\n    values = c(\"High-High\" = \"red\", \"Low-Low\" = \"blue\", \"Low-High\" = \"lightblue\", \"High-Low\" = \"lightpink\", \"Not Significant\" = \"grey90\"),\n    na.value = \"grey50\",\n    name = \"LISA Cluster Type\"\n  ) +\n  theme_minimal() +\n  labs(title = \"LISA Cluster Map of Drug Abuse Cases in Thailand (2020)\",\n       subtitle = \"Based on Local Moran's I\") +\n  theme(legend.position = \"right\")\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex2_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Calculate Local Gi*\ngi_stars_2020 <- local_g_perm(\n  map_data_2020$total_cases,\n  nb_2020,\n  weights_2020,\n  nsim = 999\n)\n\n# Add Gi* results to the map_data_2020\nmap_data_2020$gi_star <- gi_stars_2020$gi\nmap_data_2020$gi_p_sim <- gi_stars_2020$p_sim\nmap_data_2020$gi_p_folded_sim <- gi_stars_2020$p_folded_sim\n\n# Create a map displaying the actual Gi* values\nggplot(map_data_2020) +\n  geom_sf(aes(fill = gi_star), color = \"white\", size = 0.1) +\n  scale_fill_gradient2(\n    low = \"blue\",\n    mid = \"white\",\n    high = \"red\",\n    midpoint = 0,\n    name = \"Gi* Value\"\n  ) +\n  theme_minimal() +\n  labs(\n    title = \"Gi* Value Map of Drug Abuse Cases in Thailand (2020)\",\n    subtitle = \"Displaying Getis-Ord Gi* Statistic\"\n  )\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex2_files/figure-html/unnamed-chunk-19-2.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndrug_summary_2021 <- data %>% \n  filter(fiscal_year == 2021) %>% \n  group_by(province_en) %>% \n  summarize(total_cases = sum(no_cases, na.rm = TRUE)) %>% \n  arrange(desc(total_cases))\n\nmap_data_2021 <- adm1 %>% \n  left_join(drug_summary_2021, by = c(\"ADM1_EN\" = \"province_en\"))\n\n# Ensure map_data_2021 is an sf object\nmap_data_2021 <- st_as_sf(map_data_2021)\n\n# Create neighbor list for 2021\nnb_2021 <- st_contiguity(map_data_2021)\n\n# Create weights for 2021\nweights_2021 <- st_weights(nb_2021, allow_zero = TRUE)\n\n# Ensure total_cases is numeric\nmap_data_2021$total_cases <- as.numeric(map_data_2021$total_cases)\n\n# Calculate global Moran's I\nmoran_i_2021 <- global_moran_test(map_data_2021$total_cases, nb_2021, weights_2021, zero.policy = TRUE)\nprint(moran_i_2021)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  x  \nweights: listw  \nn reduced by no-neighbour observations  \n\nMoran I statistic standard deviate = 2.8146, p-value = 0.002442\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.198888805      -0.013333333       0.005685208 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Calculate Local Moran's I\nlocal_moran_results_2021 <- local_moran(\n  map_data_2021$total_cases, \n  nb_2021, \n  weights_2021, \n  nsim = 999, \n  zero.policy = TRUE\n)\n\n# Add results to the map_data_2021\nmap_data_2021 <- map_data_2021 %>%\n  mutate(\n    local_moran_i = local_moran_results_2021$Ii,\n    local_moran_p = local_moran_results_2021$p_folded_sim,\n    local_moran_z = local_moran_results_2021$Z.Ii\n  )\n\n# Calculate LISA clusters\nmap_data_2021 <- map_data_2021 %>%\n  mutate(\n    case_lag = st_lag(total_cases, nb_2021, weights_2021),\n    case_scale = scale(total_cases),\n    lag_scale = scale(case_lag),\n    lisa_cluster = case_when(\n      local_moran_p > 0.05 ~ \"Not Significant\",\n      case_scale > 0 & lag_scale > 0 ~ \"High-High\",\n      case_scale < 0 & lag_scale < 0 ~ \"Low-Low\",\n      case_scale > 0 & lag_scale < 0 ~ \"High-Low\",\n      case_scale < 0 & lag_scale > 0 ~ \"Low-High\"\n    )\n  )\n\n# Create a map of LISA clusters\nggplot(map_data_2021) +\n  geom_sf(aes(fill = lisa_cluster), color = \"white\", size = 0.1) +\n  scale_fill_manual(\n    values = c(\"High-High\" = \"red\", \"Low-Low\" = \"blue\", \"Low-High\" = \"lightblue\", \"High-Low\" = \"lightpink\", \"Not Significant\" = \"grey90\"),\n    na.value = \"grey50\",\n    name = \"LISA Cluster Type\"\n  ) +\n  theme_minimal() +\n  labs(title = \"LISA Cluster Map of Drug Abuse Cases in Thailand (2021)\",\n       subtitle = \"Based on Local Moran's I\") +\n  theme(legend.position = \"right\")\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex2_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Calculate Local Gi*\ngi_stars_2021 <- local_g_perm(\n  map_data_2021$total_cases,\n  nb_2021,\n  weights_2021,\n  nsim = 999\n)\n\n# Add Gi* results to the map_data_2021\nmap_data_2021$gi_star <- gi_stars_2021$gi\nmap_data_2021$gi_p_sim <- gi_stars_2021$p_sim\nmap_data_2021$gi_p_folded_sim <- gi_stars_2021$p_folded_sim\n\n# Create a map displaying the actual Gi* values\nggplot(map_data_2021) +\n  geom_sf(aes(fill = gi_star), color = \"white\", size = 0.1) +\n  scale_fill_gradient2(\n    low = \"blue\",\n    mid = \"white\",\n    high = \"red\",\n    midpoint = 0,\n    name = \"Gi* Value\"\n  ) +\n  theme_minimal() +\n  labs(\n    title = \"Gi* Value Map of Drug Abuse Cases in Thailand (2021)\",\n    subtitle = \"Displaying Getis-Ord Gi* Statistic\"\n  )\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex2_files/figure-html/unnamed-chunk-20-2.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndrug_summary_2022 <- data %>% \n  filter(fiscal_year == 2022) %>% \n  group_by(province_en) %>% \n  summarize(total_cases = sum(no_cases, na.rm = TRUE)) %>% \n  arrange(desc(total_cases))\n\nmap_data_2022 <- adm1 %>% \n  left_join(drug_summary_2022, by = c(\"ADM1_EN\" = \"province_en\"))\n\n# Ensure map_data_2022 is an sf object\nmap_data_2022 <- st_as_sf(map_data_2022)\n\n# Create neighbor list for 2022\nnb_2022 <- st_contiguity(map_data_2022)\n\n# Create weights for 2022\nweights_2022 <- st_weights(nb_2022, allow_zero = TRUE)\n\n# Ensure total_cases is numeric\nmap_data_2022$total_cases <- as.numeric(map_data_2022$total_cases)\n\n# Calculate global Moran's I\nmoran_i_2022 <- global_moran_test(map_data_2022$total_cases, nb_2022, weights_2022, zero.policy = TRUE)\nprint(moran_i_2022)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  x  \nweights: listw  \nn reduced by no-neighbour observations  \n\nMoran I statistic standard deviate = 2.7999, p-value = 0.002556\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n       0.20112705       -0.01333333        0.00586698 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Calculate Local Moran's I\nlocal_moran_results_2022 <- local_moran(\n  map_data_2022$total_cases, \n  nb_2022, \n  weights_2022, \n  nsim = 999, \n  zero.policy = TRUE\n)\n\n# Add results to the map_data_2022\nmap_data_2022 <- map_data_2022 %>%\n  mutate(\n    local_moran_i = local_moran_results_2022$Ii,\n    local_moran_p = local_moran_results_2022$p_folded_sim,\n    local_moran_z = local_moran_results_2022$Z.Ii\n  )\n\n# Calculate LISA clusters\nmap_data_2022 <- map_data_2022 %>%\n  mutate(\n    case_lag = st_lag(total_cases, nb_2022, weights_2022),\n    case_scale = scale(total_cases),\n    lag_scale = scale(case_lag),\n    lisa_cluster = case_when(\n      local_moran_p > 0.05 ~ \"Not Significant\",\n      case_scale > 0 & lag_scale > 0 ~ \"High-High\",\n      case_scale < 0 & lag_scale < 0 ~ \"Low-Low\",\n      case_scale > 0 & lag_scale < 0 ~ \"High-Low\",\n      case_scale < 0 & lag_scale > 0 ~ \"Low-High\"\n    )\n  )\n\n# Create a map of LISA clusters\nggplot(map_data_2022) +\n  geom_sf(aes(fill = lisa_cluster), color = \"white\", size = 0.1) +\n  scale_fill_manual(\n    values = c(\"High-High\" = \"red\", \"Low-Low\" = \"blue\", \"Low-High\" = \"lightblue\", \"High-Low\" = \"lightpink\", \"Not Significant\" = \"grey90\"),\n    na.value = \"grey50\",\n    name = \"LISA Cluster Type\"\n  ) +\n  theme_minimal() +\n  labs(title = \"LISA Cluster Map of Drug Abuse Cases in Thailand (2022)\",\n       subtitle = \"Based on Local Moran's I\") +\n  theme(legend.position = \"right\")\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex2_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Calculate Local Gi*\ngi_stars_2022 <- local_g_perm(\n  map_data_2022$total_cases,\n  nb_2022,\n  weights_2022,\n  nsim = 999\n)\n\n# Add Gi* results to the map_data_2022\nmap_data_2022$gi_star <- gi_stars_2022$gi\nmap_data_2022$gi_p_sim <- gi_stars_2022$p_sim\nmap_data_2022$gi_p_folded_sim <- gi_stars_2022$p_folded_sim\n\n# Create a map displaying the actual Gi* values\nggplot(map_data_2022) +\n  geom_sf(aes(fill = gi_star), color = \"white\", size = 0.1) +\n  scale_fill_gradient2(\n    low = \"blue\",\n    mid = \"white\",\n    high = \"red\",\n    midpoint = 0,\n    name = \"Gi* Value\"\n  ) +\n  theme_minimal() +\n  labs(\n    title = \"Gi* Value Map of Drug Abuse Cases in Thailand (2022)\",\n    subtitle = \"Displaying Getis-Ord Gi* Statistic\"\n  )\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex2_files/figure-html/unnamed-chunk-21-2.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Function to create LISA cluster map\ncreate_lisa_map <- function(map_data, year) {\n  ggplot(map_data) +\n    geom_sf(aes(fill = lisa_cluster), color = \"white\", size = 0.1) +\n    scale_fill_manual(\n      values = c(\"High-High\" = \"red\", \"Low-Low\" = \"blue\", \"Low-High\" = \"lightblue\", \"High-Low\" = \"lightpink\", \"Not Significant\" = \"grey90\"),\n      na.value = \"grey50\",\n      name = \"LISA Cluster Type\"\n    ) +\n    theme_minimal() +\n    labs(title = paste(\"LISA\", year)) +\n    theme(\n      legend.position = \"none\", \n      plot.title = element_text(size = 10),\n      axis.text.x = element_blank(),\n      axis.text.y = element_blank(),\n      axis.ticks = element_blank()\n    )\n}\n\n# Function to create Gi* value map\ncreate_gi_star_map <- function(map_data, year) {\n  ggplot(map_data) +\n    geom_sf(aes(fill = gi_star), color = \"white\", size = 0.1) +\n    scale_fill_gradient2(\n      low = \"blue\",\n      mid = \"white\",\n      high = \"red\",\n      midpoint = 0,\n      name = \"Gi* Value\"\n    ) +\n    theme_minimal() +\n    labs(title = paste(\"Gi*\", year)) +\n    theme(\n      legend.position = \"none\", \n      plot.title = element_text(size = 10),\n      axis.text.x = element_blank(),\n      axis.text.y = element_blank(),\n      axis.ticks = element_blank()\n    )\n}\n\n# Create LISA maps for all years\nlisa_map_2017 <- create_lisa_map(map_data_2017, 2017)\nlisa_map_2018 <- create_lisa_map(map_data_2018, 2018)\nlisa_map_2019 <- create_lisa_map(map_data_2019, 2019)\nlisa_map_2020 <- create_lisa_map(map_data_2020, 2020)\nlisa_map_2021 <- create_lisa_map(map_data_2021, 2021)\nlisa_map_2022 <- create_lisa_map(map_data_2022, 2022)\n\n# Create Gi* maps for all years\ngi_star_map_2017 <- create_gi_star_map(map_data_2017, 2017)\ngi_star_map_2018 <- create_gi_star_map(map_data_2018, 2018)\ngi_star_map_2019 <- create_gi_star_map(map_data_2019, 2019)\ngi_star_map_2020 <- create_gi_star_map(map_data_2020, 2020)\ngi_star_map_2021 <- create_gi_star_map(map_data_2021, 2021)\ngi_star_map_2022 <- create_gi_star_map(map_data_2022, 2022)\n\n# Combine all LISA maps\ncombined_lisa <- (lisa_map_2017 | lisa_map_2018 | lisa_map_2019) /\n                 (lisa_map_2020 | lisa_map_2021 | lisa_map_2022) +\n  plot_annotation(\n    title = \"LISA Cluster Maps of Drug Abuse Cases in Thailand (2017-2022)\",\n    theme = theme(plot.title = element_text(size = 16, hjust = 0.5))\n  )\n\n# Combine all Gi* maps\ncombined_gi_star <- (gi_star_map_2017 | gi_star_map_2018 | gi_star_map_2019) /\n                    (gi_star_map_2020 | gi_star_map_2021 | gi_star_map_2022) +\n  plot_annotation(\n    title = \"Gi* Value Maps of Drug Abuse Cases in Thailand (2017-2022)\",\n    theme = theme(plot.title = element_text(size = 16, hjust = 0.5))\n  )\n\n# Display the combined maps\nprint(combined_lisa)\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex2_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n\n```{.r .cell-code}\nprint(combined_gi_star)\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex2_files/figure-html/unnamed-chunk-22-2.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(\"Moran I 2017\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Moran I 2017\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(moran_i_2017)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  x  \nweights: listw  \nn reduced by no-neighbour observations  \n\nMoran I statistic standard deviate = 2.4598, p-value = 0.006951\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.133140650      -0.013333333       0.003545946 \n```\n\n\n:::\n\n```{.r .cell-code}\nprint(\"Moran I 2018\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Moran I 2018\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(moran_i_2018)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  x  \nweights: listw  \nn reduced by no-neighbour observations  \n\nMoran I statistic standard deviate = 2.1529, p-value = 0.01566\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.116368909      -0.013333333       0.003629353 \n```\n\n\n:::\n\n```{.r .cell-code}\nprint(\"Moran I 2019\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Moran I 2019\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(moran_i_2019)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  x  \nweights: listw  \nn reduced by no-neighbour observations  \n\nMoran I statistic standard deviate = 2.4911, p-value = 0.006367\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.155405262      -0.013333333       0.004588259 \n```\n\n\n:::\n\n```{.r .cell-code}\nprint(\"Moran I 2020\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Moran I 2020\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(moran_i_2020)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  x  \nweights: listw  \nn reduced by no-neighbour observations  \n\nMoran I statistic standard deviate = 1.9969, p-value = 0.02292\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.129597584      -0.013333333       0.005123377 \n```\n\n\n:::\n\n```{.r .cell-code}\nprint(\"Moran I 2021\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Moran I 2021\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(moran_i_2021)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  x  \nweights: listw  \nn reduced by no-neighbour observations  \n\nMoran I statistic standard deviate = 2.8146, p-value = 0.002442\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.198888805      -0.013333333       0.005685208 \n```\n\n\n:::\n\n```{.r .cell-code}\nprint(\"Moran I 2022\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Moran I 2022\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(moran_i_2022)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  x  \nweights: listw  \nn reduced by no-neighbour observations  \n\nMoran I statistic standard deviate = 2.7999, p-value = 0.002556\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n       0.20112705       -0.01333333        0.00586698 \n```\n\n\n:::\n:::\n\n\n1.  Moran's I Statistics:\n    -   All years show statistically significant positive spatial autocorrelation (p-values \\< 0.05).\n    -   The Moran's I statistic increases over time, from 0.133 in 2017 to 0.201 in 2022, indicating strengthening spatial clustering.\n    -   The most significant jump occurs between 2020 (I = 0.130) and 2021 (I = 0.199), suggesting a notable increase in spatial dependency.\n2.  LISA Cluster Maps:\n    -   2017-2020: Consistent Low-Low cluster in the western region and small High-High clusters in the central and southern regions.\n    -   2021: Significant expansion of the Low-Low cluster in the west and central regions.\n    -   2022: Dramatic shift with a large High-High cluster emerging in the northeastern region, while maintaining the western Low-Low cluster.\n3.  Gi\\* Value Maps:\n    -   2017-2019: Relatively stable patterns with cold spots (purple) in the west and hot spots (red) in the south and central regions.\n    -   2020: Intensification of the western cold spot and southern hot spot.\n    -   2021: Significant expansion of the western cold spot and intensification of the southern hot spot.\n    -   2022: Major shift with a new large hot spot in the northeast, while maintaining the western cold spot.\n\nKey Observations on Temporal Evolution:\n\n1.  Increasing Spatial Dependency: The consistent increase in Moran's I values indicates that drug abuse patterns became more spatially clustered over time.\n\n2.  Stability and Change:\n\n    -   Western Region: Consistently maintained as a Low-Low cluster/cold spot throughout the period.\n    -   Southern Region: Relatively stable hot spot, with some fluctuations in intensity.\n    -   Northeastern Region: Dramatic shift in 2022, emerging as a significant High-High cluster/hot spot.\n\n3.  Critical Transition in 2021-2022:\n\n    -   2021 marked a significant increase in spatial clustering.\n    -   2022 saw a major redistribution of drug abuse patterns, with the northeastern region becoming a new area of concern.\n\n4.  Regional Dynamics:\n\n    -   The western region consistently performed well in managing drug abuse.\n    -   The southern region remained a persistent area of concern.\n    -   The northeastern region's sudden emergence as a hot spot in 2022 warrants immediate attention.\n\n# **Overall Spatial Patterns Analysis**\n\nBased on all the analyses conducted, including the LISA Cluster Maps, Gi\\* Value Maps, and Moran's I statistics from 2017 to 2022, we can describe the following spatial patterns of drug abuse cases in Thailand:\n\n1.  **Overall Spatial Dependency**:\n    -   Throughout the study period, drug abuse cases in Thailand consistently showed significant positive spatial autocorrelation.\n    -   This indicates that provinces with similar levels of drug abuse tend to cluster together, rather than being randomly distributed across the country.\n    -   The strength of this spatial dependency increased over time, with Moran's I values rising from 0.133 in 2017 to 0.201 in 2022.\n2.  **Persistent Western Cold Spot**:\n    -   The western region of Thailand consistently appeared as a Low-Low cluster in LISA maps and a cold spot in Gi\\* maps across all years.\n    -   This area maintained lower drug abuse rates compared to the national average, suggesting the presence of protective factors or effective drug control measures in this region.\n3.  **Southern Hot Spot Evolution**:\n    -   The southern peninsula of Thailand frequently appeared as a hot spot or High-High cluster, particularly in the earlier years of the study period (2017-2020).\n    -   This region consistently showed higher rates of drug abuse cases during this time, indicating a persistent problem area.\n    -   However, by 2022, the southern region's drug offense rates decreased significantly, becoming comparable to the rest of the country.\n4.  **Central Region Variability**:\n    -   The central region, including and surrounding Bangkok, consistently appeared as a hotspot from 2017 to 2021.\n    -   This densely populated area maintained higher rates of drug abuse cases compared to the national average for most of the study period.\n    -   However, in 2022, there was a significant decrease in drug offense cases in this region. By 2022, the central region, including Bangkok, ceased to be a hotspot for drug offense cases and returned to levels comparable with the rest of the country.\n    -   This shift suggests a potentially successful implementation of drug control measures or changes in socio-economic factors influencing drug abuse patterns in this urban center.\n5.  **Northeastern Region Shift**:\n    -   From 2017 to 2021, the northeastern region showed relatively low or non-significant clustering in terms of drug offense hot spots.\n    -   In 2022, it emerged as a significant High-High cluster and hot spot in relative terms.\n    -   However, when examining the total drug offense cases by year, the region actually shows relatively stable numbers throughout the study period.\n    -   The apparent emergence of the northeastern region as a hot spot in 2022 is primarily due to a significant decrease in drug offense cases in other parts of the country, rather than an increase in the northeast itself.\n6.  **Border Region Patterns**:\n    -   Provinces bordering neighboring countries often showed significant clustering, though the nature of these clusters varied:\n        -   Western border: Consistently low drug abuse rates\n        -   Southern border: Initially high rates, but decreasing by 2022\n        -   Northern and eastern borders: Variable patterns, with a notable relative shift in the northeast in 2022\n7.  **Urban-Rural Divide**:\n    -   Major urban centers, particularly in the central region (Bangkok), often showed distinct patterns compared to surrounding rural areas, though this distinction lessened by 2022.\n8.  **Temporal Evolution**:\n    -   The western cold spot remained stable, while other regions experienced more dynamic shifts.\n    -   A general trend of decreasing drug offense cases was observed across much of the country by 2022.\n9.  **Regional Contrasts**:\n    -   Clear contrasts emerged between different regions of Thailand, but these contrasts evolved over time:\n        -   The western region consistently performed well in managing drug abuse.\n        -   The southern region transitioned from a persistent area of concern to showing improvement by 2022.\n        -   The northeastern region appeared to become a relative hotspot due to decreases elsewhere, rather than absolute increases.\n10. **Spatial Outliers**:\n    -   Occasional Low-High or High-Low outliers appeared in different years, representing provinces that diverged from their neighbors' patterns.\n\nIn summary, the spatial patterns of drug abuse in Thailand reveal a complex, dynamic landscape with significant regional variations. While some areas maintained consistent patterns over time, others underwent dramatic changes, particularly in the latter years of the study period.\n\nThe overall trend by 2022 shows a general decrease in drug offense cases across much of the country.\n\n# **Bonus Section: Advanced Spatio-Temporal Analysis Using Space-Time Cube**\n\nTo gain deeper insights into the temporal and spatial dynamics of drug abuse cases in Thailand, we employed an advanced visualization technique known as Space-Time Cube Analysis. This method goes beyond traditional 2D mapping and time series analysis by integrating both spatial and temporal dimensions into a single 3D visualization.\n\n**Methodology:**\n\nWe created a 3D scatter plot using R and the Plotly library, where: - X and Y axes represent geographical space (longitude and latitude of Thai provinces) - Z-axis represents time (fiscal years from 2017 to 2022) - Point size and color intensity indicate the number of drug abuse cases\n\nThe Space-Time Cube Analysis offers several advantages over conventional methods:\n\n1\\. Simultaneous visualization of spatial and temporal trends\n\n2\\. Enhanced pattern recognition in three-dimensional space\n\n3\\. Ability to identify persistent hotspots, emerging problem areas, and improving regions\n\n4\\. Potential for interactive exploration\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Prepare data for all years\ndrug_summary_all <- data %>%\n  group_by(province_en, fiscal_year) %>%\n  summarize(total_cases = sum(no_cases, na.rm = TRUE)) %>%\n  ungroup()\n\n# Join with spatial data\nmap_data_all <- adm1 %>%\n  left_join(drug_summary_all, by = c(\"ADM1_EN\" = \"province_en\"))\n\n# Calculate centroids of each province\ncentroids <- st_centroid(map_data_all)\ncentroids_coords <- st_coordinates(centroids)\n\n# Create the 3D plot\nplot_ly() %>%\n  add_trace(\n    x = centroids_coords[, 1],\n    y = centroids_coords[, 2],\n    z = map_data_all$fiscal_year,\n    size = map_data_all$total_cases,\n    color = map_data_all$total_cases,\n    type = \"scatter3d\",\n    mode = \"markers\",\n    marker = list(symbol = 'circle', sizemode = 'diameter'),\n    hoverinfo = 'text',\n    text = ~paste(\"Province: \", map_data_all$ADM1_EN, \n                  \"<br>Year: \", map_data_all$fiscal_year,\n                  \"<br>Total Cases: \", map_data_all$total_cases)\n  ) %>%\n  layout(\n    scene = list(\n      xaxis = list(title = \"Longitude\"),\n      yaxis = list(title = \"Latitude\"),\n      zaxis = list(title = \"Year\")\n    ),\n    title = \"Space-Time Cube of Drug Abuse Cases in Thailand (2017-2022)\"\n  )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-7695744ab5b8c17a9046\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-7695744ab5b8c17a9046\">{\"x\":{\"visdat\":{\"3140539e79e6\":[\"function () \",\"plotlyVisDat\"]},\"cur_data\":\"3140539e79e6\",\"attrs\":{\"3140539e79e6\":{\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"x\":[100.62346136424746,100.62346136424746,100.62346136424746,100.62346136424746,100.62346136424746,100.62346136424746,100.71023157204732,100.71023157204732,100.71023157204732,100.71023157204732,100.71023157204732,100.71023157204732,100.39284437729408,100.39284437729408,100.39284437729408,100.39284437729408,100.39284437729408,100.39284437729408,100.68237573701045,100.68237573701045,100.68237573701045,100.68237573701045,100.68237573701045,100.68237573701045,100.52658206775011,100.52658206775011,100.52658206775011,100.52658206775011,100.52658206775011,100.52658206775011,100.34852189532658,100.34852189532658,100.34852189532658,100.34852189532658,100.34852189532658,100.34852189532658,100.90693523816465,100.90693523816465,100.90693523816465,100.90693523816465,100.90693523816465,100.90693523816465,100.34721554976805,100.34721554976805,100.34721554976805,100.34721554976805,100.34721554976805,100.34721554976805,100.02746225500066,100.02746225500066,100.02746225500066,100.02746225500066,100.02746225500066,100.02746225500066,101.01687337340066,101.01687337340066,101.01687337340066,101.01687337340066,101.01687337340066,101.01687337340066,101.20152594716131,101.20152594716131,101.20152594716131,101.20152594716131,101.20152594716131,101.20152594716131,101.4274815704137,101.4274815704137,101.4274815704137,101.4274815704137,101.4274815704137,101.4274815704137,102.13018937580715,102.13018937580715,102.13018937580715,102.13018937580715,102.13018937580715,102.13018937580715,102.52166692213197,102.52166692213197,102.52166692213197,102.52166692213197,102.52166692213197,102.52166692213197,101.42566537600294,101.42566537600294,101.42566537600294,101.42566537600294,101.42566537600294,101.42566537600294,101.65029268511354,101.65029268511354,101.65029268511354,101.65029268511354,101.65029268511354,101.65029268511354,101.17132031170088,101.17132031170088,101.17132031170088,101.17132031170088,101.17132031170088,101.17132031170088,102.32254595676091,102.32254595676091,102.32254595676091,102.32254595676091,102.32254595676091,102.32254595676091,102.10918946975428,102.10918946975428,102.10918946975428,102.10918946975428,102.10918946975428,102.10918946975428,102.95638684337747,102.95638684337747,102.95638684337747,102.95638684337747,102.95638684337747,102.95638684337747,103.65589320101067,103.65589320101067,103.65589320101067,103.65589320101067,103.65589320101067,103.65589320101067,104.36937796146215,104.36937796146215,104.36937796146215,104.36937796146215,104.36937796146215,104.36937796146215,105.11159291657839,105.11159291657839,105.11159291657839,105.11159291657839,105.11159291657839,105.11159291657839,104.33828904209687,104.33828904209687,104.33828904209687,104.33828904209687,104.33828904209687,104.33828904209687,101.81923565920435,101.81923565920435,101.81923565920435,101.81923565920435,101.81923565920435,101.81923565920435,104.74125515291696,104.74125515291696,104.74125515291696,104.74125515291696,104.74125515291696,104.74125515291696,103.71112124377785,103.71112124377785,103.71112124377785,103.71112124377785,103.71112124377785,103.71112124377785,102.30251002772171,102.30251002772171,102.30251002772171,102.30251002772171,102.30251002772171,102.30251002772171,102.57837215749053,102.57837215749053,102.57837215749053,102.57837215749053,102.57837215749053,102.57837215749053,102.86324901561068,102.86324901561068,102.86324901561068,102.86324901561068,102.86324901561068,102.86324901561068,101.63584153310288,101.63584153310288,101.63584153310288,101.63584153310288,101.63584153310288,101.63584153310288,102.83371850222453,102.83371850222453,102.83371850222453,102.83371850222453,102.83371850222453,102.83371850222453,103.16573568947332,103.16573568947332,103.16573568947332,103.16573568947332,103.16573568947332,103.16573568947332,103.81363127030255,103.81363127030255,103.81363127030255,103.81363127030255,103.81363127030255,103.81363127030255,103.6219325474386,103.6219325474386,103.6219325474386,103.6219325474386,103.6219325474386,103.6219325474386,103.82457063077901,103.82457063077901,103.82457063077901,103.82457063077901,103.82457063077901,103.82457063077901,104.42992041019586,104.42992041019586,104.42992041019586,104.42992041019586,104.42992041019586,104.42992041019586,104.51740134873387,104.51740134873387,104.51740134873387,104.51740134873387,104.51740134873387,104.51740134873387,98.726311920539317,98.726311920539317,98.726311920539317,98.726311920539317,98.726311920539317,98.726311920539317,98.95455696992417,98.95455696992417,98.95455696992417,98.95455696992417,98.95455696992417,98.95455696992417,99.511090102610538,99.511090102610538,99.511090102610538,99.511090102610538,99.511090102610538,99.511090102610538,100.51385903697164,100.51385903697164,100.51385903697164,100.51385903697164,100.51385903697164,100.51385903697164,100.06414359125134,100.06414359125134,100.06414359125134,100.06414359125134,100.06414359125134,100.06414359125134,100.83458608466044,100.83458608466044,100.83458608466044,100.83458608466044,100.83458608466044,100.83458608466044,100.19116097905194,100.19116097905194,100.19116097905194,100.19116097905194,100.19116097905194,100.19116097905194,99.865546708332758,99.865546708332758,99.865546708332758,99.865546708332758,99.865546708332758,99.865546708332758,98.02949974473222,98.02949974473222,98.02949974473222,98.02949974473222,98.02949974473222,98.02949974473222,100.15247854629372,100.15247854629372,100.15247854629372,100.15247854629372,100.15247854629372,100.15247854629372,99.478191527351228,99.478191527351228,99.478191527351228,99.478191527351228,99.478191527351228,99.478191527351228,99.53429737636543,99.53429737636543,99.53429737636543,99.53429737636543,99.53429737636543,99.53429737636543,98.793293074641312,98.793293074641312,98.793293074641312,98.793293074641312,98.793293074641312,98.793293074641312,99.711025160045722,99.711025160045722,99.711025160045722,99.711025160045722,99.711025160045722,99.711025160045722,100.5445275959101,100.5445275959101,100.5445275959101,100.5445275959101,100.5445275959101,100.5445275959101,100.34280180642683,100.34280180642683,100.34280180642683,100.34280180642683,100.34280180642683,100.34280180642683,101.14753472624987,101.14753472624987,101.14753472624987,101.14753472624987,101.14753472624987,101.14753472624987,99.578280336182232,99.578280336182232,99.578280336182232,99.578280336182232,99.578280336182232,99.578280336182232,99.047730045254099,99.047730045254099,99.047730045254099,99.047730045254099,99.047730045254099,99.047730045254099,99.891547512508552,99.891547512508552,99.891547512508552,99.891547512508552,99.891547512508552,99.891547512508552,100.10314950394655,100.10314950394655,100.10314950394655,100.10314950394655,100.10314950394655,100.10314950394655,100.21173868339022,100.21173868339022,100.21173868339022,100.21173868339022,100.21173868339022,100.21173868339022,99.953134610074017,99.953134610074017,99.953134610074017,99.953134610074017,99.953134610074017,99.953134610074017,99.618819445993097,99.618819445993097,99.618819445993097,99.618819445993097,99.618819445993097,99.618819445993097,99.633681582997326,99.633681582997326,99.633681582997326,99.633681582997326,99.633681582997326,99.633681582997326,99.787584295148818,99.787584295148818,99.787584295148818,99.787584295148818,99.787584295148818,99.787584295148818,99.020357410482532,99.020357410482532,99.020357410482532,99.020357410482532,99.020357410482532,99.020357410482532,98.418333815614915,98.418333815614915,98.418333815614915,98.418333815614915,98.418333815614915,98.418333815614915,98.346339414005271,98.346339414005271,98.346339414005271,98.346339414005271,98.346339414005271,98.346339414005271,99.091623329689639,99.091623329689639,99.091623329689639,99.091623329689639,99.091623329689639,99.091623329689639,98.69611038772419,98.69611038772419,98.69611038772419,98.69611038772419,98.69611038772419,98.69611038772419,99.061484507694573,99.061484507694573,99.061484507694573,99.061484507694573,99.061484507694573,99.061484507694573,100.54561631140365,100.54561631140365,100.54561631140365,100.54561631140365,100.54561631140365,100.54561631140365,99.926930333294507,99.926930333294507,99.926930333294507,99.926930333294507,99.926930333294507,99.926930333294507,99.594519472512076,99.594519472512076,99.594519472512076,99.594519472512076,99.594519472512076,99.594519472512076,100.06954070275103,100.06954070275103,100.06954070275103,100.06954070275103,100.06954070275103,100.06954070275103,101.34979080945477,101.34979080945477,101.34979080945477,101.34979080945477,101.34979080945477,101.34979080945477,101.22850408114085,101.22850408114085,101.22850408114085,101.22850408114085,101.22850408114085,101.22850408114085,101.71890058390012,101.71890058390012,101.71890058390012,101.71890058390012,101.71890058390012,101.71890058390012],\"y\":[13.771842642937594,13.771842642937594,13.771842642937594,13.771842642937594,13.771842642937594,13.771842642937594,13.596531641263732,13.596531641263732,13.596531641263732,13.596531641263732,13.596531641263732,13.596531641263732,13.924141651583613,13.924141651583613,13.924141651583613,13.924141651583613,13.924141651583613,13.924141651583613,14.065156444017401,14.065156444017401,14.065156444017401,14.065156444017401,14.065156444017401,14.065156444017401,14.345321207193846,14.345321207193846,14.345321207193846,14.345321207193846,14.345321207193846,14.345321207193846,14.623523184634754,14.623523184634754,14.623523184634754,14.623523184634754,14.623523184634754,14.623523184634754,15.107539548515751,15.107539548515751,15.107539548515751,15.107539548515751,15.107539548515751,15.107539548515751,14.912490065733344,14.912490065733344,14.912490065733344,14.912490065733344,14.912490065733344,14.912490065733344,15.133889617364774,15.133889617364774,15.133889617364774,15.133889617364774,15.133889617364774,15.133889617364774,14.626539800996554,14.626539800996554,14.626539800996554,14.626539800996554,14.626539800996554,14.626539800996554,13.191384933855957,13.191384933855957,13.191384933855957,13.191384933855957,13.191384933855957,13.191384933855957,12.854335509941485,12.854335509941485,12.854335509941485,12.854335509941485,12.854335509941485,12.854335509941485,12.880990449397574,12.880990449397574,12.880990449397574,12.880990449397574,12.880990449397574,12.880990449397574,12.315809477354154,12.315809477354154,12.315809477354154,12.315809477354154,12.315809477354154,12.315809477354154,13.606554292405297,13.606554292405297,13.606554292405297,13.606554292405297,13.606554292405297,13.606554292405297,14.04805232636498,14.04805232636498,14.04805232636498,14.04805232636498,14.04805232636498,14.04805232636498,14.217073842445865,14.217073842445865,14.217073842445865,14.217073842445865,14.217073842445865,14.217073842445865,13.787181209128988,13.787181209128988,13.787181209128988,13.787181209128988,13.787181209128988,13.787181209128988,14.957015165346613,14.957015165346613,14.957015165346613,14.957015165346613,14.957015165346613,14.957015165346613,14.819436338853901,14.819436338853901,14.819436338853901,14.819436338853901,14.819436338853901,14.819436338853901,14.885448090327689,14.885448090327689,14.885448090327689,14.885448090327689,14.885448090327689,14.885448090327689,14.856271065160547,14.856271065160547,14.856271065160547,14.856271065160547,14.856271065160547,14.856271065160547,15.182769400387267,15.182769400387267,15.182769400387267,15.182769400387267,15.182769400387267,15.182769400387267,15.895705710022401,15.895705710022401,15.895705710022401,15.895705710022401,15.895705710022401,15.895705710022401,16.031734828746259,16.031734828746259,16.031734828746259,16.031734828746259,16.031734828746259,16.031734828746259,15.892525697933207,15.892525697933207,15.892525697933207,15.892525697933207,15.892525697933207,15.892525697933207,18.148809022252419,18.148809022252419,18.148809022252419,18.148809022252419,18.148809022252419,18.148809022252419,17.18149934201405,17.18149934201405,17.18149934201405,17.18149934201405,17.18149934201405,17.18149934201405,16.408266039267097,16.408266039267097,16.408266039267097,16.408266039267097,16.408266039267097,16.408266039267097,17.424398898916309,17.424398898916309,17.424398898916309,17.424398898916309,17.424398898916309,17.424398898916309,17.408751108842939,17.408751108842939,17.408751108842939,17.408751108842939,17.408751108842939,17.408751108842939,17.940798929048551,17.940798929048551,17.940798929048551,17.940798929048551,17.940798929048551,17.940798929048551,15.999373307434064,15.999373307434064,15.999373307434064,15.999373307434064,15.999373307434064,15.999373307434064,15.919542964523277,15.919542964523277,15.919542964523277,15.919542964523277,15.919542964523277,15.919542964523277,16.628017874948977,16.628017874948977,16.628017874948977,16.628017874948977,16.628017874948977,16.628017874948977,17.389511189745487,17.389511189745487,17.389511189745487,17.389511189745487,17.389511189745487,17.389511189745487,17.384408021449254,17.384408021449254,17.384408021449254,17.384408021449254,17.384408021449254,17.384408021449254,16.56267101869096,16.56267101869096,16.56267101869096,16.56267101869096,16.56267101869096,16.56267101869096,18.790680416560441,18.790680416560441,18.790680416560441,18.790680416560441,18.790680416560441,18.790680416560441,18.118525488555264,18.118525488555264,18.118525488555264,18.118525488555264,18.118525488555264,18.118525488555264,18.325439611008616,18.325439611008616,18.325439611008616,18.325439611008616,18.325439611008616,18.325439611008616,17.745060563166142,17.745060563166142,17.745060563166142,17.745060563166142,17.745060563166142,17.745060563166142,18.199291463885181,18.199291463885181,18.199291463885181,18.199291463885181,18.199291463885181,18.199291463885181,18.849092995099021,18.849092995099021,18.849092995099021,18.849092995099021,18.849092995099021,18.849092995099021,19.2344602879459,19.2344602879459,19.2344602879459,19.2344602879459,19.2344602879459,19.2344602879459,19.847325205810534,19.847325205810534,19.847325205810534,19.847325205810534,19.847325205810534,19.847325205810534,18.809394945200079,18.809394945200079,18.809394945200079,18.809394945200079,18.809394945200079,18.809394945200079,15.682828824885807,15.682828824885807,15.682828824885807,15.682828824885807,15.682828824885807,15.682828824885807,15.350157942527098,15.350157942527098,15.350157942527098,15.350157942527098,15.350157942527098,15.350157942527098,16.330197698292761,16.330197698292761,16.330197698292761,16.330197698292761,16.330197698292761,16.330197698292761,16.714634920377183,16.714634920377183,16.714634920377183,16.714634920377183,16.714634920377183,16.714634920377183,17.262393722843864,17.262393722843864,17.262393722843864,17.262393722843864,17.262393722843864,17.262393722843864,16.980816658086351,16.980816658086351,16.980816658086351,16.980816658086351,16.980816658086351,16.980816658086351,16.259692040912682,16.259692040912682,16.259692040912682,16.259692040912682,16.259692040912682,16.259692040912682,16.27647204771667,16.27647204771667,16.27647204771667,16.27647204771667,16.27647204771667,16.27647204771667,13.535158595761066,13.535158595761066,13.535158595761066,13.535158595761066,13.535158595761066,13.535158595761066,14.584683473561048,14.584683473561048,14.584683473561048,14.584683473561048,14.584683473561048,14.584683473561048,14.612955871594377,14.612955871594377,14.612955871594377,14.612955871594377,14.612955871594377,14.612955871594377,13.924967905649092,13.924967905649092,13.924967905649092,13.924967905649092,13.924967905649092,13.924967905649092,13.570335912276358,13.570335912276358,13.570335912276358,13.570335912276358,13.570335912276358,13.570335912276358,13.396092165252947,13.396092165252947,13.396092165252947,13.396092165252947,13.396092165252947,13.396092165252947,12.947047394068173,12.947047394068173,12.947047394068173,12.947047394068173,12.947047394068173,12.947047394068173,11.943489380788098,11.943489380788098,11.943489380788098,11.943489380788098,11.943489380788098,11.943489380788098,8.379241221657125,8.379241221657125,8.379241221657125,8.379241221657125,8.379241221657125,8.379241221657125,8.1490133898866386,8.1490133898866386,8.1490133898866386,8.1490133898866386,8.1490133898866386,8.1490133898866386,8.67281627587146,8.67281627587146,8.67281627587146,8.67281627587146,8.67281627587146,8.67281627587146,7.9652043194017539,7.9652043194017539,7.9652043194017539,7.9652043194017539,7.9652043194017539,7.9652043194017539,9.053020221653334,9.053020221653334,9.053020221653334,9.053020221653334,9.053020221653334,9.053020221653334,9.9672001865435913,9.9672001865435913,9.9672001865435913,9.9672001865435913,9.9672001865435913,9.9672001865435913,10.343792312341224,10.343792312341224,10.343792312341224,10.343792312341224,10.343792312341224,10.343792312341224,6.9341853094096253,6.9341853094096253,6.9341853094096253,6.9341853094096253,6.9341853094096253,6.9341853094096253,6.8453889269477823,6.8453889269477823,6.8453889269477823,6.8453889269477823,6.8453889269477823,6.8453889269477823,7.5445392609998292,7.5445392609998292,7.5445392609998292,7.5445392609998292,7.5445392609998292,7.5445392609998292,7.5157929411677022,7.5157929411677022,7.5157929411677022,7.5157929411677022,7.5157929411677022,7.5157929411677022,6.7305448500274503,6.7305448500274503,6.7305448500274503,6.7305448500274503,6.7305448500274503,6.7305448500274503,6.1907451639298765,6.1907451639298765,6.1907451639298765,6.1907451639298765,6.1907451639298765,6.1907451639298765,6.1774973714727786,6.1774973714727786,6.1774973714727786,6.1774973714727786,6.1774973714727786,6.1774973714727786],\"z\":[2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022],\"size\":[60067,70215,62291,44169,37318,12420,12452,17656,23295,14615,14002,7366,7348,9583,11347,7064,10290,3912,7616,11005,14643,8744,8927,5571,6221,8555,10631,8549,8013,4890,1614,2717,2781,2636,3513,2907,5872,9547,10043,8132,9254,4647,1574,2117,2586,2209,2872,1744,1536,2195,3215,3119,3128,2117,4288,5766,6391,5632,6744,3585,17286,24021,25727,23940,21736,8643,13563,14821,14648,15390,15427,7487,4021,5430,5862,5877,6635,3648,1482,2108,2570,2900,2991,1445,9318,8685,9086,9203,12344,4878,6395,7059,6191,6241,6875,3255,4384,4870,4740,4130,6909,3183,5304,5492,5723,5101,6848,3240,10147,17586,24283,11802,21949,11943,5061,8774,12393,6897,15960,8267,4658,9100,11345,4830,9592,5265,8150,10809,14779,9465,22484,11723,14761,19419,24878,15635,28121,11271,4755,5897,7874,6054,12144,5867,6435,11334,14796,8333,15131,8468,5076,5651,7339,3949,8961,4459,4312,4326,4746,6030,9095,6778,1181,1769,1691,2298,5112,3128,10698,14138,14274,15488,25903,13404,5957,6497,7422,10517,22449,15185,4211,5097,5024,5342,9555,8845,5434,6317,6581,6386,11698,6371,3987,5500,5681,6497,9985,6907,4850,6198,7270,9212,14778,10869,5461,6535,6339,8923,15388,12954,3901,4262,4991,6834,11171,10008,4539,3637,3662,5068,8478,7955,4029,5558,5529,7431,9744,4462,15620,18944,21722,22574,28778,14174,3735,5339,6179,6103,9087,6184,5441,7330,8296,8700,11604,8863,2210,3990,4555,4266,7337,4627,4737,5265,5642,6485,9874,5702,2960,3962,5577,5970,9520,5695,3339,4342,5082,5881,8888,5262,8820,10623,12419,14453,19353,9684,864,950,1029,1188,2275,1739,4246,5176,5045,5682,6396,4165,1251,1964,3245,2164,2057,1673,3052,5243,7420,5228,5090,3211,3117,5368,5681,4206,3406,1752,1876,3059,4330,4432,4164,1942,2858,5390,6996,6827,5656,2908,2033,4560,3994,3811,4090,2011,4450,7375,6471,6035,9832,5315,9082,12885,12937,8597,5270,7385,7420,9665,8802,6482,5385,5767,5967,7495,7249,6179,5726,5274,7870,9936,9071,7472,5366,6211,3857,4406,4387,3889,1471,1264,1598,1796,1942,1363,846,1350,3714,4962,5196,5046,4451,3560,4284,5317,4935,4983,4850,3575,21330,24032,27228,29929,40983,13459,7756,8474,8913,9880,10442,3004,4261,5043,5443,6355,7419,2576,13731,14459,14862,14062,15375,2832,22044,22651,23185,24199,28566,9709,3571,4633,4845,5226,6077,2141,8245,9156,9643,10320,11811,5852,21034,23446,24647,23056,28509,17209,6561,7370,8109,7240,8021,3625,7610,7515,8464,7625,9176,3865,5390,5599,5085,5087,7408,4291,7566,8727,9040,9332,11163,6266,7406,7822,6897,7003,7337,3346,7560,13242,10381,8762,9119,4548],\"color\":[60067,70215,62291,44169,37318,12420,12452,17656,23295,14615,14002,7366,7348,9583,11347,7064,10290,3912,7616,11005,14643,8744,8927,5571,6221,8555,10631,8549,8013,4890,1614,2717,2781,2636,3513,2907,5872,9547,10043,8132,9254,4647,1574,2117,2586,2209,2872,1744,1536,2195,3215,3119,3128,2117,4288,5766,6391,5632,6744,3585,17286,24021,25727,23940,21736,8643,13563,14821,14648,15390,15427,7487,4021,5430,5862,5877,6635,3648,1482,2108,2570,2900,2991,1445,9318,8685,9086,9203,12344,4878,6395,7059,6191,6241,6875,3255,4384,4870,4740,4130,6909,3183,5304,5492,5723,5101,6848,3240,10147,17586,24283,11802,21949,11943,5061,8774,12393,6897,15960,8267,4658,9100,11345,4830,9592,5265,8150,10809,14779,9465,22484,11723,14761,19419,24878,15635,28121,11271,4755,5897,7874,6054,12144,5867,6435,11334,14796,8333,15131,8468,5076,5651,7339,3949,8961,4459,4312,4326,4746,6030,9095,6778,1181,1769,1691,2298,5112,3128,10698,14138,14274,15488,25903,13404,5957,6497,7422,10517,22449,15185,4211,5097,5024,5342,9555,8845,5434,6317,6581,6386,11698,6371,3987,5500,5681,6497,9985,6907,4850,6198,7270,9212,14778,10869,5461,6535,6339,8923,15388,12954,3901,4262,4991,6834,11171,10008,4539,3637,3662,5068,8478,7955,4029,5558,5529,7431,9744,4462,15620,18944,21722,22574,28778,14174,3735,5339,6179,6103,9087,6184,5441,7330,8296,8700,11604,8863,2210,3990,4555,4266,7337,4627,4737,5265,5642,6485,9874,5702,2960,3962,5577,5970,9520,5695,3339,4342,5082,5881,8888,5262,8820,10623,12419,14453,19353,9684,864,950,1029,1188,2275,1739,4246,5176,5045,5682,6396,4165,1251,1964,3245,2164,2057,1673,3052,5243,7420,5228,5090,3211,3117,5368,5681,4206,3406,1752,1876,3059,4330,4432,4164,1942,2858,5390,6996,6827,5656,2908,2033,4560,3994,3811,4090,2011,4450,7375,6471,6035,9832,5315,9082,12885,12937,8597,5270,7385,7420,9665,8802,6482,5385,5767,5967,7495,7249,6179,5726,5274,7870,9936,9071,7472,5366,6211,3857,4406,4387,3889,1471,1264,1598,1796,1942,1363,846,1350,3714,4962,5196,5046,4451,3560,4284,5317,4935,4983,4850,3575,21330,24032,27228,29929,40983,13459,7756,8474,8913,9880,10442,3004,4261,5043,5443,6355,7419,2576,13731,14459,14862,14062,15375,2832,22044,22651,23185,24199,28566,9709,3571,4633,4845,5226,6077,2141,8245,9156,9643,10320,11811,5852,21034,23446,24647,23056,28509,17209,6561,7370,8109,7240,8021,3625,7610,7515,8464,7625,9176,3865,5390,5599,5085,5087,7408,4291,7566,8727,9040,9332,11163,6266,7406,7822,6897,7003,7337,3346,7560,13242,10381,8762,9119,4548],\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"symbol\":\"circle\",\"sizemode\":\"diameter\"},\"hoverinfo\":\"text\",\"text\":{},\"inherit\":true}},\"layout\":{\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"scene\":{\"xaxis\":{\"title\":\"Longitude\"},\"yaxis\":{\"title\":\"Latitude\"},\"zaxis\":{\"title\":\"Year\"}},\"title\":\"Space-Time Cube of Drug Abuse Cases in Thailand (2017-2022)\",\"hovermode\":\"closest\",\"showlegend\":false,\"legend\":{\"yanchor\":\"top\",\"y\":0.5}},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"data\":[{\"x\":[100.62346136424746,100.62346136424746,100.62346136424746,100.62346136424746,100.62346136424746,100.62346136424746,100.71023157204732,100.71023157204732,100.71023157204732,100.71023157204732,100.71023157204732,100.71023157204732,100.39284437729408,100.39284437729408,100.39284437729408,100.39284437729408,100.39284437729408,100.39284437729408,100.68237573701045,100.68237573701045,100.68237573701045,100.68237573701045,100.68237573701045,100.68237573701045,100.52658206775011,100.52658206775011,100.52658206775011,100.52658206775011,100.52658206775011,100.52658206775011,100.34852189532658,100.34852189532658,100.34852189532658,100.34852189532658,100.34852189532658,100.34852189532658,100.90693523816465,100.90693523816465,100.90693523816465,100.90693523816465,100.90693523816465,100.90693523816465,100.34721554976805,100.34721554976805,100.34721554976805,100.34721554976805,100.34721554976805,100.34721554976805,100.02746225500066,100.02746225500066,100.02746225500066,100.02746225500066,100.02746225500066,100.02746225500066,101.01687337340066,101.01687337340066,101.01687337340066,101.01687337340066,101.01687337340066,101.01687337340066,101.20152594716131,101.20152594716131,101.20152594716131,101.20152594716131,101.20152594716131,101.20152594716131,101.4274815704137,101.4274815704137,101.4274815704137,101.4274815704137,101.4274815704137,101.4274815704137,102.13018937580715,102.13018937580715,102.13018937580715,102.13018937580715,102.13018937580715,102.13018937580715,102.52166692213197,102.52166692213197,102.52166692213197,102.52166692213197,102.52166692213197,102.52166692213197,101.42566537600294,101.42566537600294,101.42566537600294,101.42566537600294,101.42566537600294,101.42566537600294,101.65029268511354,101.65029268511354,101.65029268511354,101.65029268511354,101.65029268511354,101.65029268511354,101.17132031170088,101.17132031170088,101.17132031170088,101.17132031170088,101.17132031170088,101.17132031170088,102.32254595676091,102.32254595676091,102.32254595676091,102.32254595676091,102.32254595676091,102.32254595676091,102.10918946975428,102.10918946975428,102.10918946975428,102.10918946975428,102.10918946975428,102.10918946975428,102.95638684337747,102.95638684337747,102.95638684337747,102.95638684337747,102.95638684337747,102.95638684337747,103.65589320101067,103.65589320101067,103.65589320101067,103.65589320101067,103.65589320101067,103.65589320101067,104.36937796146215,104.36937796146215,104.36937796146215,104.36937796146215,104.36937796146215,104.36937796146215,105.11159291657839,105.11159291657839,105.11159291657839,105.11159291657839,105.11159291657839,105.11159291657839,104.33828904209687,104.33828904209687,104.33828904209687,104.33828904209687,104.33828904209687,104.33828904209687,101.81923565920435,101.81923565920435,101.81923565920435,101.81923565920435,101.81923565920435,101.81923565920435,104.74125515291696,104.74125515291696,104.74125515291696,104.74125515291696,104.74125515291696,104.74125515291696,103.71112124377785,103.71112124377785,103.71112124377785,103.71112124377785,103.71112124377785,103.71112124377785,102.30251002772171,102.30251002772171,102.30251002772171,102.30251002772171,102.30251002772171,102.30251002772171,102.57837215749053,102.57837215749053,102.57837215749053,102.57837215749053,102.57837215749053,102.57837215749053,102.86324901561068,102.86324901561068,102.86324901561068,102.86324901561068,102.86324901561068,102.86324901561068,101.63584153310288,101.63584153310288,101.63584153310288,101.63584153310288,101.63584153310288,101.63584153310288,102.83371850222453,102.83371850222453,102.83371850222453,102.83371850222453,102.83371850222453,102.83371850222453,103.16573568947332,103.16573568947332,103.16573568947332,103.16573568947332,103.16573568947332,103.16573568947332,103.81363127030255,103.81363127030255,103.81363127030255,103.81363127030255,103.81363127030255,103.81363127030255,103.6219325474386,103.6219325474386,103.6219325474386,103.6219325474386,103.6219325474386,103.6219325474386,103.82457063077901,103.82457063077901,103.82457063077901,103.82457063077901,103.82457063077901,103.82457063077901,104.42992041019586,104.42992041019586,104.42992041019586,104.42992041019586,104.42992041019586,104.42992041019586,104.51740134873387,104.51740134873387,104.51740134873387,104.51740134873387,104.51740134873387,104.51740134873387,98.726311920539317,98.726311920539317,98.726311920539317,98.726311920539317,98.726311920539317,98.726311920539317,98.95455696992417,98.95455696992417,98.95455696992417,98.95455696992417,98.95455696992417,98.95455696992417,99.511090102610538,99.511090102610538,99.511090102610538,99.511090102610538,99.511090102610538,99.511090102610538,100.51385903697164,100.51385903697164,100.51385903697164,100.51385903697164,100.51385903697164,100.51385903697164,100.06414359125134,100.06414359125134,100.06414359125134,100.06414359125134,100.06414359125134,100.06414359125134,100.83458608466044,100.83458608466044,100.83458608466044,100.83458608466044,100.83458608466044,100.83458608466044,100.19116097905194,100.19116097905194,100.19116097905194,100.19116097905194,100.19116097905194,100.19116097905194,99.865546708332758,99.865546708332758,99.865546708332758,99.865546708332758,99.865546708332758,99.865546708332758,98.02949974473222,98.02949974473222,98.02949974473222,98.02949974473222,98.02949974473222,98.02949974473222,100.15247854629372,100.15247854629372,100.15247854629372,100.15247854629372,100.15247854629372,100.15247854629372,99.478191527351228,99.478191527351228,99.478191527351228,99.478191527351228,99.478191527351228,99.478191527351228,99.53429737636543,99.53429737636543,99.53429737636543,99.53429737636543,99.53429737636543,99.53429737636543,98.793293074641312,98.793293074641312,98.793293074641312,98.793293074641312,98.793293074641312,98.793293074641312,99.711025160045722,99.711025160045722,99.711025160045722,99.711025160045722,99.711025160045722,99.711025160045722,100.5445275959101,100.5445275959101,100.5445275959101,100.5445275959101,100.5445275959101,100.5445275959101,100.34280180642683,100.34280180642683,100.34280180642683,100.34280180642683,100.34280180642683,100.34280180642683,101.14753472624987,101.14753472624987,101.14753472624987,101.14753472624987,101.14753472624987,101.14753472624987,99.578280336182232,99.578280336182232,99.578280336182232,99.578280336182232,99.578280336182232,99.578280336182232,99.047730045254099,99.047730045254099,99.047730045254099,99.047730045254099,99.047730045254099,99.047730045254099,99.891547512508552,99.891547512508552,99.891547512508552,99.891547512508552,99.891547512508552,99.891547512508552,100.10314950394655,100.10314950394655,100.10314950394655,100.10314950394655,100.10314950394655,100.10314950394655,100.21173868339022,100.21173868339022,100.21173868339022,100.21173868339022,100.21173868339022,100.21173868339022,99.953134610074017,99.953134610074017,99.953134610074017,99.953134610074017,99.953134610074017,99.953134610074017,99.618819445993097,99.618819445993097,99.618819445993097,99.618819445993097,99.618819445993097,99.618819445993097,99.633681582997326,99.633681582997326,99.633681582997326,99.633681582997326,99.633681582997326,99.633681582997326,99.787584295148818,99.787584295148818,99.787584295148818,99.787584295148818,99.787584295148818,99.787584295148818,99.020357410482532,99.020357410482532,99.020357410482532,99.020357410482532,99.020357410482532,99.020357410482532,98.418333815614915,98.418333815614915,98.418333815614915,98.418333815614915,98.418333815614915,98.418333815614915,98.346339414005271,98.346339414005271,98.346339414005271,98.346339414005271,98.346339414005271,98.346339414005271,99.091623329689639,99.091623329689639,99.091623329689639,99.091623329689639,99.091623329689639,99.091623329689639,98.69611038772419,98.69611038772419,98.69611038772419,98.69611038772419,98.69611038772419,98.69611038772419,99.061484507694573,99.061484507694573,99.061484507694573,99.061484507694573,99.061484507694573,99.061484507694573,100.54561631140365,100.54561631140365,100.54561631140365,100.54561631140365,100.54561631140365,100.54561631140365,99.926930333294507,99.926930333294507,99.926930333294507,99.926930333294507,99.926930333294507,99.926930333294507,99.594519472512076,99.594519472512076,99.594519472512076,99.594519472512076,99.594519472512076,99.594519472512076,100.06954070275103,100.06954070275103,100.06954070275103,100.06954070275103,100.06954070275103,100.06954070275103,101.34979080945477,101.34979080945477,101.34979080945477,101.34979080945477,101.34979080945477,101.34979080945477,101.22850408114085,101.22850408114085,101.22850408114085,101.22850408114085,101.22850408114085,101.22850408114085,101.71890058390012,101.71890058390012,101.71890058390012,101.71890058390012,101.71890058390012,101.71890058390012],\"y\":[13.771842642937594,13.771842642937594,13.771842642937594,13.771842642937594,13.771842642937594,13.771842642937594,13.596531641263732,13.596531641263732,13.596531641263732,13.596531641263732,13.596531641263732,13.596531641263732,13.924141651583613,13.924141651583613,13.924141651583613,13.924141651583613,13.924141651583613,13.924141651583613,14.065156444017401,14.065156444017401,14.065156444017401,14.065156444017401,14.065156444017401,14.065156444017401,14.345321207193846,14.345321207193846,14.345321207193846,14.345321207193846,14.345321207193846,14.345321207193846,14.623523184634754,14.623523184634754,14.623523184634754,14.623523184634754,14.623523184634754,14.623523184634754,15.107539548515751,15.107539548515751,15.107539548515751,15.107539548515751,15.107539548515751,15.107539548515751,14.912490065733344,14.912490065733344,14.912490065733344,14.912490065733344,14.912490065733344,14.912490065733344,15.133889617364774,15.133889617364774,15.133889617364774,15.133889617364774,15.133889617364774,15.133889617364774,14.626539800996554,14.626539800996554,14.626539800996554,14.626539800996554,14.626539800996554,14.626539800996554,13.191384933855957,13.191384933855957,13.191384933855957,13.191384933855957,13.191384933855957,13.191384933855957,12.854335509941485,12.854335509941485,12.854335509941485,12.854335509941485,12.854335509941485,12.854335509941485,12.880990449397574,12.880990449397574,12.880990449397574,12.880990449397574,12.880990449397574,12.880990449397574,12.315809477354154,12.315809477354154,12.315809477354154,12.315809477354154,12.315809477354154,12.315809477354154,13.606554292405297,13.606554292405297,13.606554292405297,13.606554292405297,13.606554292405297,13.606554292405297,14.04805232636498,14.04805232636498,14.04805232636498,14.04805232636498,14.04805232636498,14.04805232636498,14.217073842445865,14.217073842445865,14.217073842445865,14.217073842445865,14.217073842445865,14.217073842445865,13.787181209128988,13.787181209128988,13.787181209128988,13.787181209128988,13.787181209128988,13.787181209128988,14.957015165346613,14.957015165346613,14.957015165346613,14.957015165346613,14.957015165346613,14.957015165346613,14.819436338853901,14.819436338853901,14.819436338853901,14.819436338853901,14.819436338853901,14.819436338853901,14.885448090327689,14.885448090327689,14.885448090327689,14.885448090327689,14.885448090327689,14.885448090327689,14.856271065160547,14.856271065160547,14.856271065160547,14.856271065160547,14.856271065160547,14.856271065160547,15.182769400387267,15.182769400387267,15.182769400387267,15.182769400387267,15.182769400387267,15.182769400387267,15.895705710022401,15.895705710022401,15.895705710022401,15.895705710022401,15.895705710022401,15.895705710022401,16.031734828746259,16.031734828746259,16.031734828746259,16.031734828746259,16.031734828746259,16.031734828746259,15.892525697933207,15.892525697933207,15.892525697933207,15.892525697933207,15.892525697933207,15.892525697933207,18.148809022252419,18.148809022252419,18.148809022252419,18.148809022252419,18.148809022252419,18.148809022252419,17.18149934201405,17.18149934201405,17.18149934201405,17.18149934201405,17.18149934201405,17.18149934201405,16.408266039267097,16.408266039267097,16.408266039267097,16.408266039267097,16.408266039267097,16.408266039267097,17.424398898916309,17.424398898916309,17.424398898916309,17.424398898916309,17.424398898916309,17.424398898916309,17.408751108842939,17.408751108842939,17.408751108842939,17.408751108842939,17.408751108842939,17.408751108842939,17.940798929048551,17.940798929048551,17.940798929048551,17.940798929048551,17.940798929048551,17.940798929048551,15.999373307434064,15.999373307434064,15.999373307434064,15.999373307434064,15.999373307434064,15.999373307434064,15.919542964523277,15.919542964523277,15.919542964523277,15.919542964523277,15.919542964523277,15.919542964523277,16.628017874948977,16.628017874948977,16.628017874948977,16.628017874948977,16.628017874948977,16.628017874948977,17.389511189745487,17.389511189745487,17.389511189745487,17.389511189745487,17.389511189745487,17.389511189745487,17.384408021449254,17.384408021449254,17.384408021449254,17.384408021449254,17.384408021449254,17.384408021449254,16.56267101869096,16.56267101869096,16.56267101869096,16.56267101869096,16.56267101869096,16.56267101869096,18.790680416560441,18.790680416560441,18.790680416560441,18.790680416560441,18.790680416560441,18.790680416560441,18.118525488555264,18.118525488555264,18.118525488555264,18.118525488555264,18.118525488555264,18.118525488555264,18.325439611008616,18.325439611008616,18.325439611008616,18.325439611008616,18.325439611008616,18.325439611008616,17.745060563166142,17.745060563166142,17.745060563166142,17.745060563166142,17.745060563166142,17.745060563166142,18.199291463885181,18.199291463885181,18.199291463885181,18.199291463885181,18.199291463885181,18.199291463885181,18.849092995099021,18.849092995099021,18.849092995099021,18.849092995099021,18.849092995099021,18.849092995099021,19.2344602879459,19.2344602879459,19.2344602879459,19.2344602879459,19.2344602879459,19.2344602879459,19.847325205810534,19.847325205810534,19.847325205810534,19.847325205810534,19.847325205810534,19.847325205810534,18.809394945200079,18.809394945200079,18.809394945200079,18.809394945200079,18.809394945200079,18.809394945200079,15.682828824885807,15.682828824885807,15.682828824885807,15.682828824885807,15.682828824885807,15.682828824885807,15.350157942527098,15.350157942527098,15.350157942527098,15.350157942527098,15.350157942527098,15.350157942527098,16.330197698292761,16.330197698292761,16.330197698292761,16.330197698292761,16.330197698292761,16.330197698292761,16.714634920377183,16.714634920377183,16.714634920377183,16.714634920377183,16.714634920377183,16.714634920377183,17.262393722843864,17.262393722843864,17.262393722843864,17.262393722843864,17.262393722843864,17.262393722843864,16.980816658086351,16.980816658086351,16.980816658086351,16.980816658086351,16.980816658086351,16.980816658086351,16.259692040912682,16.259692040912682,16.259692040912682,16.259692040912682,16.259692040912682,16.259692040912682,16.27647204771667,16.27647204771667,16.27647204771667,16.27647204771667,16.27647204771667,16.27647204771667,13.535158595761066,13.535158595761066,13.535158595761066,13.535158595761066,13.535158595761066,13.535158595761066,14.584683473561048,14.584683473561048,14.584683473561048,14.584683473561048,14.584683473561048,14.584683473561048,14.612955871594377,14.612955871594377,14.612955871594377,14.612955871594377,14.612955871594377,14.612955871594377,13.924967905649092,13.924967905649092,13.924967905649092,13.924967905649092,13.924967905649092,13.924967905649092,13.570335912276358,13.570335912276358,13.570335912276358,13.570335912276358,13.570335912276358,13.570335912276358,13.396092165252947,13.396092165252947,13.396092165252947,13.396092165252947,13.396092165252947,13.396092165252947,12.947047394068173,12.947047394068173,12.947047394068173,12.947047394068173,12.947047394068173,12.947047394068173,11.943489380788098,11.943489380788098,11.943489380788098,11.943489380788098,11.943489380788098,11.943489380788098,8.379241221657125,8.379241221657125,8.379241221657125,8.379241221657125,8.379241221657125,8.379241221657125,8.1490133898866386,8.1490133898866386,8.1490133898866386,8.1490133898866386,8.1490133898866386,8.1490133898866386,8.67281627587146,8.67281627587146,8.67281627587146,8.67281627587146,8.67281627587146,8.67281627587146,7.9652043194017539,7.9652043194017539,7.9652043194017539,7.9652043194017539,7.9652043194017539,7.9652043194017539,9.053020221653334,9.053020221653334,9.053020221653334,9.053020221653334,9.053020221653334,9.053020221653334,9.9672001865435913,9.9672001865435913,9.9672001865435913,9.9672001865435913,9.9672001865435913,9.9672001865435913,10.343792312341224,10.343792312341224,10.343792312341224,10.343792312341224,10.343792312341224,10.343792312341224,6.9341853094096253,6.9341853094096253,6.9341853094096253,6.9341853094096253,6.9341853094096253,6.9341853094096253,6.8453889269477823,6.8453889269477823,6.8453889269477823,6.8453889269477823,6.8453889269477823,6.8453889269477823,7.5445392609998292,7.5445392609998292,7.5445392609998292,7.5445392609998292,7.5445392609998292,7.5445392609998292,7.5157929411677022,7.5157929411677022,7.5157929411677022,7.5157929411677022,7.5157929411677022,7.5157929411677022,6.7305448500274503,6.7305448500274503,6.7305448500274503,6.7305448500274503,6.7305448500274503,6.7305448500274503,6.1907451639298765,6.1907451639298765,6.1907451639298765,6.1907451639298765,6.1907451639298765,6.1907451639298765,6.1774973714727786,6.1774973714727786,6.1774973714727786,6.1774973714727786,6.1774973714727786,6.1774973714727786],\"z\":[2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022,2017,2018,2019,2020,2021,2022],\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"colorbar\":{\"title\":\"\",\"ticklen\":2},\"cmin\":846,\"cmax\":70215,\"colorscale\":[[\"0\",\"rgba(68,1,84,1)\"],[\"0.0416666666666667\",\"rgba(70,19,97,1)\"],[\"0.0833333333333333\",\"rgba(72,32,111,1)\"],[\"0.125\",\"rgba(71,45,122,1)\"],[\"0.166666666666667\",\"rgba(68,58,128,1)\"],[\"0.208333333333333\",\"rgba(64,70,135,1)\"],[\"0.25\",\"rgba(60,82,138,1)\"],[\"0.291666666666667\",\"rgba(56,93,140,1)\"],[\"0.333333333333333\",\"rgba(49,104,142,1)\"],[\"0.375\",\"rgba(46,114,142,1)\"],[\"0.416666666666667\",\"rgba(42,123,142,1)\"],[\"0.458333333333333\",\"rgba(38,133,141,1)\"],[\"0.5\",\"rgba(37,144,140,1)\"],[\"0.541666666666667\",\"rgba(33,154,138,1)\"],[\"0.583333333333333\",\"rgba(39,164,133,1)\"],[\"0.625\",\"rgba(47,174,127,1)\"],[\"0.666666666666667\",\"rgba(53,183,121,1)\"],[\"0.708333333333333\",\"rgba(79,191,110,1)\"],[\"0.75\",\"rgba(98,199,98,1)\"],[\"0.791666666666667\",\"rgba(119,207,85,1)\"],[\"0.833333333333333\",\"rgba(147,214,70,1)\"],[\"0.875\",\"rgba(172,220,52,1)\"],[\"0.916666666666667\",\"rgba(199,225,42,1)\"],[\"0.958333333333333\",\"rgba(226,228,40,1)\"],[\"1\",\"rgba(253,231,37,1)\"]],\"showscale\":false,\"color\":[60067,70215,62291,44169,37318,12420,12452,17656,23295,14615,14002,7366,7348,9583,11347,7064,10290,3912,7616,11005,14643,8744,8927,5571,6221,8555,10631,8549,8013,4890,1614,2717,2781,2636,3513,2907,5872,9547,10043,8132,9254,4647,1574,2117,2586,2209,2872,1744,1536,2195,3215,3119,3128,2117,4288,5766,6391,5632,6744,3585,17286,24021,25727,23940,21736,8643,13563,14821,14648,15390,15427,7487,4021,5430,5862,5877,6635,3648,1482,2108,2570,2900,2991,1445,9318,8685,9086,9203,12344,4878,6395,7059,6191,6241,6875,3255,4384,4870,4740,4130,6909,3183,5304,5492,5723,5101,6848,3240,10147,17586,24283,11802,21949,11943,5061,8774,12393,6897,15960,8267,4658,9100,11345,4830,9592,5265,8150,10809,14779,9465,22484,11723,14761,19419,24878,15635,28121,11271,4755,5897,7874,6054,12144,5867,6435,11334,14796,8333,15131,8468,5076,5651,7339,3949,8961,4459,4312,4326,4746,6030,9095,6778,1181,1769,1691,2298,5112,3128,10698,14138,14274,15488,25903,13404,5957,6497,7422,10517,22449,15185,4211,5097,5024,5342,9555,8845,5434,6317,6581,6386,11698,6371,3987,5500,5681,6497,9985,6907,4850,6198,7270,9212,14778,10869,5461,6535,6339,8923,15388,12954,3901,4262,4991,6834,11171,10008,4539,3637,3662,5068,8478,7955,4029,5558,5529,7431,9744,4462,15620,18944,21722,22574,28778,14174,3735,5339,6179,6103,9087,6184,5441,7330,8296,8700,11604,8863,2210,3990,4555,4266,7337,4627,4737,5265,5642,6485,9874,5702,2960,3962,5577,5970,9520,5695,3339,4342,5082,5881,8888,5262,8820,10623,12419,14453,19353,9684,864,950,1029,1188,2275,1739,4246,5176,5045,5682,6396,4165,1251,1964,3245,2164,2057,1673,3052,5243,7420,5228,5090,3211,3117,5368,5681,4206,3406,1752,1876,3059,4330,4432,4164,1942,2858,5390,6996,6827,5656,2908,2033,4560,3994,3811,4090,2011,4450,7375,6471,6035,9832,5315,9082,12885,12937,8597,5270,7385,7420,9665,8802,6482,5385,5767,5967,7495,7249,6179,5726,5274,7870,9936,9071,7472,5366,6211,3857,4406,4387,3889,1471,1264,1598,1796,1942,1363,846,1350,3714,4962,5196,5046,4451,3560,4284,5317,4935,4983,4850,3575,21330,24032,27228,29929,40983,13459,7756,8474,8913,9880,10442,3004,4261,5043,5443,6355,7419,2576,13731,14459,14862,14062,15375,2832,22044,22651,23185,24199,28566,9709,3571,4633,4845,5226,6077,2141,8245,9156,9643,10320,11811,5852,21034,23446,24647,23056,28509,17209,6561,7370,8109,7240,8021,3625,7610,7515,8464,7625,9176,3865,5390,5599,5085,5087,7408,4291,7566,8727,9040,9332,11163,6266,7406,7822,6897,7003,7337,3346,7560,13242,10381,8762,9119,4548],\"size\":[86.833888336288538,100,89.719327076936395,66.207672014876962,57.319119491415478,25.016217618821088,25.057734723003072,31.809453790598106,39.125545993166973,27.864031483804006,27.068719456817888,18.459109977079098,18.435756605976735,21.335466851187132,23.62409721921896,18.06729230636163,22.252735371707825,13.977857544436276,18.783462353500845,23.180383168274012,27.900358949963241,20.246940275915755,20.484366215456472,16.130259914370974,16.973576093067507,20.001729879340914,22.695152013147084,19.993945422306794,19.298533927258575,15.24672404099814,10.996410500367599,12.427453185140337,12.510487393504302,12.322363015179691,13.460191151667171,12.673960991220863,16.520780175582754,21.288760108982398,21.932275223803138,19.452925658435326,20.908619123816113,14.931453531116205,10.94451412014012,11.64900748172815,12.257492539895342,11.768369156251351,12.628551658521818,11.165073736106907,10.895212558924015,11.750205423171733,13.073563118972451,12.949011806426501,12.960688491977685,11.64900748172815,14.465683518574579,16.383254767979935,17.194135709034295,16.209401894217876,17.652121264541798,13.553604636076633,31.329412273493922,40.067465294295715,42.280845910997705,39.962375124335082,37.102884573800978,20.11590191584137,26.499156683821305,28.131297841975524,27.906845997491676,28.869523850711413,28.917528002421829,18.616096527267224,14.119275180556155,15.947325174069109,16.507806080525881,16.527267223111188,17.510703628421918,13.635341434934913,10.825152445616919,11.637330796176967,12.236733987804351,12.664879124681054,12.782943389698568,10.7771482939065,20.991653332180078,20.170393115080223,20.690654326860702,20.842451239026076,24.917614496388875,15.231155126929895,17.199325347057041,18.060805258833199,16.9346538078969,16.999524283181248,17.822081909786792,13.12545949919993,14.590234831120529,15.220775850884401,15.052112615145093,14.260692816676038,17.866193832980152,13.032046014790469,15.78385157635255,16.027764563421702,16.327466159235392,15.520477446698091,17.787051853133242,13.105998356614625,22.067205812394587,31.718635125200016,40.407386584785712,24.214418544306533,37.379232798512305,24.3973532846084,15.468581066470612,20.285862561086365,24.981187562167541,17.850624918911905,29.609047268952988,19.628075941703067,14.945725035678763,20.70881805994032,23.621502400207586,15.168879470656922,21.347143536738315,15.733252605630756,19.47627902953769,22.926090905159366,28.07680664273667,21.182372529516066,38.073346884054843,24.111923193357264,28.053453271634304,34.096786749124249,41.179345240669463,29.187389179604722,45.386844267612332,23.525494096786748,15.071573757730398,16.553215413224926,19.118194005968085,16.756908705617782,24.65813259525148,16.514293128054319,17.251221727284523,23.607230895645031,28.098862604333348,19.713704969078407,28.533494788738487,19.888855252346147,15.488042209055919,16.234052674825932,18.424079920425548,14.025861696146695,20.528478138649831,14.687540544047053,14.496821346711066,14.514985079790684,15.059897072179215,16.725770877481295,20.702331012411882,17.696233187735157,10.434632184405137,11.19750897374908,11.096311032305497,11.883838602257493,15.534748951260649,12.960688491977685,22.782078450028109,27.245167149591317,27.421614842364747,28.996669982268738,42.509189983998617,26.292868572417074,16.631059983566146,17.331661116637115,18.53176490939757,22.547247329498767,38.027937551355791,28.603554902045584,14.365782986636681,15.515287808675344,15.420576914760197,15.833153137568655,21.299139385027893,20.377978635990139,15.952514812091856,17.098127405613457,17.440643515114822,17.187648661505861,24.079487955715088,17.168187518920554,14.075163257362799,16.038143839467196,16.272974959996539,17.331661116637115,21.857025472473296,17.863599013968773,15.194827660770661,16.943735674436709,18.334558664533148,20.854127924577263,28.075509233230985,23.003935475500583,15.987544868745404,17.380962677853219,17.126670414738573,20.479176577433723,28.866929031700039,25.709034294857936,13.963586039873718,14.431950871426718,15.377762401072525,17.768888120053624,23.395753146218052,21.886865891104094,14.791333304502011,13.621069930372357,13.653505168014531,15.477662933010423,19.901829347403016,19.223284175928729,14.129654456601653,16.113393590797042,16.075768715132121,18.543441594948753,21.544349781602733,14.691432772564113,29.167928037019418,33.480517233922932,37.08472084072136,38.190113739566669,46.239242312848681,27.291873891796048,13.74821606192968,15.829260909051595,16.919084893828657,16.820481771396445,20.691951736366388,16.925571941357092,15.961596678631665,18.412403234874368,19.665700817367988,20.18985425766553,23.957531462180512,20.401332007092506,11.769666565757039,14.079055485879859,14.812091856593003,14.437140509449467,18.421485101414177,14.905505341002465,15.048220386628032,15.733252605630756,16.222375989274749,17.316092202568871,21.713013017342039,16.300220559615965,12.742723695022272,14.042728019720624,16.138044371405094,16.647926307140075,21.253730052328848,16.291138693076157,13.234441897677637,14.535743631881676,15.495826666090039,16.532456861133937,20.433767244734682,15.729360377113697,20.345543398347964,22.684772737101589,25.014920209315399,27.653851143882715,34.011157721748909,21.466505211261513,10.023353371102365,10.134930588591446,10.237425939540717,10.443714050944946,11.853998183626691,11.158586688578472,14.411192319335726,15.617783159624615,15.447822514379622,16.274272369502228,17.20062275656273,14.306102149375082,10.525450849803226,11.450503827358041,13.112485404143062,11.709985728495438,11.571162911386931,11.07295766120313,12.862085369545474,15.704709596505644,18.529170090386195,15.685248453920339,15.506205942135537,13.068373480949704,12.946416987415128,15.866885784716516,16.272974959996539,14.359295939108247,13.321368334558665,11.175453012152403,11.336331790857587,12.871167236085283,14.520174717813433,14.652510487393505,14.304804739869393,11.421960818232929,12.6103879254422,15.895428793841631,17.979068459974918,17.759806253513815,16.240539722354367,12.675258400726548,11.540025083250443,14.818578904121438,14.084245123902608,13.846819184361891,14.208796436448559,11.511482074125329,14.67586385849587,18.470786662630282,17.297928469489253,16.73225792500973,21.658521818103189,15.798123080915108,20.685464688837953,25.619513038965533,25.686978333261255,20.056221078579767,15.739739653159191,18.483760757687151,18.529170090386195,21.441854430653464,20.3221900272456,17.312199974051808,15.888941746313193,16.38455217748562,16.644034078623015,18.626475803312719,18.307313064913721,16.919084893828657,16.331358387752452,15.74492929118194,19.113004367945337,21.793452406694634,20.671193184275396,18.596635384681917,15.864290965705141,16.960601998010638,13.906500021623492,14.618777840245642,14.594127059637589,13.948017125805475,10.810880941054361,10.542317173377157,10.975651948276608,11.232539030402629,11.421960818232929,10.670760714440167,10,10.653894390866236,13.720970462310254,15.340137525407602,15.643731349738356,15.449119923885309,14.677161268001557,13.521169398434459,14.46049388055183,15.800717899926481,15.305107468754056,15.367383125027029,15.194827660770661,13.540630541019764,36.576136314492061,40.08173679885828,44.228257579033858,47.732560653894396,62.074125329758253,26.364226095229856,18.965099684297023,19.89663970938027,20.466202482376854,21.720797474376162,22.449941616572243,12.799809713272499,14.430653461921031,15.445227695368249,15.964191497643039,17.147428966829565,18.527872680880506,12.244518444838473,26.717121480776715,27.661635600916838,28.184491631708688,27.146564027159105,28.850062708126107,12.576655278294339,37.50248670155257,38.29001427150456,38.982830947541409,40.298404186308005,45.964191497643036,21.498940448903689,13.535440902997015,14.913289798036587,15.188340613242225,15.682653634908966,16.786749124248583,11.680145309864637,19.599532932577951,20.781472992258792,21.413311421528348,22.291657656878435,24.226095229857716,16.494831985469013,36.192103100808716,39.32145482852571,40.879643644855769,38.815465121307788,45.890239155818882,31.229511741556028,17.41469532500108,18.464299615101844,19.423085239804522,18.295636379362541,19.308913203304069,13.605501016304112,18.775677896466721,18.65242399342646,19.883665614323402,18.795139039052025,20.807421182372529,13.916879297668988,15.895428793841631,16.16658738053021,15.499718894607101,15.502313713618475,18.513601176317952,14.469575747091641,18.718591878216493,20.224884314319077,20.6309734895991,21.009817065259696,23.385373870172558,17.031959520823424,18.511006357306577,19.050728711672363,17.850624918911905,17.988150326514727,18.421485101414177,13.243523764217446,18.710807421182373,26.082688232495784,22.370799636725337,20.270293647018121,20.733468840548372,14.803009990053194],\"sizemode\":\"diameter\",\"symbol\":\"circle\",\"line\":{\"colorbar\":{\"title\":\"\",\"ticklen\":2},\"cmin\":846,\"cmax\":70215,\"colorscale\":[[\"0\",\"rgba(68,1,84,1)\"],[\"0.0416666666666667\",\"rgba(70,19,97,1)\"],[\"0.0833333333333333\",\"rgba(72,32,111,1)\"],[\"0.125\",\"rgba(71,45,122,1)\"],[\"0.166666666666667\",\"rgba(68,58,128,1)\"],[\"0.208333333333333\",\"rgba(64,70,135,1)\"],[\"0.25\",\"rgba(60,82,138,1)\"],[\"0.291666666666667\",\"rgba(56,93,140,1)\"],[\"0.333333333333333\",\"rgba(49,104,142,1)\"],[\"0.375\",\"rgba(46,114,142,1)\"],[\"0.416666666666667\",\"rgba(42,123,142,1)\"],[\"0.458333333333333\",\"rgba(38,133,141,1)\"],[\"0.5\",\"rgba(37,144,140,1)\"],[\"0.541666666666667\",\"rgba(33,154,138,1)\"],[\"0.583333333333333\",\"rgba(39,164,133,1)\"],[\"0.625\",\"rgba(47,174,127,1)\"],[\"0.666666666666667\",\"rgba(53,183,121,1)\"],[\"0.708333333333333\",\"rgba(79,191,110,1)\"],[\"0.75\",\"rgba(98,199,98,1)\"],[\"0.791666666666667\",\"rgba(119,207,85,1)\"],[\"0.833333333333333\",\"rgba(147,214,70,1)\"],[\"0.875\",\"rgba(172,220,52,1)\"],[\"0.916666666666667\",\"rgba(199,225,42,1)\"],[\"0.958333333333333\",\"rgba(226,228,40,1)\"],[\"1\",\"rgba(253,231,37,1)\"]],\"showscale\":false,\"color\":[60067,70215,62291,44169,37318,12420,12452,17656,23295,14615,14002,7366,7348,9583,11347,7064,10290,3912,7616,11005,14643,8744,8927,5571,6221,8555,10631,8549,8013,4890,1614,2717,2781,2636,3513,2907,5872,9547,10043,8132,9254,4647,1574,2117,2586,2209,2872,1744,1536,2195,3215,3119,3128,2117,4288,5766,6391,5632,6744,3585,17286,24021,25727,23940,21736,8643,13563,14821,14648,15390,15427,7487,4021,5430,5862,5877,6635,3648,1482,2108,2570,2900,2991,1445,9318,8685,9086,9203,12344,4878,6395,7059,6191,6241,6875,3255,4384,4870,4740,4130,6909,3183,5304,5492,5723,5101,6848,3240,10147,17586,24283,11802,21949,11943,5061,8774,12393,6897,15960,8267,4658,9100,11345,4830,9592,5265,8150,10809,14779,9465,22484,11723,14761,19419,24878,15635,28121,11271,4755,5897,7874,6054,12144,5867,6435,11334,14796,8333,15131,8468,5076,5651,7339,3949,8961,4459,4312,4326,4746,6030,9095,6778,1181,1769,1691,2298,5112,3128,10698,14138,14274,15488,25903,13404,5957,6497,7422,10517,22449,15185,4211,5097,5024,5342,9555,8845,5434,6317,6581,6386,11698,6371,3987,5500,5681,6497,9985,6907,4850,6198,7270,9212,14778,10869,5461,6535,6339,8923,15388,12954,3901,4262,4991,6834,11171,10008,4539,3637,3662,5068,8478,7955,4029,5558,5529,7431,9744,4462,15620,18944,21722,22574,28778,14174,3735,5339,6179,6103,9087,6184,5441,7330,8296,8700,11604,8863,2210,3990,4555,4266,7337,4627,4737,5265,5642,6485,9874,5702,2960,3962,5577,5970,9520,5695,3339,4342,5082,5881,8888,5262,8820,10623,12419,14453,19353,9684,864,950,1029,1188,2275,1739,4246,5176,5045,5682,6396,4165,1251,1964,3245,2164,2057,1673,3052,5243,7420,5228,5090,3211,3117,5368,5681,4206,3406,1752,1876,3059,4330,4432,4164,1942,2858,5390,6996,6827,5656,2908,2033,4560,3994,3811,4090,2011,4450,7375,6471,6035,9832,5315,9082,12885,12937,8597,5270,7385,7420,9665,8802,6482,5385,5767,5967,7495,7249,6179,5726,5274,7870,9936,9071,7472,5366,6211,3857,4406,4387,3889,1471,1264,1598,1796,1942,1363,846,1350,3714,4962,5196,5046,4451,3560,4284,5317,4935,4983,4850,3575,21330,24032,27228,29929,40983,13459,7756,8474,8913,9880,10442,3004,4261,5043,5443,6355,7419,2576,13731,14459,14862,14062,15375,2832,22044,22651,23185,24199,28566,9709,3571,4633,4845,5226,6077,2141,8245,9156,9643,10320,11811,5852,21034,23446,24647,23056,28509,17209,6561,7370,8109,7240,8021,3625,7610,7515,8464,7625,9176,3865,5390,5599,5085,5087,7408,4291,7566,8727,9040,9332,11163,6266,7406,7822,6897,7003,7337,3346,7560,13242,10381,8762,9119,4548]}},\"hoverinfo\":[\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\",\"text\"],\"text\":[\"Province:  Bangkok <br>Year:  2017 <br>Total Cases:  60067\",\"Province:  Bangkok <br>Year:  2018 <br>Total Cases:  70215\",\"Province:  Bangkok <br>Year:  2019 <br>Total Cases:  62291\",\"Province:  Bangkok <br>Year:  2020 <br>Total Cases:  44169\",\"Province:  Bangkok <br>Year:  2021 <br>Total Cases:  37318\",\"Province:  Bangkok <br>Year:  2022 <br>Total Cases:  12420\",\"Province:  Samut Prakan <br>Year:  2017 <br>Total Cases:  12452\",\"Province:  Samut Prakan <br>Year:  2018 <br>Total Cases:  17656\",\"Province:  Samut Prakan <br>Year:  2019 <br>Total Cases:  23295\",\"Province:  Samut Prakan <br>Year:  2020 <br>Total Cases:  14615\",\"Province:  Samut Prakan <br>Year:  2021 <br>Total Cases:  14002\",\"Province:  Samut Prakan <br>Year:  2022 <br>Total Cases:  7366\",\"Province:  Nonthaburi <br>Year:  2017 <br>Total Cases:  7348\",\"Province:  Nonthaburi <br>Year:  2018 <br>Total Cases:  9583\",\"Province:  Nonthaburi <br>Year:  2019 <br>Total Cases:  11347\",\"Province:  Nonthaburi <br>Year:  2020 <br>Total Cases:  7064\",\"Province:  Nonthaburi <br>Year:  2021 <br>Total Cases:  10290\",\"Province:  Nonthaburi <br>Year:  2022 <br>Total Cases:  3912\",\"Province:  Pathum Thani <br>Year:  2017 <br>Total Cases:  7616\",\"Province:  Pathum Thani <br>Year:  2018 <br>Total Cases:  11005\",\"Province:  Pathum Thani <br>Year:  2019 <br>Total Cases:  14643\",\"Province:  Pathum Thani <br>Year:  2020 <br>Total Cases:  8744\",\"Province:  Pathum Thani <br>Year:  2021 <br>Total Cases:  8927\",\"Province:  Pathum Thani <br>Year:  2022 <br>Total Cases:  5571\",\"Province:  Phra Nakhon Si Ayutthaya <br>Year:  2017 <br>Total Cases:  6221\",\"Province:  Phra Nakhon Si Ayutthaya <br>Year:  2018 <br>Total Cases:  8555\",\"Province:  Phra Nakhon Si Ayutthaya <br>Year:  2019 <br>Total Cases:  10631\",\"Province:  Phra Nakhon Si Ayutthaya <br>Year:  2020 <br>Total Cases:  8549\",\"Province:  Phra Nakhon Si Ayutthaya <br>Year:  2021 <br>Total Cases:  8013\",\"Province:  Phra Nakhon Si Ayutthaya <br>Year:  2022 <br>Total Cases:  4890\",\"Province:  Ang Thong <br>Year:  2017 <br>Total Cases:  1614\",\"Province:  Ang Thong <br>Year:  2018 <br>Total Cases:  2717\",\"Province:  Ang Thong <br>Year:  2019 <br>Total Cases:  2781\",\"Province:  Ang Thong <br>Year:  2020 <br>Total Cases:  2636\",\"Province:  Ang Thong <br>Year:  2021 <br>Total Cases:  3513\",\"Province:  Ang Thong <br>Year:  2022 <br>Total Cases:  2907\",\"Province:  Lop Buri <br>Year:  2017 <br>Total Cases:  5872\",\"Province:  Lop Buri <br>Year:  2018 <br>Total Cases:  9547\",\"Province:  Lop Buri <br>Year:  2019 <br>Total Cases:  10043\",\"Province:  Lop Buri <br>Year:  2020 <br>Total Cases:  8132\",\"Province:  Lop Buri <br>Year:  2021 <br>Total Cases:  9254\",\"Province:  Lop Buri <br>Year:  2022 <br>Total Cases:  4647\",\"Province:  Sing Buri <br>Year:  2017 <br>Total Cases:  1574\",\"Province:  Sing Buri <br>Year:  2018 <br>Total Cases:  2117\",\"Province:  Sing Buri <br>Year:  2019 <br>Total Cases:  2586\",\"Province:  Sing Buri <br>Year:  2020 <br>Total Cases:  2209\",\"Province:  Sing Buri <br>Year:  2021 <br>Total Cases:  2872\",\"Province:  Sing Buri <br>Year:  2022 <br>Total Cases:  1744\",\"Province:  Chai Nat <br>Year:  2017 <br>Total Cases:  1536\",\"Province:  Chai Nat <br>Year:  2018 <br>Total Cases:  2195\",\"Province:  Chai Nat <br>Year:  2019 <br>Total Cases:  3215\",\"Province:  Chai Nat <br>Year:  2020 <br>Total Cases:  3119\",\"Province:  Chai Nat <br>Year:  2021 <br>Total Cases:  3128\",\"Province:  Chai Nat <br>Year:  2022 <br>Total Cases:  2117\",\"Province:  Saraburi <br>Year:  2017 <br>Total Cases:  4288\",\"Province:  Saraburi <br>Year:  2018 <br>Total Cases:  5766\",\"Province:  Saraburi <br>Year:  2019 <br>Total Cases:  6391\",\"Province:  Saraburi <br>Year:  2020 <br>Total Cases:  5632\",\"Province:  Saraburi <br>Year:  2021 <br>Total Cases:  6744\",\"Province:  Saraburi <br>Year:  2022 <br>Total Cases:  3585\",\"Province:  Chon Buri <br>Year:  2017 <br>Total Cases:  17286\",\"Province:  Chon Buri <br>Year:  2018 <br>Total Cases:  24021\",\"Province:  Chon Buri <br>Year:  2019 <br>Total Cases:  25727\",\"Province:  Chon Buri <br>Year:  2020 <br>Total Cases:  23940\",\"Province:  Chon Buri <br>Year:  2021 <br>Total Cases:  21736\",\"Province:  Chon Buri <br>Year:  2022 <br>Total Cases:  8643\",\"Province:  Rayong <br>Year:  2017 <br>Total Cases:  13563\",\"Province:  Rayong <br>Year:  2018 <br>Total Cases:  14821\",\"Province:  Rayong <br>Year:  2019 <br>Total Cases:  14648\",\"Province:  Rayong <br>Year:  2020 <br>Total Cases:  15390\",\"Province:  Rayong <br>Year:  2021 <br>Total Cases:  15427\",\"Province:  Rayong <br>Year:  2022 <br>Total Cases:  7487\",\"Province:  Chanthaburi <br>Year:  2017 <br>Total Cases:  4021\",\"Province:  Chanthaburi <br>Year:  2018 <br>Total Cases:  5430\",\"Province:  Chanthaburi <br>Year:  2019 <br>Total Cases:  5862\",\"Province:  Chanthaburi <br>Year:  2020 <br>Total Cases:  5877\",\"Province:  Chanthaburi <br>Year:  2021 <br>Total Cases:  6635\",\"Province:  Chanthaburi <br>Year:  2022 <br>Total Cases:  3648\",\"Province:  Trat <br>Year:  2017 <br>Total Cases:  1482\",\"Province:  Trat <br>Year:  2018 <br>Total Cases:  2108\",\"Province:  Trat <br>Year:  2019 <br>Total Cases:  2570\",\"Province:  Trat <br>Year:  2020 <br>Total Cases:  2900\",\"Province:  Trat <br>Year:  2021 <br>Total Cases:  2991\",\"Province:  Trat <br>Year:  2022 <br>Total Cases:  1445\",\"Province:  Chachoengsao <br>Year:  2017 <br>Total Cases:  9318\",\"Province:  Chachoengsao <br>Year:  2018 <br>Total Cases:  8685\",\"Province:  Chachoengsao <br>Year:  2019 <br>Total Cases:  9086\",\"Province:  Chachoengsao <br>Year:  2020 <br>Total Cases:  9203\",\"Province:  Chachoengsao <br>Year:  2021 <br>Total Cases:  12344\",\"Province:  Chachoengsao <br>Year:  2022 <br>Total Cases:  4878\",\"Province:  Prachin Buri <br>Year:  2017 <br>Total Cases:  6395\",\"Province:  Prachin Buri <br>Year:  2018 <br>Total Cases:  7059\",\"Province:  Prachin Buri <br>Year:  2019 <br>Total Cases:  6191\",\"Province:  Prachin Buri <br>Year:  2020 <br>Total Cases:  6241\",\"Province:  Prachin Buri <br>Year:  2021 <br>Total Cases:  6875\",\"Province:  Prachin Buri <br>Year:  2022 <br>Total Cases:  3255\",\"Province:  Nakhon Nayok <br>Year:  2017 <br>Total Cases:  4384\",\"Province:  Nakhon Nayok <br>Year:  2018 <br>Total Cases:  4870\",\"Province:  Nakhon Nayok <br>Year:  2019 <br>Total Cases:  4740\",\"Province:  Nakhon Nayok <br>Year:  2020 <br>Total Cases:  4130\",\"Province:  Nakhon Nayok <br>Year:  2021 <br>Total Cases:  6909\",\"Province:  Nakhon Nayok <br>Year:  2022 <br>Total Cases:  3183\",\"Province:  Sa Kaeo <br>Year:  2017 <br>Total Cases:  5304\",\"Province:  Sa Kaeo <br>Year:  2018 <br>Total Cases:  5492\",\"Province:  Sa Kaeo <br>Year:  2019 <br>Total Cases:  5723\",\"Province:  Sa Kaeo <br>Year:  2020 <br>Total Cases:  5101\",\"Province:  Sa Kaeo <br>Year:  2021 <br>Total Cases:  6848\",\"Province:  Sa Kaeo <br>Year:  2022 <br>Total Cases:  3240\",\"Province:  Nakhon Ratchasima <br>Year:  2017 <br>Total Cases:  10147\",\"Province:  Nakhon Ratchasima <br>Year:  2018 <br>Total Cases:  17586\",\"Province:  Nakhon Ratchasima <br>Year:  2019 <br>Total Cases:  24283\",\"Province:  Nakhon Ratchasima <br>Year:  2020 <br>Total Cases:  11802\",\"Province:  Nakhon Ratchasima <br>Year:  2021 <br>Total Cases:  21949\",\"Province:  Nakhon Ratchasima <br>Year:  2022 <br>Total Cases:  11943\",\"Province:  Buri Ram <br>Year:  2017 <br>Total Cases:  5061\",\"Province:  Buri Ram <br>Year:  2018 <br>Total Cases:  8774\",\"Province:  Buri Ram <br>Year:  2019 <br>Total Cases:  12393\",\"Province:  Buri Ram <br>Year:  2020 <br>Total Cases:  6897\",\"Province:  Buri Ram <br>Year:  2021 <br>Total Cases:  15960\",\"Province:  Buri Ram <br>Year:  2022 <br>Total Cases:  8267\",\"Province:  Surin <br>Year:  2017 <br>Total Cases:  4658\",\"Province:  Surin <br>Year:  2018 <br>Total Cases:  9100\",\"Province:  Surin <br>Year:  2019 <br>Total Cases:  11345\",\"Province:  Surin <br>Year:  2020 <br>Total Cases:  4830\",\"Province:  Surin <br>Year:  2021 <br>Total Cases:  9592\",\"Province:  Surin <br>Year:  2022 <br>Total Cases:  5265\",\"Province:  Si Sa Ket <br>Year:  2017 <br>Total Cases:  8150\",\"Province:  Si Sa Ket <br>Year:  2018 <br>Total Cases:  10809\",\"Province:  Si Sa Ket <br>Year:  2019 <br>Total Cases:  14779\",\"Province:  Si Sa Ket <br>Year:  2020 <br>Total Cases:  9465\",\"Province:  Si Sa Ket <br>Year:  2021 <br>Total Cases:  22484\",\"Province:  Si Sa Ket <br>Year:  2022 <br>Total Cases:  11723\",\"Province:  Ubon Ratchathani <br>Year:  2017 <br>Total Cases:  14761\",\"Province:  Ubon Ratchathani <br>Year:  2018 <br>Total Cases:  19419\",\"Province:  Ubon Ratchathani <br>Year:  2019 <br>Total Cases:  24878\",\"Province:  Ubon Ratchathani <br>Year:  2020 <br>Total Cases:  15635\",\"Province:  Ubon Ratchathani <br>Year:  2021 <br>Total Cases:  28121\",\"Province:  Ubon Ratchathani <br>Year:  2022 <br>Total Cases:  11271\",\"Province:  Yasothon <br>Year:  2017 <br>Total Cases:  4755\",\"Province:  Yasothon <br>Year:  2018 <br>Total Cases:  5897\",\"Province:  Yasothon <br>Year:  2019 <br>Total Cases:  7874\",\"Province:  Yasothon <br>Year:  2020 <br>Total Cases:  6054\",\"Province:  Yasothon <br>Year:  2021 <br>Total Cases:  12144\",\"Province:  Yasothon <br>Year:  2022 <br>Total Cases:  5867\",\"Province:  Chaiyaphum <br>Year:  2017 <br>Total Cases:  6435\",\"Province:  Chaiyaphum <br>Year:  2018 <br>Total Cases:  11334\",\"Province:  Chaiyaphum <br>Year:  2019 <br>Total Cases:  14796\",\"Province:  Chaiyaphum <br>Year:  2020 <br>Total Cases:  8333\",\"Province:  Chaiyaphum <br>Year:  2021 <br>Total Cases:  15131\",\"Province:  Chaiyaphum <br>Year:  2022 <br>Total Cases:  8468\",\"Province:  Amnat Charoen <br>Year:  2017 <br>Total Cases:  5076\",\"Province:  Amnat Charoen <br>Year:  2018 <br>Total Cases:  5651\",\"Province:  Amnat Charoen <br>Year:  2019 <br>Total Cases:  7339\",\"Province:  Amnat Charoen <br>Year:  2020 <br>Total Cases:  3949\",\"Province:  Amnat Charoen <br>Year:  2021 <br>Total Cases:  8961\",\"Province:  Amnat Charoen <br>Year:  2022 <br>Total Cases:  4459\",\"Province:  Bueng Kan <br>Year:  2017 <br>Total Cases:  4312\",\"Province:  Bueng Kan <br>Year:  2018 <br>Total Cases:  4326\",\"Province:  Bueng Kan <br>Year:  2019 <br>Total Cases:  4746\",\"Province:  Bueng Kan <br>Year:  2020 <br>Total Cases:  6030\",\"Province:  Bueng Kan <br>Year:  2021 <br>Total Cases:  9095\",\"Province:  Bueng Kan <br>Year:  2022 <br>Total Cases:  6778\",\"Province:  Nong Bua Lam Phu <br>Year:  2017 <br>Total Cases:  1181\",\"Province:  Nong Bua Lam Phu <br>Year:  2018 <br>Total Cases:  1769\",\"Province:  Nong Bua Lam Phu <br>Year:  2019 <br>Total Cases:  1691\",\"Province:  Nong Bua Lam Phu <br>Year:  2020 <br>Total Cases:  2298\",\"Province:  Nong Bua Lam Phu <br>Year:  2021 <br>Total Cases:  5112\",\"Province:  Nong Bua Lam Phu <br>Year:  2022 <br>Total Cases:  3128\",\"Province:  Khon Kaen <br>Year:  2017 <br>Total Cases:  10698\",\"Province:  Khon Kaen <br>Year:  2018 <br>Total Cases:  14138\",\"Province:  Khon Kaen <br>Year:  2019 <br>Total Cases:  14274\",\"Province:  Khon Kaen <br>Year:  2020 <br>Total Cases:  15488\",\"Province:  Khon Kaen <br>Year:  2021 <br>Total Cases:  25903\",\"Province:  Khon Kaen <br>Year:  2022 <br>Total Cases:  13404\",\"Province:  Udon Thani <br>Year:  2017 <br>Total Cases:  5957\",\"Province:  Udon Thani <br>Year:  2018 <br>Total Cases:  6497\",\"Province:  Udon Thani <br>Year:  2019 <br>Total Cases:  7422\",\"Province:  Udon Thani <br>Year:  2020 <br>Total Cases:  10517\",\"Province:  Udon Thani <br>Year:  2021 <br>Total Cases:  22449\",\"Province:  Udon Thani <br>Year:  2022 <br>Total Cases:  15185\",\"Province:  Loei <br>Year:  2017 <br>Total Cases:  4211\",\"Province:  Loei <br>Year:  2018 <br>Total Cases:  5097\",\"Province:  Loei <br>Year:  2019 <br>Total Cases:  5024\",\"Province:  Loei <br>Year:  2020 <br>Total Cases:  5342\",\"Province:  Loei <br>Year:  2021 <br>Total Cases:  9555\",\"Province:  Loei <br>Year:  2022 <br>Total Cases:  8845\",\"Province:  Nong Khai <br>Year:  2017 <br>Total Cases:  5434\",\"Province:  Nong Khai <br>Year:  2018 <br>Total Cases:  6317\",\"Province:  Nong Khai <br>Year:  2019 <br>Total Cases:  6581\",\"Province:  Nong Khai <br>Year:  2020 <br>Total Cases:  6386\",\"Province:  Nong Khai <br>Year:  2021 <br>Total Cases:  11698\",\"Province:  Nong Khai <br>Year:  2022 <br>Total Cases:  6371\",\"Province:  Maha Sarakham <br>Year:  2017 <br>Total Cases:  3987\",\"Province:  Maha Sarakham <br>Year:  2018 <br>Total Cases:  5500\",\"Province:  Maha Sarakham <br>Year:  2019 <br>Total Cases:  5681\",\"Province:  Maha Sarakham <br>Year:  2020 <br>Total Cases:  6497\",\"Province:  Maha Sarakham <br>Year:  2021 <br>Total Cases:  9985\",\"Province:  Maha Sarakham <br>Year:  2022 <br>Total Cases:  6907\",\"Province:  Roi Et <br>Year:  2017 <br>Total Cases:  4850\",\"Province:  Roi Et <br>Year:  2018 <br>Total Cases:  6198\",\"Province:  Roi Et <br>Year:  2019 <br>Total Cases:  7270\",\"Province:  Roi Et <br>Year:  2020 <br>Total Cases:  9212\",\"Province:  Roi Et <br>Year:  2021 <br>Total Cases:  14778\",\"Province:  Roi Et <br>Year:  2022 <br>Total Cases:  10869\",\"Province:  Kalasin <br>Year:  2017 <br>Total Cases:  5461\",\"Province:  Kalasin <br>Year:  2018 <br>Total Cases:  6535\",\"Province:  Kalasin <br>Year:  2019 <br>Total Cases:  6339\",\"Province:  Kalasin <br>Year:  2020 <br>Total Cases:  8923\",\"Province:  Kalasin <br>Year:  2021 <br>Total Cases:  15388\",\"Province:  Kalasin <br>Year:  2022 <br>Total Cases:  12954\",\"Province:  Sakon Nakhon <br>Year:  2017 <br>Total Cases:  3901\",\"Province:  Sakon Nakhon <br>Year:  2018 <br>Total Cases:  4262\",\"Province:  Sakon Nakhon <br>Year:  2019 <br>Total Cases:  4991\",\"Province:  Sakon Nakhon <br>Year:  2020 <br>Total Cases:  6834\",\"Province:  Sakon Nakhon <br>Year:  2021 <br>Total Cases:  11171\",\"Province:  Sakon Nakhon <br>Year:  2022 <br>Total Cases:  10008\",\"Province:  Nakhon Phanom <br>Year:  2017 <br>Total Cases:  4539\",\"Province:  Nakhon Phanom <br>Year:  2018 <br>Total Cases:  3637\",\"Province:  Nakhon Phanom <br>Year:  2019 <br>Total Cases:  3662\",\"Province:  Nakhon Phanom <br>Year:  2020 <br>Total Cases:  5068\",\"Province:  Nakhon Phanom <br>Year:  2021 <br>Total Cases:  8478\",\"Province:  Nakhon Phanom <br>Year:  2022 <br>Total Cases:  7955\",\"Province:  Mukdahan <br>Year:  2017 <br>Total Cases:  4029\",\"Province:  Mukdahan <br>Year:  2018 <br>Total Cases:  5558\",\"Province:  Mukdahan <br>Year:  2019 <br>Total Cases:  5529\",\"Province:  Mukdahan <br>Year:  2020 <br>Total Cases:  7431\",\"Province:  Mukdahan <br>Year:  2021 <br>Total Cases:  9744\",\"Province:  Mukdahan <br>Year:  2022 <br>Total Cases:  4462\",\"Province:  Chiang Mai <br>Year:  2017 <br>Total Cases:  15620\",\"Province:  Chiang Mai <br>Year:  2018 <br>Total Cases:  18944\",\"Province:  Chiang Mai <br>Year:  2019 <br>Total Cases:  21722\",\"Province:  Chiang Mai <br>Year:  2020 <br>Total Cases:  22574\",\"Province:  Chiang Mai <br>Year:  2021 <br>Total Cases:  28778\",\"Province:  Chiang Mai <br>Year:  2022 <br>Total Cases:  14174\",\"Province:  Lamphun <br>Year:  2017 <br>Total Cases:  3735\",\"Province:  Lamphun <br>Year:  2018 <br>Total Cases:  5339\",\"Province:  Lamphun <br>Year:  2019 <br>Total Cases:  6179\",\"Province:  Lamphun <br>Year:  2020 <br>Total Cases:  6103\",\"Province:  Lamphun <br>Year:  2021 <br>Total Cases:  9087\",\"Province:  Lamphun <br>Year:  2022 <br>Total Cases:  6184\",\"Province:  Lampang <br>Year:  2017 <br>Total Cases:  5441\",\"Province:  Lampang <br>Year:  2018 <br>Total Cases:  7330\",\"Province:  Lampang <br>Year:  2019 <br>Total Cases:  8296\",\"Province:  Lampang <br>Year:  2020 <br>Total Cases:  8700\",\"Province:  Lampang <br>Year:  2021 <br>Total Cases:  11604\",\"Province:  Lampang <br>Year:  2022 <br>Total Cases:  8863\",\"Province:  Uttaradit <br>Year:  2017 <br>Total Cases:  2210\",\"Province:  Uttaradit <br>Year:  2018 <br>Total Cases:  3990\",\"Province:  Uttaradit <br>Year:  2019 <br>Total Cases:  4555\",\"Province:  Uttaradit <br>Year:  2020 <br>Total Cases:  4266\",\"Province:  Uttaradit <br>Year:  2021 <br>Total Cases:  7337\",\"Province:  Uttaradit <br>Year:  2022 <br>Total Cases:  4627\",\"Province:  Phrae <br>Year:  2017 <br>Total Cases:  4737\",\"Province:  Phrae <br>Year:  2018 <br>Total Cases:  5265\",\"Province:  Phrae <br>Year:  2019 <br>Total Cases:  5642\",\"Province:  Phrae <br>Year:  2020 <br>Total Cases:  6485\",\"Province:  Phrae <br>Year:  2021 <br>Total Cases:  9874\",\"Province:  Phrae <br>Year:  2022 <br>Total Cases:  5702\",\"Province:  Nan <br>Year:  2017 <br>Total Cases:  2960\",\"Province:  Nan <br>Year:  2018 <br>Total Cases:  3962\",\"Province:  Nan <br>Year:  2019 <br>Total Cases:  5577\",\"Province:  Nan <br>Year:  2020 <br>Total Cases:  5970\",\"Province:  Nan <br>Year:  2021 <br>Total Cases:  9520\",\"Province:  Nan <br>Year:  2022 <br>Total Cases:  5695\",\"Province:  Phayao <br>Year:  2017 <br>Total Cases:  3339\",\"Province:  Phayao <br>Year:  2018 <br>Total Cases:  4342\",\"Province:  Phayao <br>Year:  2019 <br>Total Cases:  5082\",\"Province:  Phayao <br>Year:  2020 <br>Total Cases:  5881\",\"Province:  Phayao <br>Year:  2021 <br>Total Cases:  8888\",\"Province:  Phayao <br>Year:  2022 <br>Total Cases:  5262\",\"Province:  Chiang Rai <br>Year:  2017 <br>Total Cases:  8820\",\"Province:  Chiang Rai <br>Year:  2018 <br>Total Cases:  10623\",\"Province:  Chiang Rai <br>Year:  2019 <br>Total Cases:  12419\",\"Province:  Chiang Rai <br>Year:  2020 <br>Total Cases:  14453\",\"Province:  Chiang Rai <br>Year:  2021 <br>Total Cases:  19353\",\"Province:  Chiang Rai <br>Year:  2022 <br>Total Cases:  9684\",\"Province:  Mae Hong Son <br>Year:  2017 <br>Total Cases:  864\",\"Province:  Mae Hong Son <br>Year:  2018 <br>Total Cases:  950\",\"Province:  Mae Hong Son <br>Year:  2019 <br>Total Cases:  1029\",\"Province:  Mae Hong Son <br>Year:  2020 <br>Total Cases:  1188\",\"Province:  Mae Hong Son <br>Year:  2021 <br>Total Cases:  2275\",\"Province:  Mae Hong Son <br>Year:  2022 <br>Total Cases:  1739\",\"Province:  Nakhon Sawan <br>Year:  2017 <br>Total Cases:  4246\",\"Province:  Nakhon Sawan <br>Year:  2018 <br>Total Cases:  5176\",\"Province:  Nakhon Sawan <br>Year:  2019 <br>Total Cases:  5045\",\"Province:  Nakhon Sawan <br>Year:  2020 <br>Total Cases:  5682\",\"Province:  Nakhon Sawan <br>Year:  2021 <br>Total Cases:  6396\",\"Province:  Nakhon Sawan <br>Year:  2022 <br>Total Cases:  4165\",\"Province:  Uthai Thani <br>Year:  2017 <br>Total Cases:  1251\",\"Province:  Uthai Thani <br>Year:  2018 <br>Total Cases:  1964\",\"Province:  Uthai Thani <br>Year:  2019 <br>Total Cases:  3245\",\"Province:  Uthai Thani <br>Year:  2020 <br>Total Cases:  2164\",\"Province:  Uthai Thani <br>Year:  2021 <br>Total Cases:  2057\",\"Province:  Uthai Thani <br>Year:  2022 <br>Total Cases:  1673\",\"Province:  Kamphaeng Phet <br>Year:  2017 <br>Total Cases:  3052\",\"Province:  Kamphaeng Phet <br>Year:  2018 <br>Total Cases:  5243\",\"Province:  Kamphaeng Phet <br>Year:  2019 <br>Total Cases:  7420\",\"Province:  Kamphaeng Phet <br>Year:  2020 <br>Total Cases:  5228\",\"Province:  Kamphaeng Phet <br>Year:  2021 <br>Total Cases:  5090\",\"Province:  Kamphaeng Phet <br>Year:  2022 <br>Total Cases:  3211\",\"Province:  Tak <br>Year:  2017 <br>Total Cases:  3117\",\"Province:  Tak <br>Year:  2018 <br>Total Cases:  5368\",\"Province:  Tak <br>Year:  2019 <br>Total Cases:  5681\",\"Province:  Tak <br>Year:  2020 <br>Total Cases:  4206\",\"Province:  Tak <br>Year:  2021 <br>Total Cases:  3406\",\"Province:  Tak <br>Year:  2022 <br>Total Cases:  1752\",\"Province:  Sukhothai <br>Year:  2017 <br>Total Cases:  1876\",\"Province:  Sukhothai <br>Year:  2018 <br>Total Cases:  3059\",\"Province:  Sukhothai <br>Year:  2019 <br>Total Cases:  4330\",\"Province:  Sukhothai <br>Year:  2020 <br>Total Cases:  4432\",\"Province:  Sukhothai <br>Year:  2021 <br>Total Cases:  4164\",\"Province:  Sukhothai <br>Year:  2022 <br>Total Cases:  1942\",\"Province:  Phitsanulok <br>Year:  2017 <br>Total Cases:  2858\",\"Province:  Phitsanulok <br>Year:  2018 <br>Total Cases:  5390\",\"Province:  Phitsanulok <br>Year:  2019 <br>Total Cases:  6996\",\"Province:  Phitsanulok <br>Year:  2020 <br>Total Cases:  6827\",\"Province:  Phitsanulok <br>Year:  2021 <br>Total Cases:  5656\",\"Province:  Phitsanulok <br>Year:  2022 <br>Total Cases:  2908\",\"Province:  Phichit <br>Year:  2017 <br>Total Cases:  2033\",\"Province:  Phichit <br>Year:  2018 <br>Total Cases:  4560\",\"Province:  Phichit <br>Year:  2019 <br>Total Cases:  3994\",\"Province:  Phichit <br>Year:  2020 <br>Total Cases:  3811\",\"Province:  Phichit <br>Year:  2021 <br>Total Cases:  4090\",\"Province:  Phichit <br>Year:  2022 <br>Total Cases:  2011\",\"Province:  Phetchabun <br>Year:  2017 <br>Total Cases:  4450\",\"Province:  Phetchabun <br>Year:  2018 <br>Total Cases:  7375\",\"Province:  Phetchabun <br>Year:  2019 <br>Total Cases:  6471\",\"Province:  Phetchabun <br>Year:  2020 <br>Total Cases:  6035\",\"Province:  Phetchabun <br>Year:  2021 <br>Total Cases:  9832\",\"Province:  Phetchabun <br>Year:  2022 <br>Total Cases:  5315\",\"Province:  Ratchaburi <br>Year:  2017 <br>Total Cases:  9082\",\"Province:  Ratchaburi <br>Year:  2018 <br>Total Cases:  12885\",\"Province:  Ratchaburi <br>Year:  2019 <br>Total Cases:  12937\",\"Province:  Ratchaburi <br>Year:  2020 <br>Total Cases:  8597\",\"Province:  Ratchaburi <br>Year:  2021 <br>Total Cases:  5270\",\"Province:  Ratchaburi <br>Year:  2022 <br>Total Cases:  7385\",\"Province:  Kanchanaburi <br>Year:  2017 <br>Total Cases:  7420\",\"Province:  Kanchanaburi <br>Year:  2018 <br>Total Cases:  9665\",\"Province:  Kanchanaburi <br>Year:  2019 <br>Total Cases:  8802\",\"Province:  Kanchanaburi <br>Year:  2020 <br>Total Cases:  6482\",\"Province:  Kanchanaburi <br>Year:  2021 <br>Total Cases:  5385\",\"Province:  Kanchanaburi <br>Year:  2022 <br>Total Cases:  5767\",\"Province:  Suphan Buri <br>Year:  2017 <br>Total Cases:  5967\",\"Province:  Suphan Buri <br>Year:  2018 <br>Total Cases:  7495\",\"Province:  Suphan Buri <br>Year:  2019 <br>Total Cases:  7249\",\"Province:  Suphan Buri <br>Year:  2020 <br>Total Cases:  6179\",\"Province:  Suphan Buri <br>Year:  2021 <br>Total Cases:  5726\",\"Province:  Suphan Buri <br>Year:  2022 <br>Total Cases:  5274\",\"Province:  Nakhon Pathom <br>Year:  2017 <br>Total Cases:  7870\",\"Province:  Nakhon Pathom <br>Year:  2018 <br>Total Cases:  9936\",\"Province:  Nakhon Pathom <br>Year:  2019 <br>Total Cases:  9071\",\"Province:  Nakhon Pathom <br>Year:  2020 <br>Total Cases:  7472\",\"Province:  Nakhon Pathom <br>Year:  2021 <br>Total Cases:  5366\",\"Province:  Nakhon Pathom <br>Year:  2022 <br>Total Cases:  6211\",\"Province:  Samut Sakhon <br>Year:  2017 <br>Total Cases:  3857\",\"Province:  Samut Sakhon <br>Year:  2018 <br>Total Cases:  4406\",\"Province:  Samut Sakhon <br>Year:  2019 <br>Total Cases:  4387\",\"Province:  Samut Sakhon <br>Year:  2020 <br>Total Cases:  3889\",\"Province:  Samut Sakhon <br>Year:  2021 <br>Total Cases:  1471\",\"Province:  Samut Sakhon <br>Year:  2022 <br>Total Cases:  1264\",\"Province:  Samut Songkhram <br>Year:  2017 <br>Total Cases:  1598\",\"Province:  Samut Songkhram <br>Year:  2018 <br>Total Cases:  1796\",\"Province:  Samut Songkhram <br>Year:  2019 <br>Total Cases:  1942\",\"Province:  Samut Songkhram <br>Year:  2020 <br>Total Cases:  1363\",\"Province:  Samut Songkhram <br>Year:  2021 <br>Total Cases:  846\",\"Province:  Samut Songkhram <br>Year:  2022 <br>Total Cases:  1350\",\"Province:  Phetchaburi <br>Year:  2017 <br>Total Cases:  3714\",\"Province:  Phetchaburi <br>Year:  2018 <br>Total Cases:  4962\",\"Province:  Phetchaburi <br>Year:  2019 <br>Total Cases:  5196\",\"Province:  Phetchaburi <br>Year:  2020 <br>Total Cases:  5046\",\"Province:  Phetchaburi <br>Year:  2021 <br>Total Cases:  4451\",\"Province:  Phetchaburi <br>Year:  2022 <br>Total Cases:  3560\",\"Province:  Prachuap Khiri Khan <br>Year:  2017 <br>Total Cases:  4284\",\"Province:  Prachuap Khiri Khan <br>Year:  2018 <br>Total Cases:  5317\",\"Province:  Prachuap Khiri Khan <br>Year:  2019 <br>Total Cases:  4935\",\"Province:  Prachuap Khiri Khan <br>Year:  2020 <br>Total Cases:  4983\",\"Province:  Prachuap Khiri Khan <br>Year:  2021 <br>Total Cases:  4850\",\"Province:  Prachuap Khiri Khan <br>Year:  2022 <br>Total Cases:  3575\",\"Province:  Nakhon Si Thammarat <br>Year:  2017 <br>Total Cases:  21330\",\"Province:  Nakhon Si Thammarat <br>Year:  2018 <br>Total Cases:  24032\",\"Province:  Nakhon Si Thammarat <br>Year:  2019 <br>Total Cases:  27228\",\"Province:  Nakhon Si Thammarat <br>Year:  2020 <br>Total Cases:  29929\",\"Province:  Nakhon Si Thammarat <br>Year:  2021 <br>Total Cases:  40983\",\"Province:  Nakhon Si Thammarat <br>Year:  2022 <br>Total Cases:  13459\",\"Province:  Krabi <br>Year:  2017 <br>Total Cases:  7756\",\"Province:  Krabi <br>Year:  2018 <br>Total Cases:  8474\",\"Province:  Krabi <br>Year:  2019 <br>Total Cases:  8913\",\"Province:  Krabi <br>Year:  2020 <br>Total Cases:  9880\",\"Province:  Krabi <br>Year:  2021 <br>Total Cases:  10442\",\"Province:  Krabi <br>Year:  2022 <br>Total Cases:  3004\",\"Province:  Phangnga <br>Year:  2017 <br>Total Cases:  4261\",\"Province:  Phangnga <br>Year:  2018 <br>Total Cases:  5043\",\"Province:  Phangnga <br>Year:  2019 <br>Total Cases:  5443\",\"Province:  Phangnga <br>Year:  2020 <br>Total Cases:  6355\",\"Province:  Phangnga <br>Year:  2021 <br>Total Cases:  7419\",\"Province:  Phangnga <br>Year:  2022 <br>Total Cases:  2576\",\"Province:  Phuket <br>Year:  2017 <br>Total Cases:  13731\",\"Province:  Phuket <br>Year:  2018 <br>Total Cases:  14459\",\"Province:  Phuket <br>Year:  2019 <br>Total Cases:  14862\",\"Province:  Phuket <br>Year:  2020 <br>Total Cases:  14062\",\"Province:  Phuket <br>Year:  2021 <br>Total Cases:  15375\",\"Province:  Phuket <br>Year:  2022 <br>Total Cases:  2832\",\"Province:  Surat Thani <br>Year:  2017 <br>Total Cases:  22044\",\"Province:  Surat Thani <br>Year:  2018 <br>Total Cases:  22651\",\"Province:  Surat Thani <br>Year:  2019 <br>Total Cases:  23185\",\"Province:  Surat Thani <br>Year:  2020 <br>Total Cases:  24199\",\"Province:  Surat Thani <br>Year:  2021 <br>Total Cases:  28566\",\"Province:  Surat Thani <br>Year:  2022 <br>Total Cases:  9709\",\"Province:  Ranong <br>Year:  2017 <br>Total Cases:  3571\",\"Province:  Ranong <br>Year:  2018 <br>Total Cases:  4633\",\"Province:  Ranong <br>Year:  2019 <br>Total Cases:  4845\",\"Province:  Ranong <br>Year:  2020 <br>Total Cases:  5226\",\"Province:  Ranong <br>Year:  2021 <br>Total Cases:  6077\",\"Province:  Ranong <br>Year:  2022 <br>Total Cases:  2141\",\"Province:  Chumphon <br>Year:  2017 <br>Total Cases:  8245\",\"Province:  Chumphon <br>Year:  2018 <br>Total Cases:  9156\",\"Province:  Chumphon <br>Year:  2019 <br>Total Cases:  9643\",\"Province:  Chumphon <br>Year:  2020 <br>Total Cases:  10320\",\"Province:  Chumphon <br>Year:  2021 <br>Total Cases:  11811\",\"Province:  Chumphon <br>Year:  2022 <br>Total Cases:  5852\",\"Province:  Songkhla <br>Year:  2017 <br>Total Cases:  21034\",\"Province:  Songkhla <br>Year:  2018 <br>Total Cases:  23446\",\"Province:  Songkhla <br>Year:  2019 <br>Total Cases:  24647\",\"Province:  Songkhla <br>Year:  2020 <br>Total Cases:  23056\",\"Province:  Songkhla <br>Year:  2021 <br>Total Cases:  28509\",\"Province:  Songkhla <br>Year:  2022 <br>Total Cases:  17209\",\"Province:  Satun <br>Year:  2017 <br>Total Cases:  6561\",\"Province:  Satun <br>Year:  2018 <br>Total Cases:  7370\",\"Province:  Satun <br>Year:  2019 <br>Total Cases:  8109\",\"Province:  Satun <br>Year:  2020 <br>Total Cases:  7240\",\"Province:  Satun <br>Year:  2021 <br>Total Cases:  8021\",\"Province:  Satun <br>Year:  2022 <br>Total Cases:  3625\",\"Province:  Trang <br>Year:  2017 <br>Total Cases:  7610\",\"Province:  Trang <br>Year:  2018 <br>Total Cases:  7515\",\"Province:  Trang <br>Year:  2019 <br>Total Cases:  8464\",\"Province:  Trang <br>Year:  2020 <br>Total Cases:  7625\",\"Province:  Trang <br>Year:  2021 <br>Total Cases:  9176\",\"Province:  Trang <br>Year:  2022 <br>Total Cases:  3865\",\"Province:  Phatthalung <br>Year:  2017 <br>Total Cases:  5390\",\"Province:  Phatthalung <br>Year:  2018 <br>Total Cases:  5599\",\"Province:  Phatthalung <br>Year:  2019 <br>Total Cases:  5085\",\"Province:  Phatthalung <br>Year:  2020 <br>Total Cases:  5087\",\"Province:  Phatthalung <br>Year:  2021 <br>Total Cases:  7408\",\"Province:  Phatthalung <br>Year:  2022 <br>Total Cases:  4291\",\"Province:  Pattani <br>Year:  2017 <br>Total Cases:  7566\",\"Province:  Pattani <br>Year:  2018 <br>Total Cases:  8727\",\"Province:  Pattani <br>Year:  2019 <br>Total Cases:  9040\",\"Province:  Pattani <br>Year:  2020 <br>Total Cases:  9332\",\"Province:  Pattani <br>Year:  2021 <br>Total Cases:  11163\",\"Province:  Pattani <br>Year:  2022 <br>Total Cases:  6266\",\"Province:  Yala <br>Year:  2017 <br>Total Cases:  7406\",\"Province:  Yala <br>Year:  2018 <br>Total Cases:  7822\",\"Province:  Yala <br>Year:  2019 <br>Total Cases:  6897\",\"Province:  Yala <br>Year:  2020 <br>Total Cases:  7003\",\"Province:  Yala <br>Year:  2021 <br>Total Cases:  7337\",\"Province:  Yala <br>Year:  2022 <br>Total Cases:  3346\",\"Province:  Narathiwat <br>Year:  2017 <br>Total Cases:  7560\",\"Province:  Narathiwat <br>Year:  2018 <br>Total Cases:  13242\",\"Province:  Narathiwat <br>Year:  2019 <br>Total Cases:  10381\",\"Province:  Narathiwat <br>Year:  2020 <br>Total Cases:  8762\",\"Province:  Narathiwat <br>Year:  2021 <br>Total Cases:  9119\",\"Province:  Narathiwat <br>Year:  2022 <br>Total Cases:  4548\"],\"textfont\":{\"size\":[86.833888336288538,100,89.719327076936395,66.207672014876962,57.319119491415478,25.016217618821088,25.057734723003072,31.809453790598106,39.125545993166973,27.864031483804006,27.068719456817888,18.459109977079098,18.435756605976735,21.335466851187132,23.62409721921896,18.06729230636163,22.252735371707825,13.977857544436276,18.783462353500845,23.180383168274012,27.900358949963241,20.246940275915755,20.484366215456472,16.130259914370974,16.973576093067507,20.001729879340914,22.695152013147084,19.993945422306794,19.298533927258575,15.24672404099814,10.996410500367599,12.427453185140337,12.510487393504302,12.322363015179691,13.460191151667171,12.673960991220863,16.520780175582754,21.288760108982398,21.932275223803138,19.452925658435326,20.908619123816113,14.931453531116205,10.94451412014012,11.64900748172815,12.257492539895342,11.768369156251351,12.628551658521818,11.165073736106907,10.895212558924015,11.750205423171733,13.073563118972451,12.949011806426501,12.960688491977685,11.64900748172815,14.465683518574579,16.383254767979935,17.194135709034295,16.209401894217876,17.652121264541798,13.553604636076633,31.329412273493922,40.067465294295715,42.280845910997705,39.962375124335082,37.102884573800978,20.11590191584137,26.499156683821305,28.131297841975524,27.906845997491676,28.869523850711413,28.917528002421829,18.616096527267224,14.119275180556155,15.947325174069109,16.507806080525881,16.527267223111188,17.510703628421918,13.635341434934913,10.825152445616919,11.637330796176967,12.236733987804351,12.664879124681054,12.782943389698568,10.7771482939065,20.991653332180078,20.170393115080223,20.690654326860702,20.842451239026076,24.917614496388875,15.231155126929895,17.199325347057041,18.060805258833199,16.9346538078969,16.999524283181248,17.822081909786792,13.12545949919993,14.590234831120529,15.220775850884401,15.052112615145093,14.260692816676038,17.866193832980152,13.032046014790469,15.78385157635255,16.027764563421702,16.327466159235392,15.520477446698091,17.787051853133242,13.105998356614625,22.067205812394587,31.718635125200016,40.407386584785712,24.214418544306533,37.379232798512305,24.3973532846084,15.468581066470612,20.285862561086365,24.981187562167541,17.850624918911905,29.609047268952988,19.628075941703067,14.945725035678763,20.70881805994032,23.621502400207586,15.168879470656922,21.347143536738315,15.733252605630756,19.47627902953769,22.926090905159366,28.07680664273667,21.182372529516066,38.073346884054843,24.111923193357264,28.053453271634304,34.096786749124249,41.179345240669463,29.187389179604722,45.386844267612332,23.525494096786748,15.071573757730398,16.553215413224926,19.118194005968085,16.756908705617782,24.65813259525148,16.514293128054319,17.251221727284523,23.607230895645031,28.098862604333348,19.713704969078407,28.533494788738487,19.888855252346147,15.488042209055919,16.234052674825932,18.424079920425548,14.025861696146695,20.528478138649831,14.687540544047053,14.496821346711066,14.514985079790684,15.059897072179215,16.725770877481295,20.702331012411882,17.696233187735157,10.434632184405137,11.19750897374908,11.096311032305497,11.883838602257493,15.534748951260649,12.960688491977685,22.782078450028109,27.245167149591317,27.421614842364747,28.996669982268738,42.509189983998617,26.292868572417074,16.631059983566146,17.331661116637115,18.53176490939757,22.547247329498767,38.027937551355791,28.603554902045584,14.365782986636681,15.515287808675344,15.420576914760197,15.833153137568655,21.299139385027893,20.377978635990139,15.952514812091856,17.098127405613457,17.440643515114822,17.187648661505861,24.079487955715088,17.168187518920554,14.075163257362799,16.038143839467196,16.272974959996539,17.331661116637115,21.857025472473296,17.863599013968773,15.194827660770661,16.943735674436709,18.334558664533148,20.854127924577263,28.075509233230985,23.003935475500583,15.987544868745404,17.380962677853219,17.126670414738573,20.479176577433723,28.866929031700039,25.709034294857936,13.963586039873718,14.431950871426718,15.377762401072525,17.768888120053624,23.395753146218052,21.886865891104094,14.791333304502011,13.621069930372357,13.653505168014531,15.477662933010423,19.901829347403016,19.223284175928729,14.129654456601653,16.113393590797042,16.075768715132121,18.543441594948753,21.544349781602733,14.691432772564113,29.167928037019418,33.480517233922932,37.08472084072136,38.190113739566669,46.239242312848681,27.291873891796048,13.74821606192968,15.829260909051595,16.919084893828657,16.820481771396445,20.691951736366388,16.925571941357092,15.961596678631665,18.412403234874368,19.665700817367988,20.18985425766553,23.957531462180512,20.401332007092506,11.769666565757039,14.079055485879859,14.812091856593003,14.437140509449467,18.421485101414177,14.905505341002465,15.048220386628032,15.733252605630756,16.222375989274749,17.316092202568871,21.713013017342039,16.300220559615965,12.742723695022272,14.042728019720624,16.138044371405094,16.647926307140075,21.253730052328848,16.291138693076157,13.234441897677637,14.535743631881676,15.495826666090039,16.532456861133937,20.433767244734682,15.729360377113697,20.345543398347964,22.684772737101589,25.014920209315399,27.653851143882715,34.011157721748909,21.466505211261513,10.023353371102365,10.134930588591446,10.237425939540717,10.443714050944946,11.853998183626691,11.158586688578472,14.411192319335726,15.617783159624615,15.447822514379622,16.274272369502228,17.20062275656273,14.306102149375082,10.525450849803226,11.450503827358041,13.112485404143062,11.709985728495438,11.571162911386931,11.07295766120313,12.862085369545474,15.704709596505644,18.529170090386195,15.685248453920339,15.506205942135537,13.068373480949704,12.946416987415128,15.866885784716516,16.272974959996539,14.359295939108247,13.321368334558665,11.175453012152403,11.336331790857587,12.871167236085283,14.520174717813433,14.652510487393505,14.304804739869393,11.421960818232929,12.6103879254422,15.895428793841631,17.979068459974918,17.759806253513815,16.240539722354367,12.675258400726548,11.540025083250443,14.818578904121438,14.084245123902608,13.846819184361891,14.208796436448559,11.511482074125329,14.67586385849587,18.470786662630282,17.297928469489253,16.73225792500973,21.658521818103189,15.798123080915108,20.685464688837953,25.619513038965533,25.686978333261255,20.056221078579767,15.739739653159191,18.483760757687151,18.529170090386195,21.441854430653464,20.3221900272456,17.312199974051808,15.888941746313193,16.38455217748562,16.644034078623015,18.626475803312719,18.307313064913721,16.919084893828657,16.331358387752452,15.74492929118194,19.113004367945337,21.793452406694634,20.671193184275396,18.596635384681917,15.864290965705141,16.960601998010638,13.906500021623492,14.618777840245642,14.594127059637589,13.948017125805475,10.810880941054361,10.542317173377157,10.975651948276608,11.232539030402629,11.421960818232929,10.670760714440167,10,10.653894390866236,13.720970462310254,15.340137525407602,15.643731349738356,15.449119923885309,14.677161268001557,13.521169398434459,14.46049388055183,15.800717899926481,15.305107468754056,15.367383125027029,15.194827660770661,13.540630541019764,36.576136314492061,40.08173679885828,44.228257579033858,47.732560653894396,62.074125329758253,26.364226095229856,18.965099684297023,19.89663970938027,20.466202482376854,21.720797474376162,22.449941616572243,12.799809713272499,14.430653461921031,15.445227695368249,15.964191497643039,17.147428966829565,18.527872680880506,12.244518444838473,26.717121480776715,27.661635600916838,28.184491631708688,27.146564027159105,28.850062708126107,12.576655278294339,37.50248670155257,38.29001427150456,38.982830947541409,40.298404186308005,45.964191497643036,21.498940448903689,13.535440902997015,14.913289798036587,15.188340613242225,15.682653634908966,16.786749124248583,11.680145309864637,19.599532932577951,20.781472992258792,21.413311421528348,22.291657656878435,24.226095229857716,16.494831985469013,36.192103100808716,39.32145482852571,40.879643644855769,38.815465121307788,45.890239155818882,31.229511741556028,17.41469532500108,18.464299615101844,19.423085239804522,18.295636379362541,19.308913203304069,13.605501016304112,18.775677896466721,18.65242399342646,19.883665614323402,18.795139039052025,20.807421182372529,13.916879297668988,15.895428793841631,16.16658738053021,15.499718894607101,15.502313713618475,18.513601176317952,14.469575747091641,18.718591878216493,20.224884314319077,20.6309734895991,21.009817065259696,23.385373870172558,17.031959520823424,18.511006357306577,19.050728711672363,17.850624918911905,17.988150326514727,18.421485101414177,13.243523764217446,18.710807421182373,26.082688232495784,22.370799636725337,20.270293647018121,20.733468840548372,14.803009990053194]},\"error_y\":{\"width\":[]},\"error_x\":{\"width\":[]},\"frame\":null},{\"x\":[98.02949974473222,105.11159291657839],\"y\":[6.1774973714727786,19.847325205810534],\"type\":\"scatter3d\",\"mode\":\"markers\",\"opacity\":0,\"hoverinfo\":\"none\",\"showlegend\":false,\"marker\":{\"colorbar\":{\"title\":\"\",\"ticklen\":2,\"len\":0.5,\"lenmode\":\"fraction\",\"y\":1,\"yanchor\":\"top\"},\"cmin\":846,\"cmax\":70215,\"colorscale\":[[\"0\",\"rgba(68,1,84,1)\"],[\"0.0416666666666667\",\"rgba(70,19,97,1)\"],[\"0.0833333333333333\",\"rgba(72,32,111,1)\"],[\"0.125\",\"rgba(71,45,122,1)\"],[\"0.166666666666667\",\"rgba(68,58,128,1)\"],[\"0.208333333333333\",\"rgba(64,70,135,1)\"],[\"0.25\",\"rgba(60,82,138,1)\"],[\"0.291666666666667\",\"rgba(56,93,140,1)\"],[\"0.333333333333333\",\"rgba(49,104,142,1)\"],[\"0.375\",\"rgba(46,114,142,1)\"],[\"0.416666666666667\",\"rgba(42,123,142,1)\"],[\"0.458333333333333\",\"rgba(38,133,141,1)\"],[\"0.5\",\"rgba(37,144,140,1)\"],[\"0.541666666666667\",\"rgba(33,154,138,1)\"],[\"0.583333333333333\",\"rgba(39,164,133,1)\"],[\"0.625\",\"rgba(47,174,127,1)\"],[\"0.666666666666667\",\"rgba(53,183,121,1)\"],[\"0.708333333333333\",\"rgba(79,191,110,1)\"],[\"0.75\",\"rgba(98,199,98,1)\"],[\"0.791666666666667\",\"rgba(119,207,85,1)\"],[\"0.833333333333333\",\"rgba(147,214,70,1)\"],[\"0.875\",\"rgba(172,220,52,1)\"],[\"0.916666666666667\",\"rgba(199,225,42,1)\"],[\"0.958333333333333\",\"rgba(226,228,40,1)\"],[\"1\",\"rgba(253,231,37,1)\"]],\"showscale\":true,\"color\":[846,70215],\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"z\":[2017,2022],\"frame\":null}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n# \n\n# **Conclusion**\n\nThis comprehensive spatial analysis of drug abuse cases in Thailand from 2017 to 2022 aims to provide valuable insights into the complex and dynamic nature of this critical social issue. Through a combination of traditional spatial statistical methods and advanced visualization techniques, we have uncovered significant patterns and trends that have important implications for policy-making and intervention strategies.\n\nKey findings from our analysis include:\n\n1.  **Spatial Dependency**: The consistent positive spatial autocorrelation observed across all years indicates that drug abuse cases in Thailand are not randomly distributed but tend to cluster geographically. This spatial dependency strengthened over time, highlighting the increasing importance of location in understanding and addressing drug abuse.\n\n2.  **Regional Variations**: We identified persistent hotspots in the southern region and the central region. However, data from 2022 suggests an improvement in those areas. Conversely, the western region consistently maintained lower drug abuse rates, offering potential insights into effective control measures.\n\n3.  **Border Influences**: Provinces bordering neighboring countries often showed significant clustering of drug abuse cases, highlighting the potential influence of cross-border activities on drug-related issues.\n\n# **References**\n\n-   Utilized Claude AI to clarify code concepts and refining responses.\n\n-   Seniors's learning from <https://is415-gaa-matthew-ho.netlify.app/takehomeex/takehomeex2/the2>\n",
    "supporting": [
      "Takehome_Ex2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"../../site_libs/plotly-binding-4.10.4/plotly.js\"></script>\n<script src=\"../../site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"../../site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"../../site_libs/crosstalk-1.2.1/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/crosstalk-1.2.1/js/crosstalk.min.js\"></script>\n<link href=\"../../site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/plotly-main-2.11.1/plotly-latest.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}