{
  "hash": "fc39514a2661efa7caf9e8c82851d7bb",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Geospatial Analytics for Social Good: Unveiling the Spatial and Temporal Dynamics of Armed Conflict in Myanmar (2021-2024)\"\nauthor: \"Chong Zhi Cheng\"\ndate: \"September 16, 2024\"\ndate-modified: \"last-modified\"\nexecute:\n  eval: true\n  echo: true\n  freeze: true\n  warning: false\n---\n\n\nThe application of geospatial analytics to complex societal challenges has emerged as a powerful tool for understanding and addressing global issues. This study leverages advanced spatial and spatio-temporal point pattern analysis techniques to examine the geographical distribution and evolution of armed conflict in Myanmar following the military coup of February 1, 2021.\n\nTo provide more context for this analysis, readers are encouraged to explore two key resources:\n\n1.  The International Institute for Strategic Studies (IISS) offers an interactive map of the conflict, along with a concise introduction to the situation in Myanmar. This resource can be accessed at <https://myanmar.iiss.org/>\n\n2.  For a comprehensive understanding of the conflict, the Special Advisory Council for Myanmar has published an in-depth report, available at <https://specialadvisorycouncil.org/>.\n\nThese resources complement our geospatial analysis by providing crucial background information and additional perspectives on the ongoing conflict in Myanmar.\n\n# Simplified Historical Context and Current Conflict\n\nMyanmar has a long history of political instability, but the current conflict stems from a military coup that occurred on February 1, 2021. This event marked a critical turning point in the country's fragile democratic transition.\n\n![](timeline.PNG)\n\n*Image source: The New York Times, \"What’s Happening in Myanmar’s Civil War?,\" April 20, 2024*\n\n<https://www.nytimes.com/interactive/2024/04/20/world/asia/myanmar-civil-war.html>\n\nOn 1 February 2021, the military in Myanmar seized power as the elected National League for Democracy (NLD) government was set to begin its second term, having won the November 2020 general election.\n\nAlleging the NLD had engaged in electoral fraud, the military set about arresting NLD officials and other activists. The public response to the coup was to take to the streets in a rejection of a return to military rule. The military responded to the demonstrations with excessive force, killing hundreds of peaceful protesters.\n\nAs military violence throughout the country increased, armed local defense forces emerged to protect communities. The coup has also set off a wave of renewed fighting in areas with ethnic armed groups. (*for more, see ACLED’s recent report: [Myanmar’s Spring Revolution](https://acleddata.com/2021/07/22/myanmars-spring-revolution/)*).\n\n## Situation Overview\n\nThe conflict in Myanmar presents a highly complex and nuanced scenario that defies simple categorization. While this report aims to provide a comprehensive analysis, it is important to acknowledge that the following overview represents a necessarily simplified version of the ongoing situation.\n\nIn the aftermath of the 2021 military coup, two primary opposition forces emerged to challenge the ruling junta: the People's Defense Force and the Three Brotherhood Alliance. These groups, while often working in concert against the military government, maintain distinct identities and operational structures. It is crucial to note that despite their shared opposition to the junta, these entities are not formally allied nor do they constitute a single, unified force.\n\n![Map showing areas of control by various groups in Myanmar](indepthv2.PNG)\n\n*Source: Special Advisory Council for Myanmar*\n\nThe following is a simplified version of the map by New York Times.\n\n![](Myanmar_controlMap.PNG)\n\n*Image source: The New York Times, \"What’s Happening in Myanmar’s Civil War?,\" April 20, 2024*\n\nThe military junta maintains control over a central corridor stretching from Mandalay southward to Yangon, encompassing the country's traditional centers of power and economic activity. In contrast, resistance forces have established footholds in many peripheral regions, particularly in the country's border areas.\n\nKey contested zones have emerged at the intersection of several administrative regions, notably where Sagaing, Magway, Mandalay, and Shan states converge. Additionally, the outskirts of Yangon, Myanmar's largest city and former capital, have evolved into another significant battleground, underscoring the conflict's reach into urban centers.\n\n## Key Actors in the Myanmar Conflict\n\n### Myanmar Military ( Junta )\n\nThe Myanmar Military, also known as the Tatmadaw, seized power on February 1, 2021, overthrowing the democratically elected government. Currently, they maintain nominal control over the country, though their authority is increasingly challenged by various opposition forces.\n\n### People's Defense Force\n\nThe term \"People's Defense Force\" encompasses three distinct types of armed groups that have emerged since the coup:\n\n1.  **People's Defense Forces (PDFs)**: These are larger armed units formed or recognized by the National Unity Government (NUG), a shadow civilian government primarily composed of democratically elected lawmakers ousted in the coup. PDFs operate under joint command systems established by the NUG and several ethnic armed organizations (EAOs), many of which have been in conflict with the Tatmadaw for decades.\n\n2.  **Local Defense Forces (LDFs)**: These are local militias operating autonomously at the community level, often pursuing missions independent of the NUG's directives.\n\n3.  **People's Defense Teams (PaKhaPha/PDTs)**: These are localized guerrilla units formed for local defense and security purposes.\n\nThe key distinction lies in their operational scope and structure: PDFs are more regularized military units operating across townships and states/regions, while LDFs and PDTs function as self-defense or community security militias at a more localize level.\n\n<https://www.usip.org/publications/2022/11/understanding-peoples-defense-forces-myanmar>\n\n### Three Brotherhood Alliance and other Armed Forces\n\nThe Three Brotherhood Alliance is made up of various ethnic armed groups with the key ones being the Arakan Army, the Myanmar National Democratic Alliance Army (MNDAA), and the Ta’ang National Liberation Army (TNLA).\n\n-   **Arakan Army:** Founded in 2009, the Arakan Army is believed to have some 30,000 soldiers. It says it is fighting to restore the sovereignty of the multi-ethnic Arakanese in the western state of Rakhine. The group has recruited troops from the Rohingya, a minority mostly Muslim group from Rakhine, who were the target of a brutal military crackdown that is now the subject of a genocide case at the International Court of Justice.\n\n-   **Myanmar National Democratic Alliance Army (MNDAA):** The MNDAA operates near the Chinese border in northern Shan state. The group says it is fighting for autonomy for the Kokang people, a Han-speaking ethnic group. MNDAA controlled Shan for about 20 years as a special region of Myanmar, during which the narcotics trade boomed. Armed conflicts between the group and the military broke out in 2009 after it was ordered to become a border force, and give up control. MNDAA said earlier this month it had taken control of Laukkai, a town notorious for transnational human trafficking and online scams, that it lost in the 2009 conflict.\n\n-   **Ta’ang National Liberation Army (TNLA): T**he TNLA is the armed wing of the Palaung Self Liberation Front, a political organisation founded by Tar Aik Bong and Tar Bone Kyaw, both former fighters from the fringe Ta’ang minority group. Its latest incarnation was formed in 1992 and says it is fighting for “real federalism” in Myanmar. The TNLA claims to have 5,000 fighters, although it has been linked to forced recruitment campaigns in rural villages.\n\nWhile these three groups form the core of the alliance, they are also aligned with other ethnic armed groups. For the purposes of this analysis, these additional groups are considered under the umbrella of the Three Brotherhood Alliance.\n\n<https://www.aljazeera.com/news/2024/1/16/what-is-myanmars-three-brotherhood-alliance-thats-resisting-the-military>\n\n# Data Sources and Parameters\n\n## **Armed conflict data**\n\nThis study utilizes armed conflict data for Myanmar spanning from January 2021 to June 2024. The primary data source is the [Armed Conflict Location & Event Data (ACLED)](https://acleddata.com/), an independent, impartial, and international non-profit organization. ACLED is renowned for its comprehensive collection of data on violent conflicts and protests across all countries and territories worldwide.\n\n### Data Characteristics\n\n1.  **Time Frame**: The analysis covers a period of 3.5 years, from January 2021 to June 2024. This timeframe captures the evolution of the conflict from its inception following the military coup on February 1, 2021.\n\n2.  **Temporal Resolution**: The data is aggregated and analyzed on a quarterly basis, allowing for the identification of seasonal patterns and medium-term trends in conflict intensity and distribution.\n\n3.  **Spatial Coverage**: The dataset encompasses the entire territory of Myanmar, allowing for a comprehensive analysis of conflict patterns across different regions and administrative divisions.\n\n4.  **Data Currency**: The ACLED dataset used in this analysis was last updated on September 16, 2024.\n\n### ACLED Data Columns\n\n| Field Name       | Description                                                                                                                                                    |\n|-----------------------|--------------------------------------------------------------|\n| ISO              | A numeric code for each individual country                                                                                                                     |\n| EVENT_ID_CNTY    | An individual event identifier by number and country acronym                                                                                                   |\n| EVENT_ID_NO_CNTY | An individual event numeric identifier                                                                                                                         |\n| EVENT_DATE       | Recorded as Day / Month / Year                                                                                                                                 |\n| YEAR             | The year in which an event took place                                                                                                                          |\n| TIME_PRECISION   | A numeric code indicating the level of certainty of the date coded for the event (1-3)                                                                         |\n| EVENT_TYPE       | The type of event                                                                                                                                              |\n| SUB_EVENT_TYPE   | The type of sub-event                                                                                                                                          |\n| ACTOR1           | A named actor involved in the event                                                                                                                            |\n| ASSOC_ACTOR_1    | The named actor associated with or identifying with ACTOR1 in one specific event                                                                               |\n| INTER1           | A numeric code indicating the type of ACTOR1                                                                                                                   |\n| ACTOR2           | The named actor involved in the event. If a dyadic event, there will also be an \"Actor 1\"                                                                      |\n| ASSOC_ACTOR_2    | The named actor associated with or identifying with ACTOR2 in one specific event                                                                               |\n| INTER2           | A numeric code indicating the type of ACTOR2                                                                                                                   |\n| INTERACTION      | A numeric code indicating the interaction between types of ACTOR1 and ACTOR2. Coded as an interaction between actor types, and recorded as lowest joint number |\n| REGION           | The region of the world where the event took place                                                                                                             |\n| COUNTRY          | The country in which the event took place                                                                                                                      |\n| ADMIN1           | The largest sub-national administrative region in which the event took place                                                                                   |\n| ADMIN2           | The second largest sub-national administrative region in which the event took place                                                                            |\n| ADMIN3           | The third largest sub-national administrative region in which the event took place                                                                             |\n| LOCATION         | The location in which the event took place                                                                                                                     |\n| LATITUDE         | The latitude of the location                                                                                                                                   |\n| LONGITUDE        | The longitude of the location                                                                                                                                  |\n| GEO_PRECISION    | A numeric code indicating the level of certainty of the location coded for the event                                                                           |\n| SOURCE           | The source(s) used to code the event                                                                                                                           |\n| SOURCE SCALE     | The geographic scale of the sources used to code the event                                                                                                     |\n| NOTES            | A short description of the event                                                                                                                               |\n| FATALITIES       | Number or estimate of fatalities due to event. These are frequently different across reports                                                                   |\n\n## GIS Data\n\n-   [Geospatial data](http://geonode.themimu.info/layers/?limit=100&offset=0) on [Myanmar Information Management Unit, MIMU](http://www.themimu.info/)\n\n# Data Import and Initial Transformation & Analysis\n\nOur analysis begins with the crucial step of importing and preparing the data for geospatial analysis. We use two primary data sources:\n\n1.  **Armed Conflict Data**: Sourced from the Armed Conflict Location & Event Data (ACLED) project.\n\n2.  **Administrative Boundary Data**: Shapefiles obtained from the Myanmar Information Management Unit (MIMU).\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, raster, spatstat, tmap, tidyverse, viridis,classInt,maptools,OpenStreetMap,stars,spdep,prophet,tmaptools,sparr)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Import conflict data\nconflict_data <- read_csv(\"data/2021-01-01-2024-06-30-Myanmar.csv\") %>%\n  # Convert to sf object\n  st_as_sf(coords = c(\"longitude\", \"latitude\"), crs = 4326) %>%\n  # Create a quarter column and parse the date correctly\n  mutate(\n    event_date = dmy(event_date),\n    quarter = paste0(year(event_date), \"-Q\", quarter(event_date))\n  ) %>%\n  # Select relevant columns\n  select(\n    event_id_cnty, event_date, year, quarter, time_precision,\n    disorder_type, event_type, sub_event_type,\n    actor1, assoc_actor_1, inter1, actor2, assoc_actor_2, inter2, interaction,\n    civilian_targeting, region, country, admin1, admin2, admin3,\n    location, geo_precision, source, source_scale, notes, fatalities,\n    tags, timestamp, population_best\n  )\n\n# Import administrative boundary data\nadm0 <- st_read(dsn = \"data/adm0\", layer = \"mmr_polbnda_adm0_250k_mimu_1\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `mmr_polbnda_adm0_250k_mimu_1' from data source \n  `C:\\zcchong\\IS415\\Takehome_Ex\\Takehome_Ex1\\data\\adm0' using driver `ESRI Shapefile'\nSimple feature collection with 1 feature and 2 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 92.1721 ymin: 9.696844 xmax: 101.17 ymax: 28.54554\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nadm1 <- st_read(dsn = \"data/adm1\", layer = \"mmr_polbnda_adm1_250k_mimu_1\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `mmr_polbnda_adm1_250k_mimu_1' from data source \n  `C:\\zcchong\\IS415\\Takehome_Ex\\Takehome_Ex1\\data\\adm1' using driver `ESRI Shapefile'\nSimple feature collection with 15 features and 6 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 92.1721 ymin: 9.696844 xmax: 101.17 ymax: 28.54554\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nadm2 <- st_read(dsn = \"data/adm2\", layer = \"mmr_polbnda_adm2_250k_mimu\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `mmr_polbnda_adm2_250k_mimu' from data source \n  `C:\\zcchong\\IS415\\Takehome_Ex\\Takehome_Ex1\\data\\adm2' using driver `ESRI Shapefile'\nSimple feature collection with 80 features and 7 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 92.1721 ymin: 9.696844 xmax: 101.17 ymax: 28.54554\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nadm3 <- st_read(dsn = \"data/adm3\", layer = \"mmr_polbnda_adm3_250k_mimu_1\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `mmr_polbnda_adm3_250k_mimu_1' from data source \n  `C:\\zcchong\\IS415\\Takehome_Ex\\Takehome_Ex1\\data\\adm3' using driver `ESRI Shapefile'\nSimple feature collection with 330 features and 9 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 92.1721 ymin: 9.696844 xmax: 101.17 ymax: 28.54554\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\n# Ensure all sf objects have the same CRS\nadm0 <- st_transform(adm0, 4326)\nadm1 <- st_transform(adm1, 4326)\nadm2 <- st_transform(adm2, 4326)\nadm3 <- st_transform(adm3, 4326)\n\n# Create a list of all administrative boundaries\nadmin_boundaries <- list(adm0 = adm0, adm1 = adm1, adm2 = adm2, adm3 = adm3)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nconflict_data\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 42608 features and 30 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 92.1837 ymin: 9.9824 xmax: 100.3576 ymax: 27.5053\nGeodetic CRS:  WGS 84\n# A tibble: 42,608 × 31\n   event_id_cnty event_date  year quarter time_precision disorder_type         \n   <chr>         <date>     <dbl> <chr>            <dbl> <chr>                 \n 1 MMR64313      2024-06-30  2024 2024-Q2              1 Political violence    \n 2 MMR64320      2024-06-30  2024 2024-Q2              1 Political violence    \n 3 MMR64321      2024-06-30  2024 2024-Q2              1 Political violence    \n 4 MMR64322      2024-06-30  2024 2024-Q2              1 Strategic developments\n 5 MMR64323      2024-06-30  2024 2024-Q2              1 Political violence    \n 6 MMR64324      2024-06-30  2024 2024-Q2              1 Strategic developments\n 7 MMR64325      2024-06-30  2024 2024-Q2              1 Political violence    \n 8 MMR64326      2024-06-30  2024 2024-Q2              1 Political violence    \n 9 MMR64328      2024-06-30  2024 2024-Q2              1 Political violence    \n10 MMR64330      2024-06-30  2024 2024-Q2              1 Political violence    \n# ℹ 42,598 more rows\n# ℹ 25 more variables: event_type <chr>, sub_event_type <chr>, actor1 <chr>,\n#   assoc_actor_1 <chr>, inter1 <dbl>, actor2 <chr>, assoc_actor_2 <chr>,\n#   inter2 <dbl>, interaction <dbl>, civilian_targeting <chr>, region <chr>,\n#   country <chr>, admin1 <chr>, admin2 <chr>, admin3 <chr>, location <chr>,\n#   geo_precision <dbl>, source <chr>, source_scale <chr>, notes <chr>,\n#   fatalities <dbl>, tags <chr>, timestamp <dbl>, population_best <dbl>, …\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a map of Myanmar showing the admin1 regions\n# Create the plot\np <- ggplot() +\n  geom_sf(data = adm1, aes(fill = ST)) +\n  coord_sf(expand = FALSE, crs = st_crs(4326)) +\n  theme_minimal() +\n  theme(legend.position = \"bottom\",\n        legend.title = element_blank()) + \n  labs(title = \"Myanmar ADM1 Boundaries\",\n       subtitle = \"First-level administrative divisions\",\n       caption = \"Data source: MIMU\") +\n  scale_fill_discrete(name = \"States\") +  # This ensures the legend shows state names\n  guides(fill = guide_legend(nrow = 3, byrow = FALSE))  # Set max 3 per column, then side by side\n\n# Display the plot\nprint(p)\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n## Exploratory Data Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a custom color palette for event types\nevent_types <- unique(conflict_data$event_type)\nevent_colors <- setNames(viridis(length(event_types)), event_types)\n\n\n# 1. Overview map of conflict events\noverview_map <- ggplot() +\n  geom_sf(data = adm1, fill = \"white\", color = \"gray\") +\n  geom_sf(data = conflict_data, aes(color = event_type), size = 0.5, alpha = 0.6) +\n  theme_minimal() +\n  labs(title = \"Overview of Conflict Events in Myanmar\",\n       color = \"Event Type\") +\n  theme(legend.position = \"bottom\")\n\n# 2. Temporal trend of events\ntemporal_trend <- conflict_data %>%\n  count(event_date) %>%\n  ggplot(aes(x = event_date, y = n)) +\n  geom_line() +\n  geom_smooth(method = \"loess\", se = FALSE, color = \"red\") +\n  theme_minimal() +\n  labs(title = \"Temporal Trend of Conflict Events\",\n       x = \"Date\", y = \"Number of Events\")\n\n# 3. Distribution of event types\nevent_type_dist <- conflict_data %>%\n  count(event_type) %>%\n  ggplot(aes(x = reorder(event_type, n), y = n, fill = event_type)) +\n  geom_bar(stat = \"identity\") +\n  coord_flip() +\n  scale_fill_manual(values = event_colors) +\n  theme_minimal() +\n  labs(title = \"Distribution of Event Types\",\n       x = \"Event Type\", y = \"Number of Events\") +\n  theme(legend.position = \"none\")\n\n# 4. Events heatmap\nevents_heatmap <- ggplot() +\n  geom_sf(data = adm1, fill = \"white\", color = \"gray\") +\n  stat_density_2d(data = conflict_data, \n                  aes(x = st_coordinates(geometry)[,1], \n                      y = st_coordinates(geometry)[,2],\n                      fill = ..level..),\n                  geom = \"polygon\", \n                  alpha = 0.5) +\n  scale_fill_viridis() +\n  theme_minimal() +\n  labs(title = \"Heatmap of Conflict Events\",\n       fill = \"Density\")\n\n\n# 5. Administrative region comparison\nadmin_comparison <- conflict_data %>%\n  st_drop_geometry() %>%\n  count(admin1) %>%\n  top_n(10, n) %>%\n  ggplot(aes(x = reorder(admin1, n), y = n, fill = admin1)) +\n  geom_bar(stat = \"identity\") +\n  coord_flip() +\n  theme_minimal() +\n  labs(title = \"Top 10 Administrative Regions by Number of Events\",\n       x = \"Administrative Region\", y = \"Number of Events\") +\n  theme(legend.position = \"none\")\n\n#Event type distribution for top 5 regions\ntop_5_regions <- conflict_data %>%\n  st_drop_geometry() %>%\n  count(admin1) %>%\n  top_n(5, n) %>%\n  pull(admin1)\n\nevent_type_by_region <- conflict_data %>%\n  st_drop_geometry() %>%\n  filter(admin1 %in% top_5_regions) %>%\n  count(admin1, event_type) %>%\n  group_by(admin1) %>%\n  mutate(prop = n / sum(n)) %>%\n  ungroup()\n\n# 6. Event type distributions among the top 5 regions.\nevent_type_pies <- ggplot(event_type_by_region, aes(x = \"\", y = prop, fill = event_type)) +\n  geom_bar(width = 1, stat = \"identity\") +\n  coord_polar(\"y\", start = 0) +\n  facet_wrap(~ admin1, ncol = 3) +\n  scale_fill_manual(values = event_colors) +\n  theme_minimal() +\n  theme(axis.text = element_blank(),\n        axis.title = element_blank(),\n        panel.grid = element_blank(),\n        strip.text = element_text(size = 12, face = \"bold\")) +\n  labs(title = \"Event Type Distribution in Top 5 Regions\",\n       fill = \"Event Type\")\n```\n:::\n\n\nOur analysis examines conflict events in Myanmar from January 2021 to June 2024. During this period, there was around 42,000 conflict events across the country. These events range from battles, violence against civilians to armed clashes, providing insight into the complex security situation in Myanmar.\n\n\n::: {.cell}\n\n```{.r .cell-code}\noverview_map\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nThis map shows the distribution of conflict events across Myanmar. Each point represents an individual event, with colors indicating different types of events. Notice how events are not evenly distributed but tend to cluster in certain areas.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntemporal_trend\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nThis graph shows how the number of conflict events has changed over time. Notice how the conflict in Myanmar shows a distinct pattern of escalation and stabilization.\n\nThe conflict intensity gradually increased from the beginning of 2021 before reaching its apex in the third to fourth quarter of 2021. Following the peak, the conflict settled into a relatively consistent level of activity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nevent_type_dist\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nevents_heatmap\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nThe heatmap reveals areas of high conflict concentration. Brighter areas indicate 'hotspots' where many events have occurred. The conflict is not evenly distributed across Myanmar. \\*\n\nKey hotspots include:\n\n1\\. Northern/Central Regions: Sagaing, Magway, Mandalay, and Shan\n\n2\\. Southern Region: Yangon\n\nPossible reasons for these hotspots:\n\n1.  Northern/Central Regions (Sagaing, Magway, Mandalay, and Shan):\n    -   The area represents a critical juncture between the military-controlled central corridor and the resistance-held peripheral regions.\n2.  Southern Region (Yangon):\n    -   Yangon, as Myanmar's largest city and former capital, is a crucial urban center with significant economic and political importance and is also a contested region.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nadmin_comparison\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nevent_type_pies\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nOur exploratory data analysis reveals clear patterns in the distribution of armed conflict across Myanmar from 2021 to 2024. The spatial distribution of fighting aligns closely with the geopolitical landscape of the country, particularly the contested areas where the Junta's held territory intersects with regions controlled or influenced by rebel forces, as observed in the map by the Special Advisory Council for Myanmar above.\n\nKey findings from our analysis include:\n\n1.  **Concentration in Contested Regions**: The majority of conflict events are clustered in areas where control is disputed between the Junta and rebel groups. This pattern underscores the strategic importance of these regions and the intensity of the struggle for territorial control.\n\n2.  **Hotspots in Northern/Central Regions**: The analysis identifies significant conflict activity in the following areas: Sagaing, Magway, Mandalay, and Shan.\n\n3.  **Southern Conflict Center**: Yangon also emerges as a notable a area of conflict.\n\n4.  **Relative Calm in Uncontested Areas**: Regions that fall squarely within the undisputed territory of either the Junta or rebel groups show notably less conflict activity. This pattern aligns with the expectation that areas of clear control experience fewer armed confrontations.\n\n# First-order Spatial-Temporal Patterns Analysis: Understanding Conflict Trends in Myanmar\n\nTo further investigate the spatial and temporal dynamics of conflict events in Myanmar, we employed a First-order Spatial-Temporal Point Patterns Analysis. This method allows us to visualize and quantify the distribution of conflict events across space and time, revealing patterns that may not be apparent from raw event data alone.\n\n**Temporal Segmentation**\n\nBuilding upon our initial analysis, we segmented the conflict event data into quarterly periods from Q1 2021 to Q2 2024. This temporal resolution provides a balance between granularity and the ability to discern broader trends, allowing us to track the evolution of conflict patterns over the study period.\n\n**Handling Spatial Data Challenges (Duplicates)**\n\nA common challenge in spatial point pattern analysis is the occurrence of multiple events at identical coordinates, often due to limitations in spatial precision of reporting. To address this, we applied a jittering technique:\n\n-   Each point was slightly displaced in a random direction.\n\n-   This process helps prevent underrepresentation of high-density areas in subsequent analyses.\n\n## Kernel Density Estimation (KDE)\n\nFor each quarter, we performed Kernel Density Estimation to visualize the spatial concentration of conflict events.\n\n**Standardization of Density Scales**\n\nTo ensure meaningful comparison of conflict intensity across different quarters, we standardized the density scales. This standardization ensures that color intensities represent the same conflict density across all temporal segments, facilitating direct visual comparison.\n\n**Visualization**\n\nAn animation was created to display the sequence of quarterly KDE maps, allowing for intuitive comprehension of temporal trends in conflict distribution.\n\nThis methodology enables us to:\n\n1.  Identify persistent conflict hotspots across the study period.\n\n2.  Detect emerging or dissipating areas of conflict.\n\n3.  Visualize the spatial evolution of conflict intensity over time.\n\n4.  Compare conflict patterns across different quarters on a standardized scale.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Function to create KDE for a specific quarter\ncreate_kde <- function(data, quarter, bw = NULL) {\n  quarter_data <- data %>% filter(quarter == !!quarter)\n  \n  # Convert sf object to ppp object\n  window <- as.owin(st_bbox(adm0))\n  ppp_obj <- as.ppp(st_coordinates(quarter_data), W = window)\n  \n  # Apply jittering to handle duplicated points\n  ppp_obj_jittered <- rjitter(ppp_obj, retry = TRUE, nsim = 1, drop = TRUE)\n  \n  # Compute default bandwidth if not provided\n  if (is.null(bw)) {\n    bw <- bw.diggle(ppp_obj_jittered)\n  }\n  \n  # Compute KDE\n  kde <- density.ppp(ppp_obj_jittered, sigma = bw.diggle, edge = TRUE)\n  \n  # Convert to raster\n  r <- raster(kde)\n  \n  # Mask the raster with Myanmar boundary\n  # Remove data outside of Myanmar.\n  r_masked <- mask(r, as(adm0, \"Spatial\"))\n  \n  return(r_masked)\n}\n\n# Get unique quarters\nquarters <- unique(conflict_data$quarter)\n\n# Create KDE for each quarter\nkde_layers <- lapply(quarters, function(q) {\n  tryCatch({\n    create_kde(conflict_data, q)\n  }, error = function(e) {\n    warning(paste(\"Error in quarter\", q, \":\", e$message))\n    return(NULL)\n  })\n})\n\n# Remove any NULL elements (quarters where KDE failed)\nkde_layers <- kde_layers[!sapply(kde_layers, is.null)]\n\n# Name the layers\nnames(kde_layers) <- quarters[!sapply(kde_layers, is.null)]\n\n# Print summary of KDE layers\nprint(summary(kde_layers))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        Length Class       Mode\n2024-Q2 16384  RasterLayer S4  \n2024-Q1 16384  RasterLayer S4  \n2023-Q4 16384  RasterLayer S4  \n2023-Q3 16384  RasterLayer S4  \n2023-Q2 16384  RasterLayer S4  \n2023-Q1 16384  RasterLayer S4  \n2022-Q4 16384  RasterLayer S4  \n2022-Q3 16384  RasterLayer S4  \n2022-Q2 16384  RasterLayer S4  \n2022-Q1 16384  RasterLayer S4  \n2021-Q4 16384  RasterLayer S4  \n2021-Q3 16384  RasterLayer S4  \n2021-Q2 16384  RasterLayer S4  \n2021-Q1 16384  RasterLayer S4  \n```\n\n\n:::\n:::\n\n\n## Visualization of the various KDE maps by quarter\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Function to get the lowest maximum density across all KDE layers\nget_lowest_max_density <- function(kde_layers) {\n  max_densities <- sapply(kde_layers, function(layer) {\n    max(values(layer), na.rm = TRUE)\n  })\n  return(c(0, min(max_densities)))\n}\n\n# Get the density range with the lowest maximum\ndensity_range <- get_lowest_max_density(kde_layers)\n\n# Function to plot a single KDE layer with fixed density scale\nplot_kde_layer <- function(kde_layer, quarter, admin_boundary, density_range) {\n  # Convert raster to data frame for ggplot\n  kde_df <- as.data.frame(kde_layer, xy = TRUE) %>%\n    rename(density = layer)\n  \n  # Create the plot\n  ggplot() +\n    geom_raster(data = kde_df, aes(x = x, y = y, fill = density)) +\n    geom_sf(data = admin_boundary, fill = NA, color = \"black\") +\n    scale_fill_viridis_c(option = \"plasma\", \n                         limits = density_range,\n                         oob = scales::squish) +\n    labs(title = paste(\"KDE for\", quarter),\n         x = \"Longitude\", y = \"Latitude\", fill = \"Density\") +\n    theme_minimal() +\n    coord_sf()\n}\n\n# Plot all KDE layers with fixed density scale\nkde_plots <- lapply(seq_along(kde_layers), function(i) {\n  plot_kde_layer(kde_layers[[i]], names(kde_layers)[i], adm0, density_range)\n})\n\n# Display the plots\nfor (plot in kde_plots) {\n  print(plot)\n}\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-13-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-13-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-13-4.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-13-5.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-13-6.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-13-7.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-13-8.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-13-9.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-13-10.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-13-11.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-13-12.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-13-13.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-13-14.png){width=672}\n:::\n:::\n\n\nThe maps above shows the \"heat\" of conflict events in Myanmar for a specific three-month period (quarter).\n\n-   Red areas are \"conflict hotspots\" with many events close together.\n\n-   The brighter the color, the more concentrated the conflict.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Function to convert a single KDE layer to a data frame\nkde_to_df <- function(kde_layer, quarter) {\n  df <- as.data.frame(kde_layer, xy = TRUE) %>%\n    rename(density = layer) %>%\n    mutate(quarter = quarter)\n  return(df)\n}\n\n# Convert all KDE layers to a single data frame\nkde_df <- map2_dfr(kde_layers, names(kde_layers), kde_to_df)\n\n# Create the base plot\np <- ggplot() +\n  geom_raster(data = kde_df, aes(x = x, y = y, fill = density)) +\n  geom_sf(data = adm0, fill = NA, color = \"white\", size = 0.5) +\n  scale_fill_viridis_c(option = \"plasma\", \n                       limits = density_range,\n                       oob = scales::squish) +\n  labs(title = \"Conflict Density in Myanmar: {closest_state}\",\n       x = \"Longitude\", y = \"Latitude\", fill = \"Density\") +\n  theme_minimal() +\n  theme(plot.title = element_text(size = 20, face = \"bold\"),\n        legend.position = \"bottom\") +\n  coord_sf()\n\n# The following code creates the animation, render it and saves it as a gif. It will be commented out for brevity.\n\n# Add animation\n#animated_plot <- p +\n# transition_states(quarter,\n#                    transition_length = 2,\n#                    state_length = 3) +\n#  ease_aes('cubic-in-out')\n\n# Render the animation\n#anim <- animate(animated_plot, nframes = 200, fps = 10, width = 800, height = 600, renderer = gifski_renderer())\n\n# Save the animation\n#anim_save(\"myanmar_conflict_density_slideshow_kde.gif\", anim)\n```\n:::\n\n\n## Animation of the Conflict Density in Myanmar over Time\n\n![](myanmar_conflict_density_slideshow_kde.gif)\n\nThis animation shows how conflict hotspots evolved in Myanmar from early 2021 to mid-2024. Each frame represents a three-month period (quarter), with warmer colors (red and orange) indicating areas of high conflict concentration and cooler colors (blue and green) showing areas of lower conflict activity.\n\nKey observations:\n\n1.  **Central Concentration**: Notice how the conflicts are consistently concentrated in the middle area of Myanmar throughout the entire period. This pattern supports our previous analysis and highlights the persistent nature of conflicts in this region.\n\n2.  **Relative Calm in Peripheries**: The peripheral areas, particularly the far north, far south and far east generally show lower conflict intensity.\n\n# Second-order Spatial-Temporal Patterns Analysis\n\nThe second-order spatial-temporal patterns analysis concentrates on a select group of key regions, strategically chosen to provide in-depth insights into the most critical areas of conflict, namely **Sagaing**, **Magway**, **Mandalay**,**Yangon**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Define the regions of interest\nregions_of_interest <- c(\"Sagaing\", \"Magway\", \"Mandalay\",\"Yangon\")\n\n# Extract the specified regions from adm1\nstudy_area <- adm1 %>%\n  filter(ST %in% regions_of_interest)\n\n# Print summary of the study area\nprint(summary(study_area))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    OBJECTID          ST              ST_PCODE            ST_RG          \n Min.   : 8.00   Length:4           Length:4           Length:4          \n 1st Qu.: 8.75   Class :character   Class :character   Class :character  \n Median :11.00   Mode  :character   Mode  :character   Mode  :character  \n Mean   :12.00                                                           \n 3rd Qu.:14.25                                                           \n Max.   :18.00                                                           \n    ST_MMR             PCode_V             geometry\n Length:4           Min.   :9.4   MULTIPOLYGON :4  \n Class :character   1st Qu.:9.4   epsg:4326    :0  \n Mode  :character   Median :9.4   +proj=long...:0  \n                    Mean   :9.4                    \n                    3rd Qu.:9.4                    \n                    Max.   :9.4                    \n```\n\n\n:::\n\n```{.r .cell-code}\n# Plot the study area to visualize it\nggplot() +\n  geom_sf(data = adm1, fill = \"lightgrey\", color = \"white\") +\n  geom_sf(data = study_area, aes(fill = ST), alpha = 0.7) +\n  theme_minimal() +\n  labs(title = \"Study Area: Selected Regions in Myanmar\",\n       fill = \"Region\") +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n## Central Regions Analysis\n\n### Sagaing\n\n#### G-Function\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract Sagaing region\nsagaing <- adm1 %>%\n  filter(ST == \"Sagaing\")\n\n# Print basic information about Sagaing\nprint(sagaing)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 1 feature and 6 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 93.94619 ymin: 21.57596 xmax: 97.0669 ymax: 27.37205\nGeodetic CRS:  WGS 84\n  OBJECTID      ST ST_PCODE  ST_RG         ST_MMR PCode_V\n1       13 Sagaing   MMR005 Region စစ်ကိုင်းတိုင်းဒေသကြီး     9.4\n                        geometry\n1 MULTIPOLYGON (((96.72824 27...\n```\n\n\n:::\n\n```{.r .cell-code}\n# Plot Sagaing to visualize it\nggplot() +\n  geom_sf(data = adm1, fill = \"lightgrey\", color = \"white\") +\n  geom_sf(data = sagaing, fill = \"red\", alpha = 0.7) +\n  theme_minimal() +\n  labs(title = \"Sagaing Region in Myanmar\")\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter conflict data for Sagaing and jitter the coordinates\nconflict_sagaing <- conflict_data %>%\n  st_join(sagaing) %>%\n  filter(!is.na(ST)) %>%\n  st_jitter()  # Small jitter amount, adjust if needed\n\n# Create observation window for Sagaing\nwindow_sagaing <- as.owin(st_bbox(sagaing))\n\n# Convert jittered conflict points to ppp object\nconflict_ppp_sagaing <- as.ppp(st_coordinates(conflict_sagaing), W = window_sagaing)\n\n# Compute G-function estimation\ng_est_sagaing <- Gest(conflict_ppp_sagaing, correction = \"border\")\n\n# Plot the G-function\nplot(g_est_sagaing, main = \"G-function for Conflict Events in Sagaing\")\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Print summary of G-function estimation\nsummary(g_est_sagaing)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       r                theo              rs        \n Min.   :0.00000   Min.   :0.0000   Min.   :0.0000  \n 1st Qu.:0.01929   1st Qu.:0.5130   1st Qu.:0.9789  \n Median :0.03859   Median :0.9438   Median :0.9946  \n Mean   :0.03859   Mean   :0.7383   Mean   :0.9428  \n 3rd Qu.:0.05788   3rd Qu.:0.9985   3rd Qu.:0.9970  \n Max.   :0.07718   Max.   :1.0000   Max.   :0.9975  \n```\n\n\n:::\n:::\n\n\nThis G-function plot provides strong evidence that conflict events in Sagaing are not randomly distributed but are instead highly clustered, particularly at very short distances. This could suggest that conflicts tend to occur in specific hotspots or that one conflict event might trigger others in very close proximity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Perform Monte Carlo test\nG_sagaing_env <- envelope(conflict_ppp_sagaing, fun = Gest, nsim = 999, rank = 1, global = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 999 simulations of CSR  ...\n1, 2, 3, ......10.........20.........30.........40.........50.........60..\n.......70.........80.........90.........100.........110.........120.........130\n.........140.........150.........160.........170.........180.........190........\n.200.........210.........220.........230.........240.........250.........260......\n...270.........280.........290.........300.........310.........320.........330....\n.....340.........350.........360.........370.........380.........390.........400..\n.......410.........420.........430.........440.........450.........460.........470\n.........480.........490.........500.........510.........520.........530........\n.540.........550.........560.........570.........580.........590.........600......\n...610.........620.........630.........640.........650.........660.........670....\n.....680.........690.........700.........710.........720.........730.........740..\n.......750.........760.........770.........780.........790.........800.........810\n.........820.........830.........840.........850.........860.........870........\n.880.........890.........900.........910.........920.........930.........940......\n...950.........960.........970.........980.........990........\n999.\n\nDone.\n```\n\n\n:::\n\n```{.r .cell-code}\n# Plot the results\nplot(G_sagaing_env, main = \"Monte Carlo Test: G-function for Conflict Events in Sagaing\")\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Print the results of the test\nprint(G_sagaing_env)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimultaneous critical envelopes for G(r)\nand observed value for 'conflict_ppp_sagaing'\nEdge correction: \"km\"\nObtained from 999 simulations of CSR\nEnvelope based on maximum deviation of G(r) from null value for CSR (known \nexactly)\nAlternative: two.sided\nSignificance level of simultaneous Monte Carlo test: 1/1000 = 0.001\n...........................................................\n     Math.label     Description                            \nr    r              distance argument r                    \nobs  hat(G)[obs](r) observed value of G(r) for data pattern\ntheo G[theo](r)     theoretical value of G(r) for CSR      \nlo   hat(G)[lo](r)  lower critical boundary for G(r)       \nhi   hat(G)[hi](r)  upper critical boundary for G(r)       \n...........................................................\nDefault plot formula:  .~r\nwhere \".\" stands for 'obs', 'theo', 'hi', 'lo'\nColumns 'lo' and 'hi' will be plotted as shading (by default)\nRecommended range of argument r: [0, 0.009949]\nAvailable range of argument r: [0, 0.009949]\n```\n\n\n:::\n:::\n\n\nThis Monte Carlo test provides strong evidence that conflict events in Sagaing are significantly more clustered than would be expected by chance, particularly at shorter distances.\n\n#### L-Function\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate L-function\nL_sagaing <- Lest(conflict_ppp_sagaing, correction = \"Ripley\")\n\n# Plot L-function\nplot(L_sagaing, . - r ~ r, main = \"L-function for Conflict Events in Sagaing\")\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\nThis L-function analysis strongly supports the conclusion that conflict events in Sagaing are significantly clustered, with the clustering being particularly intense at shorter distances but persisting across larger scales as well. This pattern deviates markedly from what would be expected if the events were randomly distributed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Perform Monte Carlo test with L-function\nL_sagaing_env <- envelope(conflict_ppp_sagaing, fun = Lest, nsim = 999, rank = 1, global = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 999 simulations of CSR  ...\n1, 2, 3, ......10 [4:53 remaining] .........20 [4:55 remaining] ...\n......30 [4:50 remaining] .........40 [4:48 remaining] .........50 [4:43 remaining] ..\n.......60 [4:39 remaining] .........70 [4:35 remaining] .........80 [4:33 remaining] .\n........90 [4:30 remaining] .........100 [4:26 remaining] .........110\n [4:24 remaining] .........120 [4:21 remaining] .........130 [4:17 remaining] .........\n140 [4:14 remaining] .........150 [4:11 remaining] .........160 [4:08 remaining] ........\n.170 [4:05 remaining] .........180 [4:02 remaining] .........190 [3:59 remaining] .......\n..200 [3:56 remaining] .........210 [3:53 remaining] .........220 [3:50 remaining] ......\n...230 [3:46 remaining] .........240 [3:43 remaining] .........250 [3:40 remaining] .....\n....260 [3:37 remaining] .........270 [3:34 remaining] .........280 [3:31 remaining] ....\n.....290 [3:28 remaining] .........300 [3:25 remaining] .........310 [3:22 remaining] ...\n......320 [3:19 remaining] .........330 [3:16 remaining] .........340 [3:13 remaining] ..\n.......350 [3:10 remaining] .........360 [3:07 remaining] .........370 [3:05 remaining] .\n........380 [3:02 remaining] .........390 [2:59 remaining] .........400\n [2:56 remaining] .........410 [2:53 remaining] .........420 [2:50 remaining] .........\n430 [2:47 remaining] .........440 [2:44 remaining] .........450 [2:41 remaining] ........\n.460 [2:38 remaining] .........470 [2:36 remaining] .........480 [2:32 remaining] .......\n..490 [2:30 remaining] .........500 [2:27 remaining] .........510 [2:24 remaining] ......\n...520 [2:21 remaining] .........530 [2:18 remaining] .........540 [2:15 remaining] .....\n....550 [2:12 remaining] .........560 [2:09 remaining] .........570 [2:06 remaining] ....\n.....580 [2:03 remaining] .........590 [2:00 remaining] .........600 [1:57 remaining] ...\n......610 [1:54 remaining] .........620 [1:51 remaining] .........630 [1:49 remaining] ..\n.......640 [1:46 remaining] .........650 [1:43 remaining] .........660 [1:40 remaining] .\n........670 [1:37 remaining] .........680 [1:34 remaining] .........690\n [1:31 remaining] .........700 [1:28 remaining] .........710 [1:25 remaining] .........\n720 [1:22 remaining] .........730 [1:19 remaining] .........740 [1:16 remaining] ........\n.750 [1:13 remaining] .........760 [1:10 remaining] .........770 [1:07 remaining] .......\n..780 [1:04 remaining] .........790 [1:02 remaining] .........800 [59 sec remaining] ......\n...810 [56 sec remaining] .........820 [53 sec remaining] .........830 [50 sec remaining] .....\n....840 [47 sec remaining] .........850 [44 sec remaining] .........860 [41 sec remaining] ....\n.....870 [38 sec remaining] .........880 [35 sec remaining] .........890 [32 sec remaining] ...\n......900 [29 sec remaining] .........910 [26 sec remaining] .........920 [23 sec remaining] ..\n.......930 [20 sec remaining] .........940 [17 sec remaining] .........950 [14 sec remaining] .\n........960 [11 sec remaining] .........970 [9 sec remaining] .........980\n [6 sec remaining] .........990 [3 sec remaining] ........\n999.\n\nDone.\n```\n\n\n:::\n\n```{.r .cell-code}\n# Plot Monte Carlo test results\nplot(L_sagaing_env, . - r ~ r, main = \"Monte Carlo Test: L-function for Conflict Events in Sagaing\")\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Print the results of the test\nprint(L_sagaing_env)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimultaneous critical envelopes for L(r)\nand observed value for 'conflict_ppp_sagaing'\nEdge correction: \"iso\"\nObtained from 999 simulations of CSR\nEnvelope based on maximum deviation of L(r) from null value for CSR (known \nexactly)\nAlternative: two.sided\nSignificance level of simultaneous Monte Carlo test: 1/1000 = 0.001\n...........................................................\n     Math.label     Description                            \nr    r              distance argument r                    \nobs  hat(L)[obs](r) observed value of L(r) for data pattern\ntheo L[theo](r)     theoretical value of L(r) for CSR      \nlo   hat(L)[lo](r)  lower critical boundary for L(r)       \nhi   hat(L)[hi](r)  upper critical boundary for L(r)       \n...........................................................\nDefault plot formula:  .~r\nwhere \".\" stands for 'obs', 'theo', 'hi', 'lo'\nColumns 'lo' and 'hi' will be plotted as shading (by default)\nRecommended range of argument r: [0, 0.7193]\nAvailable range of argument r: [0, 0.7193]\n```\n\n\n:::\n:::\n\n\n#### L-Function over time\n\nTo maintain brevity and avoid overwhelming the report with excessive imagery, the code segment demonstrating the temporal evolution of the L-Function has been set to `eval:false`. This setting suppresses the generation and display of multiple images in the final report.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract Sagaing region\nsagaing <- adm1 %>%\n  filter(ST == \"Sagaing\")\n\n# Filter conflict data for Sagaing and jitter the coordinates\nconflict_sagaing <- conflict_data %>%\n  st_join(sagaing) %>%\n  filter(!is.na(ST)) %>%\n  st_jitter()\n\n# Create observation window for Sagaing\nwindow_sagaing <- as.owin(st_bbox(sagaing))\n\n# Function to analyze a single quarter\nanalyze_quarter <- function(data, quarter) {\n  conflict_ppp <- as.ppp(st_coordinates(data), W = window_sagaing)\n  \n  tryCatch({\n    g_est <- Gest(conflict_ppp, correction = \"border\")\n    l_est <- Lest(conflict_ppp, correction = \"Ripley\")\n    \n    g_plot <- plot(g_est, main = paste(\"G-function for Sagaing -\", quarter))\n    l_plot <- plot(l_est, . - r ~ r, main = paste(\"L-function for Sagaing -\", quarter))\n    \n    return(list(g_plot = g_plot, l_plot = l_plot, message = NULL))\n  }, error = function(e) {\n    print(paste(\"Lack of entry within the time period:\", quarter))\n  })\n}\n\n# Perform analysis for each quarter\nquarterly_results <- conflict_sagaing %>%\n  group_by(quarter) %>%\n  group_map(~ analyze_quarter(.x, .y$quarter))\n```\n:::\n\n\n#### **Spatio-Temporal kernel density estimation**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract Sagaing region\nsagaing <- adm1 %>%\n  filter(ST == \"Sagaing\")\n\n# Filter conflict data for Sagaing and jitter the coordinates\nconflict_sagaing <- conflict_data %>%\n  st_join(sagaing) %>%\n  filter(!is.na(ST)) %>%\n  st_jitter()\n\n# Create observation window for Sagaing\nwindow_sagaing <- as.owin(st_bbox(sagaing))\n\n# Prepare data for STKDE\ncoords <- st_coordinates(conflict_sagaing)\nt <- as.numeric(conflict_sagaing$event_date - min(conflict_sagaing$event_date))\n\n# Create ppp object\nppp_sagaing <- as.ppp(coords, W = window_sagaing)\n\n# Compute bandwidths\nh_spatial <- bw.ppl(ppp_sagaing)\nh_temporal <- bw.SJ(t)\n\n# Perform STKDE\nstkde_result <- spattemp.density(ppp_sagaing, t, tlim = range(t),\n                                 h = c(h_spatial, h_temporal))\n\n# Commented out the plotting to save space.\n# Plot STKDE result\n# plot(stkde_result, main = \"STKDE for Sagaing Region\")\n\n# Extract and plot time slices\n#times <- seq(min(t), max(t), length.out = 5)\n#par(mfrow = c(2, 3), mar = c(2, 2, 2, 2))\n#for(time in times) {\n#  slice <- cut(stkde_result, t = time)\n#  plot(slice, main = paste(\"STKDE at time\", round(time, 2)))\n#}\n\n# Print summary of STKDE result\nprint(summary(stkde_result))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatiotemporal Kernel Density Estimate\n\nBandwidths\n  h = 0.0499 (spatial)\n  lambda = 21.4746 (temporal)\n\nNo. of observations\n  11128 \n\nSpatial bound\n  Type: rectangle\n  2D enclosure: [93.94619, 97.0669] x [21.57596, 27.37205]\n\nTemporal bound\n  [0, 1264]\n\nEvaluation\n  128 x 128 x 1265 trivariate lattice\n  Density range: [0, 0.005739644]\nNULL\n```\n\n\n:::\n:::\n\n\nThe spatiotemporal analysis of conflict events in Sagaing reveals a highly clustered pattern of violence, both in space and time.\n\nOver a period of about 3.5 years, 11,128 conflict events were recorded within a specific geographic area, averaging nearly 9 incidents per day.\n\nStatistical tests, including G-function and L-function analyses, consistently demonstrate that this clustering is significantly more pronounced than would be expected from random distribution, with particularly intense clustering at shorter distances but persisting across larger scales.\n\nThe kernel density estimation further suggests the presence of specific spatiotemporal hotspots within the region.\n\n### Mandalay\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract Mandalay region\nMandalay <- adm1 %>%\n  filter(ST == \"Mandalay\")\n\n# Print basic information about Mandalay\nprint(Mandalay)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 1 feature and 6 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 94.82973 ymin: 20.19307 xmax: 96.89598 ymax: 23.68381\nGeodetic CRS:  WGS 84\n  OBJECTID       ST ST_PCODE  ST_RG          ST_MMR PCode_V\n1        9 Mandalay   MMR010 Region မန္တလေးတိုင်းဒေသကြီး     9.4\n                        geometry\n1 MULTIPOLYGON (((96.14023 23...\n```\n\n\n:::\n\n```{.r .cell-code}\n# Plot Mandalay to visualize it\nggplot() +\n  geom_sf(data = adm1, fill = \"lightgrey\", color = \"white\") +\n  geom_sf(data = Mandalay, fill = \"red\", alpha = 0.7) +\n  theme_minimal() +\n  labs(title = \"Mandalay Region in Myanmar\")\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n#### G-Function\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter conflict data for Mandalay and jitter the coordinates\nconflict_Mandalay <- conflict_data %>%\n  st_join(Mandalay) %>%\n  filter(!is.na(ST)) %>%\n  st_jitter()  # Small jitter amount, adjust if needed\n\n# Create observation window for Mandalay\nwindow_Mandalay <- as.owin(st_bbox(Mandalay))\n\n# Convert jittered conflict points to ppp object\nconflict_ppp_Mandalay <- as.ppp(st_coordinates(conflict_Mandalay), W = window_Mandalay)\n\n# Compute G-function estimation\ng_est_Mandalay <- Gest(conflict_ppp_Mandalay, correction = \"border\")\n\n# Plot the G-function\nplot(g_est_Mandalay, main = \"G-function for Conflict Events in Mandalay\")\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Print summary of G-function estimation\nsummary(g_est_Mandalay)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       r                theo              rs        \n Min.   :0.00000   Min.   :0.0000   Min.   :0.0000  \n 1st Qu.:0.02141   1st Qu.:0.5130   1st Qu.:0.9614  \n Median :0.04283   Median :0.9438   Median :0.9875  \n Mean   :0.04283   Mean   :0.7383   Mean   :0.9519  \n 3rd Qu.:0.06424   3rd Qu.:0.9985   3rd Qu.:0.9944  \n Max.   :0.08565   Max.   :1.0000   Max.   :0.9975  \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Perform Monte Carlo test\nG_Mandalay_env <- envelope(conflict_ppp_Mandalay, fun = Gest, nsim = 999, rank = 1, global = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 999 simulations of CSR  ...\n1, 2, 3, ......10.........20.........30.........40.........50.........60..\n.......70.........80.........90.........100.........110.........120.........130\n.........140.........150.........160.........170.........180.........190........\n.200.........210.........220.........230.........240.........250.........260......\n...270.........280.........290.........300.........310.........320.........330....\n.....340.........350.........360.........370.........380.........390.........400..\n.......410.........420.........430.........440.........450.........460.........470\n.........480.........490.........500.........510.........520.........530........\n.540.........550.........560.........570.........580.........590.........600......\n...610.........620.........630.........640.........650.........660.........670....\n.....680.........690.........700.........710.........720.........730.........740..\n.......750.........760.........770.........780.........790.........800.........810\n.........820.........830.........840.........850.........860.........870........\n.880.........890.........900.........910.........920.........930.........940......\n...950.........960.........970.........980.........990........\n999.\n\nDone.\n```\n\n\n:::\n\n```{.r .cell-code}\n# Plot the results\nplot(G_Mandalay_env, main = \"Monte Carlo Test: G-function for Conflict Events in Mandalay\")\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Print the results of the test\nprint(G_Mandalay_env)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimultaneous critical envelopes for G(r)\nand observed value for 'conflict_ppp_Mandalay'\nEdge correction: \"km\"\nObtained from 999 simulations of CSR\nEnvelope based on maximum deviation of G(r) from null value for CSR (known \nexactly)\nAlternative: two.sided\nSignificance level of simultaneous Monte Carlo test: 1/1000 = 0.001\n...........................................................\n     Math.label     Description                            \nr    r              distance argument r                    \nobs  hat(G)[obs](r) observed value of G(r) for data pattern\ntheo G[theo](r)     theoretical value of G(r) for CSR      \nlo   hat(G)[lo](r)  lower critical boundary for G(r)       \nhi   hat(G)[hi](r)  upper critical boundary for G(r)       \n...........................................................\nDefault plot formula:  .~r\nwhere \".\" stands for 'obs', 'theo', 'hi', 'lo'\nColumns 'lo' and 'hi' will be plotted as shading (by default)\nRecommended range of argument r: [0, 0.0083644]\nAvailable range of argument r: [0, 0.0083644]\n```\n\n\n:::\n:::\n\n\n#### L-Function\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate L-function\nL_Mandalay <- Lest(conflict_ppp_Mandalay, correction = \"Ripley\")\n\n# Plot L-function\nplot(L_Mandalay, . - r ~ r, main = \"L-function for Conflict Events in Mandalay\")\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Perform Monte Carlo test with L-function\nL_Mandalay_env <- envelope(conflict_ppp_Mandalay, fun = Lest, nsim = 999, rank = 1, global = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 999 simulations of CSR  ...\n1, 2, 3, ......10.........20.........30.........40.........50.........60..\n.......70.........80.........90.........100.........110.........120.........130\n.........140.........150.........160.........170.........180.........190........\n.200.........210.........220.........230.........240.........250.........260......\n...270.........280.........290.........300.........310.........320.........330....\n.....340.........350.........360.........370.........380.........390.........400..\n.......410.........420.........430.........440.........450.........460.........470\n.........480.........490.........500.........510.........520.........530........\n.540.........550.........560.........570.........580.........590.........600......\n...610.........620.........630.........640.........650.........660.........670....\n.....680.........690.........700.........710.........720.........730.........740..\n.......750.........760.........770.........780.........790.........800.........810\n.........820.........830.........840.........850.........860.........870........\n.880.........890.........900.........910.........920.........930.........940......\n...950.........960.........970.........980.........990........\n999.\n\nDone.\n```\n\n\n:::\n\n```{.r .cell-code}\n# Plot Monte Carlo test results\nplot(L_Mandalay_env, . - r ~ r, main = \"Monte Carlo Test: L-function for Conflict Events in Mandalay\")\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Print the results of the test\nprint(L_Mandalay_env)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimultaneous critical envelopes for L(r)\nand observed value for 'conflict_ppp_Mandalay'\nEdge correction: \"iso\"\nObtained from 999 simulations of CSR\nEnvelope based on maximum deviation of L(r) from null value for CSR (known \nexactly)\nAlternative: two.sided\nSignificance level of simultaneous Monte Carlo test: 1/1000 = 0.001\n...........................................................\n     Math.label     Description                            \nr    r              distance argument r                    \nobs  hat(L)[obs](r) observed value of L(r) for data pattern\ntheo L[theo](r)     theoretical value of L(r) for CSR      \nlo   hat(L)[lo](r)  lower critical boundary for L(r)       \nhi   hat(L)[hi](r)  upper critical boundary for L(r)       \n...........................................................\nDefault plot formula:  .~r\nwhere \".\" stands for 'obs', 'theo', 'hi', 'lo'\nColumns 'lo' and 'hi' will be plotted as shading (by default)\nRecommended range of argument r: [0, 0.51656]\nAvailable range of argument r: [0, 0.51656]\n```\n\n\n:::\n:::\n\n\n#### L-Function over time\n\nSet to eval:false\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract Mandalay region\nmandalay <- adm1 %>%\n  filter(ST == \"Mandalay\")\n\n# Filter conflict data for Mandalay and jitter the coordinates\nconflict_mandalay <- conflict_data %>%\n  st_join(mandalay) %>%\n  filter(!is.na(ST)) %>%\n  st_jitter()\n\n# Create observation window for Mandalay\nwindow_mandalay <- as.owin(st_bbox(mandalay))\n\n# Function to analyze a single quarter\nanalyze_quarter <- function(data, quarter) {\n  conflict_ppp <- as.ppp(st_coordinates(data), W = window_mandalay)\n  \n  tryCatch({\n    g_est <- Gest(conflict_ppp, correction = \"border\")\n    l_est <- Lest(conflict_ppp, correction = \"Ripley\")\n    \n    g_plot <- plot(g_est, main = paste(\"G-function for Mandalay -\", quarter))\n    l_plot <- plot(l_est, . - r ~ r, main = paste(\"L-function for Mandalay -\", quarter))\n    \n    return(list(g_plot = g_plot, l_plot = l_plot, message = NULL))\n  }, error = function(e) {\n    print(paste(\"Lack of entry within the time period:\", quarter))\n  })\n}\n\n# Perform analysis for each quarter\nquarterly_results <- conflict_mandalay %>%\n  group_by(quarter) %>%\n  group_map(~ analyze_quarter(.x, .y$quarter))\n```\n:::\n\n\n#### **Spatio-Temporal kernel density estimation**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Mandalay Region\nmandalay <- adm1 %>%\n  filter(ST == \"Mandalay\")\n# Filter conflict data for Mandalay and jitter the coordinates\nconflict_mandalay <- conflict_data %>%\n  st_join(mandalay) %>%\n  filter(!is.na(ST)) %>%\n  st_jitter()\n# Create observation window for Mandalay\nwindow_mandalay <- as.owin(st_bbox(mandalay))\n# Prepare data for STKDE\ncoords <- st_coordinates(conflict_mandalay)\nt <- as.numeric(conflict_mandalay$event_date - min(conflict_mandalay$event_date))\n# Create ppp object\nppp_mandalay <- as.ppp(coords, W = window_mandalay)\n# Compute bandwidths\nh_spatial <- bw.ppl(ppp_mandalay)\nh_temporal <- bw.SJ(t)\n# Perform STKDE\nstkde_result <- spattemp.density(ppp_mandalay, t, tlim = range(t),\n                                 h = c(h_spatial, h_temporal))\n# Print summary of STKDE result\nprint(summary(stkde_result))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatiotemporal Kernel Density Estimate\n\nBandwidths\n  h = 0.0108 (spatial)\n  lambda = 26.5057 (temporal)\n\nNo. of observations\n  3603 \n\nSpatial bound\n  Type: rectangle\n  2D enclosure: [94.82973, 96.89598] x [20.19307, 23.68381]\n\nTemporal bound\n  [0, 1264]\n\nEvaluation\n  128 x 128 x 1265 trivariate lattice\n  Density range: [0, 0.1762955]\nNULL\n```\n\n\n:::\n:::\n\n\nThe analysis of conflict events in Mandalay reveals a significant pattern of spatial and temporal clustering. Over a period of approximately 3.5 years, 3,603 conflict events were recorded within a defined geographic area, averaging about 2.85 incidents per day.\n\nBoth the G-function and L-function analyses consistently demonstrate that this clustering is substantially more pronounced than would be expected from a random distribution, with particularly intense clustering at shorter distances but persisting across larger scales.\n\nThe spatiotemporal kernel density estimation further indicates the presence of specific hotspots within the region, with a wide density range suggesting significant variation in conflict concentration.\n\n### Magway\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract Magway region\nMagway <- adm1 %>%\n  filter(ST == \"Magway\")\n\n# Print basic information about Magway\nprint(Magway)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 1 feature and 6 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 93.84551 ymin: 18.83204 xmax: 95.85919 ymax: 22.77128\nGeodetic CRS:  WGS 84\n  OBJECTID     ST ST_PCODE  ST_RG        ST_MMR PCode_V\n1        8 Magway   MMR009 Region မကွေးတိုင်းဒေသကြီး     9.4\n                        geometry\n1 MULTIPOLYGON (((94.11699 22...\n```\n\n\n:::\n\n```{.r .cell-code}\n# Plot Magway to visualize it\nggplot() +\n  geom_sf(data = adm1, fill = \"lightgrey\", color = \"white\") +\n  geom_sf(data = Magway, fill = \"red\", alpha = 0.7) +\n  theme_minimal() +\n  labs(title = \"Magway Region in Myanmar\")\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\n#### G-Function\n\n\n::: {.cell}\n\n```{.r .cell-code}\n # Filter conflict data for Magway and jitter the coordinates\nconflict_Magway <- conflict_data %>%\n  st_join(Magway) %>%\n  filter(!is.na(ST)) %>%\n  st_jitter()  # Small jitter amount, adjust if needed\n\n# Create observation window for Magway\nwindow_Magway <- as.owin(st_bbox(Magway))\n\n# Convert jittered conflict points to ppp object\nconflict_ppp_Magway <- as.ppp(st_coordinates(conflict_Magway), W = window_Magway)\n\n# Compute G-function estimation\ng_est_Magway <- Gest(conflict_ppp_Magway, correction = \"border\")\n\n# Plot the G-function\nplot(g_est_Magway, main = \"G-function for Conflict Events in Magway\")\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Print summary of G-function estimation\nsummary(g_est_Magway)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       r                theo              rs        \n Min.   :0.00000   Min.   :0.0000   Min.   :0.0000  \n 1st Qu.:0.02085   1st Qu.:0.5130   1st Qu.:0.9529  \n Median :0.04170   Median :0.9438   Median :0.9794  \n Mean   :0.04170   Mean   :0.7383   Mean   :0.9392  \n 3rd Qu.:0.06255   3rd Qu.:0.9985   3rd Qu.:0.9919  \n Max.   :0.08340   Max.   :1.0000   Max.   :0.9962  \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Perform Monte Carlo test\nG_Magway_env <- envelope(conflict_ppp_Magway, fun = Gest, nsim = 999, rank = 1, global = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 999 simulations of CSR  ...\n1, 2, 3, ......10.........20.........30.........40.........50.........60..\n.......70.........80.........90.........100.........110.........120.........130\n.........140.........150.........160.........170.........180.........190........\n.200.........210.........220.........230.........240.........250.........260......\n...270.........280.........290.........300.........310.........320.........330....\n.....340.........350.........360.........370.........380.........390.........400..\n.......410.........420.........430.........440.........450.........460.........470\n.........480.........490.........500.........510.........520.........530........\n.540.........550.........560.........570.........580.........590.........600......\n...610.........620.........630.........640.........650.........660.........670....\n.....680.........690.........700.........710.........720.........730.........740..\n.......750.........760.........770.........780.........790.........800.........810\n.........820.........830.........840.........850.........860.........870........\n.880.........890.........900.........910.........920.........930.........940......\n...950.........960.........970.........980.........990........\n999.\n\nDone.\n```\n\n\n:::\n\n```{.r .cell-code}\n# Plot the results\nplot(G_Magway_env, main = \"Monte Carlo Test: G-function for Conflict Events in Magway\")\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Print the results of the test\nprint(G_Magway_env)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimultaneous critical envelopes for G(r)\nand observed value for 'conflict_ppp_Magway'\nEdge correction: \"km\"\nObtained from 999 simulations of CSR\nEnvelope based on maximum deviation of G(r) from null value for CSR (known \nexactly)\nAlternative: two.sided\nSignificance level of simultaneous Monte Carlo test: 1/1000 = 0.001\n...........................................................\n     Math.label     Description                            \nr    r              distance argument r                    \nobs  hat(G)[obs](r) observed value of G(r) for data pattern\ntheo G[theo](r)     theoretical value of G(r) for CSR      \nlo   hat(G)[lo](r)  lower critical boundary for G(r)       \nhi   hat(G)[hi](r)  upper critical boundary for G(r)       \n...........................................................\nDefault plot formula:  .~r\nwhere \".\" stands for 'obs', 'theo', 'hi', 'lo'\nColumns 'lo' and 'hi' will be plotted as shading (by default)\nRecommended range of argument r: [0, 0.010425]\nAvailable range of argument r: [0, 0.010425]\n```\n\n\n:::\n:::\n\n\n#### L-Function\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate L-function\nL_Magway <- Lest(conflict_ppp_Magway, correction = \"Ripley\")\n\n# Plot L-function\nplot(L_Magway, . - r ~ r, main = \"L-function for Conflict Events in Magway\")\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Perform Monte Carlo test with L-function\nL_Magway_env <- envelope(conflict_ppp_Magway, fun = Lest, nsim = 999, rank = 1, global = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 999 simulations of CSR  ...\n1, 2, 3, ......10.........20.........30.........40.........50.........60..\n.......70.........80.........90.........100.........110.........120.........130\n.........140.........150.........160.........170.........180.........190........\n.200.........210.........220.........230.........240.........250.........260......\n...270.........280.........290.........300.........310.........320.........330....\n.....340.........350.........360.........370.........380.........390.........400..\n.......410.........420.........430.........440.........450.........460.........470\n.........480.........490.........500.........510.........520.........530........\n.540.........550.........560.........570.........580.........590.........600......\n...610.........620.........630.........640.........650.........660.........670....\n.....680.........690.........700.........710.........720.........730.........740..\n.......750.........760.........770.........780.........790.........800.........810\n.........820.........830.........840.........850.........860.........870........\n.880.........890.........900.........910.........920.........930.........940......\n...950.........960.........970.........980.........990........\n999.\n\nDone.\n```\n\n\n:::\n\n```{.r .cell-code}\n# Plot Monte Carlo test results\nplot(L_Magway_env, . - r ~ r, main = \"Monte Carlo Test: L-function for Conflict Events in Magway\")\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Print the results of the test\nprint(L_Magway_env)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimultaneous critical envelopes for L(r)\nand observed value for 'conflict_ppp_Magway'\nEdge correction: \"iso\"\nObtained from 999 simulations of CSR\nEnvelope based on maximum deviation of L(r) from null value for CSR (known \nexactly)\nAlternative: two.sided\nSignificance level of simultaneous Monte Carlo test: 1/1000 = 0.001\n...........................................................\n     Math.label     Description                            \nr    r              distance argument r                    \nobs  hat(L)[obs](r) observed value of L(r) for data pattern\ntheo L[theo](r)     theoretical value of L(r) for CSR      \nlo   hat(L)[lo](r)  lower critical boundary for L(r)       \nhi   hat(L)[hi](r)  upper critical boundary for L(r)       \n...........................................................\nDefault plot formula:  .~r\nwhere \".\" stands for 'obs', 'theo', 'hi', 'lo'\nColumns 'lo' and 'hi' will be plotted as shading (by default)\nRecommended range of argument r: [0, 0.50342]\nAvailable range of argument r: [0, 0.50342]\n```\n\n\n:::\n:::\n\n\n#### L-Function over time\n\nSet eval:false\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract Magway region\nmagway <- adm1 %>%\n  filter(ST == \"Magway\")\n# Filter conflict data for Magway and jitter the coordinates\nconflict_magway <- conflict_data %>%\n  st_join(magway) %>%\n  filter(!is.na(ST)) %>%\n  st_jitter()\n# Create observation window for Magway\nwindow_magway <- as.owin(st_bbox(magway))\n# Function to analyze a single quarter\nanalyze_quarter <- function(data, quarter) {\n  conflict_ppp <- as.ppp(st_coordinates(data), W = window_magway)\n  \n  tryCatch({\n    g_est <- Gest(conflict_ppp, correction = \"border\")\n    l_est <- Lest(conflict_ppp, correction = \"Ripley\")\n    \n    g_plot <- plot(g_est, main = paste(\"G-function for Magway -\", quarter))\n    l_plot <- plot(l_est, . - r ~ r, main = paste(\"L-function for Magway -\", quarter))\n    \n    return(list(g_plot = g_plot, l_plot = l_plot, message = NULL))\n  }, error = function(e) {\n    print(paste(\"Lack of entry within the time period:\", quarter))\n  })\n}\n# Perform analysis for each quarter\nquarterly_results <- conflict_magway %>%\n  group_by(quarter) %>%\n  group_map(~ analyze_quarter(.x, .y$quarter))\n```\n:::\n\n\n#### **Spatio-Temporal kernel density estimation**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Magway Region\nmagway <- adm1 %>%\n  filter(ST == \"Magway\")\n# Filter conflict data for Magway and jitter the coordinates\nconflict_magway <- conflict_data %>%\n  st_join(magway) %>%\n  filter(!is.na(ST)) %>%\n  st_jitter()\n# Create observation window for Magway\nwindow_magway <- as.owin(st_bbox(magway))\n# Prepare data for STKDE\ncoords <- st_coordinates(conflict_magway)\nt <- as.numeric(conflict_magway$event_date - min(conflict_magway$event_date))\n# Create ppp object\nppp_magway <- as.ppp(coords, W = window_magway)\n# Compute bandwidths\nh_spatial <- bw.ppl(ppp_magway)\nh_temporal <- bw.SJ(t)\n# Perform STKDE\nstkde_result <- spattemp.density(ppp_magway, t, tlim = range(t),\n                                 h = c(h_spatial, h_temporal))\n# Print summary of STKDE result\nprint(summary(stkde_result))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatiotemporal Kernel Density Estimate\n\nBandwidths\n  h = 0.0102 (spatial)\n  lambda = 29.4614 (temporal)\n\nNo. of observations\n  4179 \n\nSpatial bound\n  Type: rectangle\n  2D enclosure: [93.84551, 95.85919] x [18.83204, 22.77128]\n\nTemporal bound\n  [0, 1231]\n\nEvaluation\n  128 x 128 x 1232 trivariate lattice\n  Density range: [0, 0.1390678]\nNULL\n```\n\n\n:::\n:::\n\n\nThe analysis of conflict events in Magway reveals a significant pattern of spatial and temporal clustering over a period of approximately 3.4 years, with 4,179 recorded incidents averaging 3.4 events per day.\n\nBoth the G-function and L-function analyses consistently demonstrate that this clustering is substantially more pronounced than would be expected from a random distribution, with particularly intense clustering at shorter distances but persisting across larger scales.\n\nThe spatiotemporal kernel density estimation further indicates the presence of specific hotspots within the region, with a wide density range suggesting significant variation in conflict concentration.\n\n### Central Region Analysis\n\nThe analysis of conflict events across these three regions demonstrates a consistent pattern of significant spatial and temporal clustering, far exceeding what would be expected from random distribution.\n\nSagaing emerges as the most conflict-intensive area, with approximately 11,128 events over 3.5 years (about 9 events per day), followed by Magway with 4,179 events (3.4 per day), and Mandalay with 3,603 events (2.85 per day).\n\nAll three regions exhibit strong multi-scale clustering, with particularly intense clustering at shorter distances, indicating the presence of localized conflict hotspots as well as broader regional patterns.\n\nThe spatial analysis suggests that these conflict events are not uniformly distributed but are concentrated in specific geographic areas within each region, likely corresponding to strategic locations, population centers, or areas of contested control between Junta and rebel forces.\n\nThe spatiotemporal kernel density estimations for each region reveal significant variations in conflict intensity across space and time, suggesting the presence of dynamic hotspots that may shift or evolve. This could reflect the changing frontlines or areas of control between Junta and rebel forces, or the focus of military operations and resistance activities.\n\nGiven their status as critical border zones, the intense clustering and high frequency of conflict events in these regions likely reflect their strategic importance in the broader conflict. The patterns observed suggest a complex interplay of local and regional factors driving the conflict dynamics, potentially including control over key infrastructure, population centers, or resources.\n\n## Southern-Region : Yangon \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract Yangon region\nYangon <- adm1 %>%\n  filter(ST == \"Yangon\")\n\n# Print basic information about Yangon\nprint(Yangon)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 1 feature and 6 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 93.35195 ymin: 14.04583 xmax: 96.82663 ymax: 17.79696\nGeodetic CRS:  WGS 84\n  OBJECTID     ST ST_PCODE  ST_RG        ST_MMR PCode_V\n1       18 Yangon   MMR013 Region ရန်ကုန်တိုင်းဒေသကြီး     9.4\n                        geometry\n1 MULTIPOLYGON (((93.37067 14...\n```\n\n\n:::\n\n```{.r .cell-code}\n# Plot Yangon to visualize it\nggplot() +\n  geom_sf(data = adm1, fill = \"lightgrey\", color = \"white\") +\n  geom_sf(data = Yangon, fill = \"red\", alpha = 0.7) +\n  theme_minimal() +\n  labs(title = \"Yangon Region in Myanmar\")\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n:::\n\n\n### G-Function\n\n\n::: {.cell}\n\n```{.r .cell-code}\n # Filter conflict data for Yangon and jitter the coordinates\nconflict_Yangon <- conflict_data %>%\n  st_join(Yangon) %>%\n  filter(!is.na(ST)) %>%\n  st_jitter()  # Small jitter amount, adjust if needed\n\n# Create observation window for Yangon\nwindow_Yangon <- as.owin(st_bbox(Yangon))\n\n# Convert jittered conflict points to ppp object\nconflict_ppp_Yangon <- as.ppp(st_coordinates(conflict_Yangon), W = window_Yangon)\n\n# Compute G-function estimation\ng_est_Yangon <- Gest(conflict_ppp_Yangon, correction = \"border\")\n\n# Plot the G-function\nplot(g_est_Yangon, main = \"G-function for Conflict Events in Yangon\")\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-38-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Print summary of G-function estimation\nsummary(g_est_Yangon)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       r                theo              rs        \n Min.   :0.00000   Min.   :0.0000   Min.   :0.0000  \n 1st Qu.:0.03383   1st Qu.:0.5130   1st Qu.:0.9904  \n Median :0.06767   Median :0.9438   Median :0.9973  \n Mean   :0.06767   Mean   :0.7383   Mean   :0.9890  \n 3rd Qu.:0.10150   3rd Qu.:0.9985   3rd Qu.:0.9992  \n Max.   :0.13533   Max.   :1.0000   Max.   :0.9996  \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Perform Monte Carlo test\nG_Yangon_env <- envelope(conflict_ppp_Yangon, fun = Gest, nsim = 999, rank = 1, global = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 999 simulations of CSR  ...\n1, 2, 3, ......10.........20.........30.........40.........50.........60..\n.......70.........80.........90.........100.........110.........120.........130\n.........140.........150.........160.........170.........180.........190........\n.200.........210.........220.........230.........240.........250.........260......\n...270.........280.........290.........300.........310.........320.........330....\n.....340.........350.........360.........370.........380.........390.........400..\n.......410.........420.........430.........440.........450.........460.........470\n.........480.........490.........500.........510.........520.........530........\n.540.........550.........560.........570.........580.........590.........600......\n...610.........620.........630.........640.........650.........660.........670....\n.....680.........690.........700.........710.........720.........730.........740..\n.......750.........760.........770.........780.........790.........800.........810\n.........820.........830.........840.........850.........860.........870........\n.880.........890.........900.........910.........920.........930.........940......\n...950.........960.........970.........980.........990........\n999.\n\nDone.\n```\n\n\n:::\n\n```{.r .cell-code}\n# Plot the results\nplot(G_Yangon_env, main = \"Monte Carlo Test: G-function for Conflict Events in Yangon\")\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-39-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Print the results of the test\nprint(G_Yangon_env)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimultaneous critical envelopes for G(r)\nand observed value for 'conflict_ppp_Yangon'\nEdge correction: \"km\"\nObtained from 999 simulations of CSR\nEnvelope based on maximum deviation of G(r) from null value for CSR (known \nexactly)\nAlternative: two.sided\nSignificance level of simultaneous Monte Carlo test: 1/1000 = 0.001\n...........................................................\n     Math.label     Description                            \nr    r              distance argument r                    \nobs  hat(G)[obs](r) observed value of G(r) for data pattern\ntheo G[theo](r)     theoretical value of G(r) for CSR      \nlo   hat(G)[lo](r)  lower critical boundary for G(r)       \nhi   hat(G)[hi](r)  upper critical boundary for G(r)       \n...........................................................\nDefault plot formula:  .~r\nwhere \".\" stands for 'obs', 'theo', 'hi', 'lo'\nColumns 'lo' and 'hi' will be plotted as shading (by default)\nRecommended range of argument r: [0, 0.00079296]\nAvailable range of argument r: [0, 0.00079296]\n```\n\n\n:::\n:::\n\n\n### L-Function\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate L-function\nL_Yangon <- Lest(conflict_ppp_Yangon, correction = \"Ripley\")\n\n# Plot L-function\nplot(L_Yangon, . - r ~ r, main = \"L-function for Conflict Events in Yangon\")\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Perform Monte Carlo test with L-function\nL_Yangon_env <- envelope(conflict_ppp_Yangon, fun = Lest, nsim = 999, rank = 1, global = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 999 simulations of CSR  ...\n1, 2, 3, ......10.........20.........30.........40.........50.........60..\n.......70.........80.........90.........100.........110.........120.........130\n.........140.........150.........160.........170.........180.........190........\n.200.........210.........220.........230.........240.........250.........260......\n...270.........280.........290.........300.........310.........320.........330....\n.....340.........350.........360.........370.........380.........390.........400..\n.......410.........420.........430.........440.........450.........460.........470\n.........480.........490.........500.........510.........520.........530........\n.540.........550.........560.........570.........580.........590.........600......\n...610.........620.........630.........640.........650.........660.........670....\n.....680.........690.........700.........710.........720.........730.........740..\n.......750.........760.........770.........780.........790.........800.........810\n.........820.........830.........840.........850.........860.........870........\n.880.........890.........900.........910.........920.........930.........940......\n...950.........960.........970.........980.........990........\n999.\n\nDone.\n```\n\n\n:::\n\n```{.r .cell-code}\n# Plot Monte Carlo test results\nplot(L_Yangon_env, . - r ~ r, main = \"Monte Carlo Test: L-function for Conflict Events in Yangon\")\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-41-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Print the results of the test\nprint(L_Yangon_env)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimultaneous critical envelopes for L(r)\nand observed value for 'conflict_ppp_Yangon'\nEdge correction: \"iso\"\nObtained from 999 simulations of CSR\nEnvelope based on maximum deviation of L(r) from null value for CSR (known \nexactly)\nAlternative: two.sided\nSignificance level of simultaneous Monte Carlo test: 1/1000 = 0.001\n...........................................................\n     Math.label     Description                            \nr    r              distance argument r                    \nobs  hat(L)[obs](r) observed value of L(r) for data pattern\ntheo L[theo](r)     theoretical value of L(r) for CSR      \nlo   hat(L)[lo](r)  lower critical boundary for L(r)       \nhi   hat(L)[hi](r)  upper critical boundary for L(r)       \n...........................................................\nDefault plot formula:  .~r\nwhere \".\" stands for 'obs', 'theo', 'hi', 'lo'\nColumns 'lo' and 'hi' will be plotted as shading (by default)\nRecommended range of argument r: [0, 0.86867]\nAvailable range of argument r: [0, 0.86867]\n```\n\n\n:::\n:::\n\n\n### L-Function over time\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract Yangon region\nyangon <- adm1 %>%\n  filter(ST == \"Yangon\")\n\n# Filter conflict data for Yangon and jitter the coordinates\nconflict_yangon <- conflict_data %>%\n  st_join(yangon) %>%\n  filter(!is.na(ST)) %>%\n  st_jitter()\n\n# Create observation window for Yangon\nwindow_yangon <- as.owin(st_bbox(yangon))\n\n# Function to analyze a single quarter\nanalyze_quarter <- function(data, quarter) {\n  conflict_ppp <- as.ppp(st_coordinates(data), W = window_yangon)\n  \n  tryCatch({\n    g_est <- Gest(conflict_ppp, correction = \"border\")\n    l_est <- Lest(conflict_ppp, correction = \"Ripley\")\n    \n    g_plot <- plot(g_est, main = paste(\"G-function for Yangon -\", quarter))\n    l_plot <- plot(l_est, . - r ~ r, main = paste(\"L-function for Yangon -\", quarter))\n    \n    return(list(g_plot = g_plot, l_plot = l_plot, message = NULL))\n  }, error = function(e) {\n    print(paste(\"Lack of entry within the time period:\", quarter))\n  })\n}\n\n# Perform analysis for each quarter\nquarterly_results <- conflict_yangon %>%\n  group_by(quarter) %>%\n  group_map(~ analyze_quarter(.x, .y$quarter))\n```\n:::\n\n\n### Spatio-Temporal kernel density estimation\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Yangon Region\nyangon <- adm1 %>%\n  filter(ST == \"Yangon\")\n# Filter conflict data for Yangon and jitter the coordinates\nconflict_yangon <- conflict_data %>%\n  st_join(yangon) %>%\n  filter(!is.na(ST)) %>%\n  st_jitter()\n# Create observation window for Yangon\nwindow_yangon <- as.owin(st_bbox(yangon))\n# Prepare data for STKDE\ncoords <- st_coordinates(conflict_yangon)\nt <- as.numeric(conflict_yangon$event_date - min(conflict_yangon$event_date))\n# Create ppp object\nppp_yangon <- as.ppp(coords, W = window_yangon)\n# Compute bandwidths\nh_spatial <- bw.ppl(ppp_yangon)\nh_temporal <- bw.SJ(t)\n# Perform STKDE\nstkde_result <- spattemp.density(ppp_yangon, t, tlim = range(t),\n                                 h = c(h_spatial, h_temporal))\n# Print summary of STKDE result\nprint(summary(stkde_result))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatiotemporal Kernel Density Estimate\n\nBandwidths\n  h = 0.004 (spatial)\n  lambda = 21.4251 (temporal)\n\nNo. of observations\n  2608 \n\nSpatial bound\n  Type: rectangle\n  2D enclosure: [93.35195, 96.82663] x [14.04583, 17.79696]\n\nTemporal bound\n  [0, 1262]\n\nEvaluation\n  128 x 128 x 1263 trivariate lattice\n  Density range: [0, 0.3442227]\nNULL\n```\n\n\n:::\n:::\n\n\nThe analysis of conflict events in Yangon reveals a complex and intensely clustered pattern of violence over approximately 3.5 years, with 2,608 recorded incidents averaging 2.07 events per day.\n\nBoth the G-function and L-function analyses consistently demonstrate significant spatial clustering far exceeding what would be expected from random distribution, with particularly strong clustering at shorter and medium distances.\n\nThe spatiotemporal kernel density estimation further confirms the presence of specific hotspots within the region, with a wide density range indicating significant variation in conflict concentration.\n\nComparing the conflict dynamics in Yangon with those of the central region (Sagaing, Mandalay, and Magway) reveals both similarities and distinct characteristics, highlighting the complex nature of the conflict across different parts of Myanmar:\n\n1.  Conflict Intensity:\n\n    -   The Central Region experiences higher overall conflict intensity.\n\n2.  Spatial Clustering:\n\n    -   Both areas exhibit strong spatial clustering of conflict events, significantly deviating from random distribution.\n\n    -   Yangon shows particularly intense clustering at shorter and medium distances.\n\n    -   The central regions display strong multi-scale clustering, but without the pronounced peak seen in Yangon.\n\nYangon's conflict pattern likely reflects complex urban dynamics, with potential concentrations in specific neighborhoods or districts of Myanmar's largest city. The central regions' patterns suggest a mix of urban and rural conflict zones, possibly reflecting the more diverse geography of these areas.\n\n# Visualization of Conflict Density Using OpenStreetMap\n\nHaving completed our analysis using shapefiles, we now transition to a more realistic and detailed mapping approach by incorporating OpenStreetMap as the base layer for our Kernel Density Estimation (KDE) visualizations. This shift from abstract boundary representations to a comprehensive geographical context allows us to better understand the nuances of conflict distribution in Myanmar.\n\nBy overlaying our KDE results on this realistic backdrop, we can more effectively correlate conflict hotspots with actual geographical features, offering deeper insights into how the physical landscape and human geography of Myanmar influence conflict dynamics.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Function to fetch OpenStreetMap base map\nget_osm_map <- function(bbox) {\n  osm_map <- read_osm(bbox, type = \"osm\", zoom = NULL)\n  return(osm_map)\n}\n\n# Function to plot a single KDE layer with tmap\nplot_kde_tmap <- function(kde_layer, quarter, admin_boundary, osm_map, density_range) {\n  # Convert raster to stars object\n  kde_stars <- st_as_stars(kde_layer)\n  \n  # Calculate the threshold for visibility (e.g., top 20% of density values)\n  threshold <- quantile(kde_stars[[1]], 0.8, na.rm = TRUE)\n  \n  # Set values below the threshold as NA for transparency\n  kde_stars[kde_stars < threshold] <- NA\n  \n  # Create the tmap plot\n  tm_shape(osm_map) +\n    tm_rgb() +\n    tm_shape(kde_stars) +\n    tm_raster(palette = c(\"#FFCCCC\", \"#FF0000\"), \n              alpha = 0.7,\n              title = \"Density\",\n              style = \"cont\",\n              breaks = c(threshold, density_range[2]),\n              midpoint = NA,\n              legend.reverse = TRUE) +\n    tm_shape(admin_boundary) +\n    tm_borders(col = \"black\", lwd = 1.5) +\n    tm_layout(main.title = paste(\"KDE for\", quarter),\n              main.title.size = 1,\n              legend.outside = TRUE,\n              legend.outside.position = \"right\")\n}\n\n# Get the bounding box of Myanmar\nmyanmar_bbox <- st_bbox(adm0)\n\n# Fetch OpenStreetMap base map\nosm_map <- read_osm(myanmar_bbox)\n\n# Get the density range\ndensity_range <- get_lowest_max_density(kde_layers)\n\n# Plot all KDE layers with fixed density scale\nkde_tmaps <- lapply(seq_along(kde_layers), function(i) {\n  plot_kde_tmap(kde_layers[[i]], names(kde_layers)[i], adm0, osm_map, density_range)\n})\n\n# Display the plots\ntmap_mode(\"plot\")  # Set tmap mode to static plotting\nfor (map in kde_tmaps) {\n  print(map)\n}\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-44-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-44-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-44-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-44-4.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-44-5.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-44-6.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-44-7.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-44-8.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-44-9.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-44-10.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-44-11.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-44-12.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-44-13.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-44-14.png){width=672}\n:::\n:::\n\n\nThe diagrams below shows a different way of visualizing the conflict density with Open Street Map.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Function to fetch OpenStreetMap base map\nget_osm_map <- function(bbox) {\n  osm_map <- read_osm(bbox, type = \"osm\", zoom = NULL)\n  return(osm_map)\n}\n\n# Function to plot a single KDE layer with tmap\nplot_kde_tmap <- function(kde_layer, quarter, admin_boundary, osm_map, density_range) {\n  # Convert raster to stars object\n  kde_stars <- st_as_stars(kde_layer)\n  \n  # Create the tmap plot\n  tm_shape(osm_map) +\n    tm_rgb() +\n    tm_shape(kde_stars) +\n    tm_raster(palette = \"viridis\", \n              alpha = 0.7,\n              title = \"Density\",\n              style = \"cont\",\n              breaks = density_range) +\n    tm_shape(admin_boundary) +\n    tm_borders(col = \"black\", lwd = 1.5) +\n    tm_layout(main.title = paste(\"KDE for\", quarter),\n              main.title.size = 1,\n              legend.outside = TRUE,\n              legend.outside.position = \"right\")\n}\n\n# Get the bounding box of Myanmar\nmyanmar_bbox <- st_bbox(adm0)\n\n# Fetch OpenStreetMap base map\nosm_map <- get_osm_map(myanmar_bbox)\n\n# Get the density range\ndensity_range <- get_lowest_max_density(kde_layers)\n\n# Plot all KDE layers with fixed density scale\nkde_tmaps <- lapply(seq_along(kde_layers), function(i) {\n  plot_kde_tmap(kde_layers[[i]], names(kde_layers)[i], adm0, osm_map, density_range)\n})\n\n# Display the plots\ntmap_mode(\"plot\")  # Set tmap mode to static plotting\nfor (map in kde_tmaps) {\n  print(map)\n}\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-45-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-45-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-45-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-45-4.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-45-5.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-45-6.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-45-7.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-45-8.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-45-9.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-45-10.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-45-11.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-45-12.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-45-13.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-45-14.png){width=672}\n:::\n:::\n\n\n# \n\n# Bonus Section : Predictive Conflict Analysis\n\nIn the pursuit of employing methods beyond those taught in class, this analysis has explored various advanced techniques and libraries in geospatial analysis. Notably, libraries such as viridis for enhanced color exploration and stars for improved raster manipulation were investigated, among others.\n\nHowever, I would like to end this report by looking towards the future and take a more proactive approach: **Predictive Conflict Analysis**. This decision stems from the recognition that while our previous analyses have been primarily retrospective, there is significant value in exploring future developments.\n\nOur approach thus far has primarily been retrospective, focusing on the examination and interpretation of historical conflict data in Myanmar. While this reactive analysis provides valuable insights into past trends and patterns, it leaves open the question of future developments.\n\nBy leveraging advanced time series forecasting techniques, specifically the Prophet package, we aim to project future conflict patterns in Myanmar. This shift from retrospective analysis to predictive modeling represents a significant step towards a more forward-looking approach in conflict studies and geospatial analysis.\n\nAs we delve into this predictive analysis, it's important to note that while these forecasts offer valuable insights, they should be interpreted with caution, considering the complex and often unpredictable nature of conflict dynamics. The following analysis serves as a data-driven complement to expert knowledge and on-the-ground intelligence in understanding and anticipating conflict patterns in Myanmar.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Prepare data for Prophet\nprophet_data <- conflict_data %>%\n  mutate(ds = as.Date(event_date)) %>%\n  group_by(ds) %>%\n  summarise(y = n()) %>%\n  ungroup()\n\n# Create and fit Prophet model\nm <- prophet(yearly.seasonality = TRUE, \n             weekly.seasonality = TRUE, \n             daily.seasonality = FALSE,\n             seasonality.mode = 'multiplicative')\n\nm <- fit.prophet(m, prophet_data)\n\n# Generate forecast\nfuture <- make_future_dataframe(m, periods = 365)  # Forecast for next year\nforecast <- predict(m, future)\n\n#  forecast\np <- plot(m, forecast) +\n  labs(title = \"Overall Conflict Event Forecast for Myanmar\",\n       x = \"Date\",\n       y = \"Number of Conflict Events\")\n\n\n# Plot components\ncomponents_plot <- prophet_plot_components(m, forecast)\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-46-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Plot Forecast\np\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-46-2.png){width=672}\n:::\n:::\n\n\n1.  Trend Analysis (Top Graph): This graph illustrates the overall trend of conflict events in Myanmar from 2021 to 2025. The y-axis represents the average number of daily conflict events, while the x-axis (labeled 'ds') shows the timeline.\n\n    The blue line depicts the trend, starting at about 10 events per day in early 2021, rapidly increasing to a peak of around 40 events per day in early 2022, followed by a gradual decline. The part of the line without any shaded area represents historical data, while the latter part (from mid 2024) is a forecast. The light blue shaded area indicates the forecast's uncertainty, widening as it projects further into the future.\n\n2.  Day of Week (Weekly) Trends (Middle Graph): This graph shows the average effect of each day of the week on conflict event frequency, based on historical data. The y-axis percentage indicates how much the number of events deviates from the overall daily average.\n\n    For instance, Wednesdays show about a 5% increase in events compared to the average, while weekends (particularly Sundays) see fewer events, with approximately a 6% decrease. This pattern suggests that conflict events are more likely to occur mid-week and less likely on weekends.\n\n3.  Yearly Seasonality (3rd Graph): This graph illustrates the seasonal patterns of conflict events throughout the year, also derived from historical data. The y-axis shows the percentage deviation from the yearly average.\n\n    Notable peaks occur in late January/early February (about 10% increase) and November (about 20% increase), while the lowest point is in early August (about 15-20% decrease). This suggests that certain times of the year consistently see more or fewer conflict events, possibly due to factors like weather patterns, political cycles, or cultural events.\n\n4.  The last graph shows a more focused look into the forecast.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Identify unique event types\nevent_types <- unique(conflict_data$event_type)\n\n# Function to prepare data for a specific event type\nprepare_event_type_data <- function(data, event_type) {\n  data %>%\n    filter(event_type == !!event_type) %>%\n    mutate(ds = as.Date(event_date)) %>%\n    group_by(ds) %>%\n    summarise(y = n()) %>%\n    ungroup()\n}\n\n# Function to create and fit Prophet model\ncreate_fit_model <- function(data) {\n  m <- prophet(yearly.seasonality = TRUE, \n               weekly.seasonality = TRUE, \n               daily.seasonality = FALSE,\n               seasonality.mode = 'multiplicative')\n  m <- fit.prophet(m, data)\n  return(m)\n}\n\n# Function to generate forecast\ngenerate_forecast <- function(model, periods = 365) {\n  future <- make_future_dataframe(model, periods = periods)\n  forecast <- predict(model, future)\n  return(forecast)\n}\n\n# Function to plot forecast\nplot_forecast <- function(model, forecast, event_type) {\n  plot(model, forecast) +\n    labs(title = paste(\"Forecast for\", event_type, \"Events\"),\n         x = \"Date\",\n         y = \"Number of Events\")\n}\n\n# Create lists to store models and forecasts\nevent_type_models <- list()\nevent_type_forecasts <- list()\n\n# Loop through each event type\nfor (type in event_types) {\n  # Prepare data\n  type_data <- prepare_event_type_data(conflict_data, type)\n  \n  # Create and fit model\n  model <- create_fit_model(type_data)\n  event_type_models[[type]] <- model\n  \n  # Generate forecast\n  forecast <- generate_forecast(model)\n  event_type_forecasts[[type]] <- forecast\n  \n  # Create and save plot\n  plot <- plot_forecast(model, forecast, type)\n\n  # Print plot\n  print(plot)\n}\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-47-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-47-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-47-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-47-4.png){width=672}\n:::\n\n```{.r .cell-code}\n# Analyze trends across event types\ntrend_comparison <- map_dfr(event_types, function(type) {\n  forecast <- event_type_forecasts[[type]]\n  forecast %>%\n    select(ds, trend) %>%\n    mutate(event_type = type)\n})\n\n# Plot trend comparison\ntrend_comparison_plot <- ggplot(trend_comparison, aes(x = ds, y = trend, color = event_type)) +\n  geom_line() +\n  labs(title = \"Trend Comparison Across Event Types\",\n       x = \"Date\",\n       y = \"Trend\",\n       color = \"Event Type\") +\n  theme_minimal()\n\n\n# Print trend comparison plot \nprint(trend_comparison_plot)\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex1_files/figure-html/unnamed-chunk-47-5.png){width=672}\n:::\n:::\n\n\n## Forecast Analysis\n\nThe predictive analysis of conflict events in Myanmar reveals a complex and evolving situation. While the overall conflict level is projected to remain relatively stable or slightly increase, a deeper examination of specific event types uncovers significant shifts in the nature of the conflict.\n\nKey findings:\n\n1.  **Overall Conflict Trend**: The general level of conflict is expected to persist or marginally increase, indicating ongoing instability in the region.\n\n2.  **Divergent Event Type Trends**:\n\n    -   Strategic developments and violence against civilians are projected to decrease.\n    -   Battles and explosions/remote violence are forecast to increase.\n\n3.  **Interpretation**: This pattern suggests that the conflict may be entering a new phase. The reduction in strategic developments and civilian-targeted violence, coupled with an increase in direct confrontations (battles) and remote attacks, indicates a potential intensification of military engagements between opposing forces.\n\n    **Context**: These projections align with recent analyses of the situation in Myanmar. As noted in a Council on Foreign Relations article, \"The rest of this year is now shaping up to be critical for both the junta and the opposition forces, who have generally maintained their alliance.\" This assessment supports our forecast that the conflict may be approaching a critical juncture or peak.\n\n<https://www.cfr.org/blog/will-2024-be-juntas-end-myanmar>\n\nThis indicates that the coming months could be decisive in shaping the future trajectory of the conflict in Myanmar.\n\n# Conclusion: Spatio-Temporal Patterns Analysis Summary\n\nOur comprehensive spatio-temporal analysis of conflict patterns in Myanmar has yielded several consistent and significant findings:\n\n1.  **Concentration of Conflict in Border Zones**: All analytical approaches employed in this study corroborate that the fighting is predominantly concentrated in regions that form the border zones between Junta-controlled areas and rebel-held territories. Specifically:\n\n    -   The regions of Sagaing, Mandalay, and Magway represent critical border zones between Junta and rebel forces in the central and northern parts of the country.\n    -   Yangon, in the south, is also a key part of this border zone, experiencing significant conflict due to its strategic importance and its position at the frontier between Junta and rebel-controlled areas.\n\n2.  **Intensity of Conflict in Border Regions**: These border zones - Sagaing, Mandalay, Magway, and Yangon - consistently show the highest intensity of conflict activities.\n\n3.  **Relative Calm in Core-Controlled Areas**: In contrast to these border zones, areas firmly under the control of either the Junta or rebel forces have demonstrated lower levels of conflict.\n\n4.  **Predictive Model Insights**: Our predictive modeling suggests that the conflict is approaching a critical juncture:\n\n    -   A projected decrease in violence against civilians and strategic developments is anticipated.\n    -   Conversely, an increase in battles and explosive events is forecasted, indicating a potential escalation in direct confrontations.\n\n5.  **Indications of an Impending Decisive Clash**: The shift in conflict patterns, as indicated by our predictive model, aligns with reports and analyses suggesting that both sides of the conflict are preparing for a decisive engagement. This impending climax in the conflict underscores the urgent need for conflict resolution initiatives and humanitarian preparedness.\n\n# References\n\n1.  *The International Institute for Strategic Studies.* (n.d.). Myanmar. The International Institute for Strategic Studies. <https://myanmar.iiss.org/>\n2.  Beech, H., & Wei, C. (2024, April 20). What’s Happening in Myanmar’s Civil War?. *The New York Times.* <https://www.nytimes.com/interactive/2024/04/20/world/asia/myanmar-civil-war.html>\n3.  *Special Advisory Council for Myanmar.* (n.d.). Special Advisory Council for Myanmar. <https://specialadvisorycouncil.org/>\n4.  *United States Institute of Peace.* (2022, November 10). Understanding the People’s Defense Forces in Myanmar. <https://www.usip.org/publications/2022/11/understanding-peoples-defense-forces-myanmar>\n5.  *Al Jazeera.* (2024, January 16). What is Myanmar’s Three Brotherhood Alliance that’s resisting the military? <https://www.aljazeera.com/news/2024/1/16/what-is-myanmars-three-brotherhood-alliance-thats-resisting-the-military>\n6.  *Council of Foreign Relations*(2024, January 13). Will 2024 be the junta’s end in Myanmar? *Council on Foreign Relations.* [https://www.cfr.org/blog/will-2024-be-juntas-end-myanmar](#0)\n7.  *Claude AI.* (n.d.). Claude AI. <https://claude.ai/>\n",
    "supporting": [
      "Takehome_Ex1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}