---
title: "In-Class Exercise 01: Geospatial Data Science"
author: "Chong Zhi Cheng"
date: "August 19, 2024"
date-modified: "last-modified"
execute:
  eval: true
  echo: true
  freeze: true
  warning: false
---

### Getting Started

#### Install and Launch R Packages

```{r}
pacman::p_load(sf, tidyverse)
```

Note that the KML file downloaded on data.gov is corrupted or is not working in some way. Hence, we will use st_write.

Note that the difference of WGS 84 and svy21

R is case sensitive .

```{r}
popdata <- read.csv('data/respopagesextod2023.csv')
```

```{r}
popdata2023 <- popdata %>% 
  group_by(PA,SZ,AG) %>%
  summarise(`POP` = sum(`Pop`)) %>%
  ungroup() %>%
  pivot_wider(names_from = AG,
              values_from = POP)

colnames(popdata2023)
```

```{r}
popdata2023 <- popdata %>% 
  group_by(PA,SZ,AG) %>%
  summarise(`POP` = sum(`Pop`)) %>%
  ungroup() %>%
  pivot_wider(names_from = AG,
              values_from = POP)%>%
  mutate(YOUNG = rowSums(.[3:6])
         +rowSums(.[14])) %>%
mutate(`ECONOMY ACTIVE` = rowSums(.[7:13])+
rowSums(.[15]))%>%
mutate(`AGED`=rowSums(.[16:21])) %>%
mutate(`TOTAL`=rowSums(.[3:21])) %>%  
mutate(`DEPENDENCY` = (`YOUNG` + `AGED`)
/`ECONOMY ACTIVE`) %>%
  select(`PA`, `SZ`, `YOUNG`, 
       `ECONOMY ACTIVE`, `AGED`, 
       `TOTAL`, `DEPENDENCY`)
```

```{r}
popdata2023 <- popdata2023 %>%
  mutate_at(.vars = vars(PA, SZ), 
          .funs = list(toupper)) %>%
  filter(`ECONOMY ACTIVE` > 0)
```

```{r}
head(popdata2023)
```

See below for the joins

```{r}
mpsz14_shp = st_read(dsn = "./data/", layer = "MP14_SUBZONE_WEB_PL")
```

```{r}
st_write(mpsz14_shp, "data/MP14_SUBZONE_WEB_PL.kml",delete_dsn = TRUE)
```

```{r}
mpsz14_kml = st_read('data/MP14_SUBZONE_WEB_PL.kml')
```

```{r}
mpsz19_kml = st_read('data/MasterPlan2019SubzoneBoundaryNoSeaKML.kml')
```

```{r}
mpsz19_shp = st_read(dsn = "./data/", layer = "MPSZ-2019") %>%
    st_transform(crs = 3414)
```

```{r}
preschool = st_read('data/PreSchoolsLocation.kml')
```

```{r}
st_crs(mpsz19_shp)
```

```{r}
pop2023_mpsz <- left_join(popdata2023, mpsz19_shp,
                          by = c("SZ" = "SUBZONE_N"))
```
