{
  "hash": "c67da09e67ca355d317467ed67d37af6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Prototyping Modules for Geospatial Analytics Shiny Application\"\nauthor: \"Chong Zhi Cheng\"\ndate: \"October 27, 2024\"\ndate-modified: \"last-modified\"\nexecute:\n  eval: true\n  echo: true\n  freeze: true\n  warning: false\n---\n\n\n# Spatial Distribution Analysis of Educational Facilities in Jakarta:\n\n## A Comprehensive Study of Accessibility and Urban Planning\n\nThe spatial distribution of schools in Jakarta, Indonesia's capital city, represents a critical aspect of educational accessibility and urban planning. As one of the world's most densely populated metropolitan areas, Jakarta's educational infrastructure directly impacts the lives of millions of students and their families. Understanding the spatial patterns, clustering, and relationships between school locations and socioeconomic factors is crucial for informed policy-making and urban development strategies.\n\n## Significance and Impact\n\nEquitable access to education is fundamental to social mobility and economic development, particularly in rapidly growing urban centers like Jakarta. Several factors make this analysis particularly crucial:\n\n-   **Educational Equity**: Spatial disparities in school distribution can perpetuate or exacerbate socioeconomic inequalities, as access to quality education often correlates with neighborhood demographics and income levels.\n\n-   **Urban Planning Challenges**: Jakarta's rapid urbanization and population growth create unique challenges for educational infrastructure planning, requiring evidence-based approaches to resource allocation.\n\n-   **Economic Implications**: School accessibility directly affects property values, population movement patterns, and local economic development, making it a key consideration for urban development strategies.\n\n-   **Transportation and Infrastructure**: Understanding school distribution patterns helps optimize transportation networks and reduce traffic congestion, a significant issue in Jakarta's urban landscape.\n\n-   **Policy Development**: Results from this analysis can inform evidence-based policy decisions about new school construction, resource allocation, and educational zoning regulations.\n\n## Research Objectives\n\nOur research objectives encompass three primary areas of investigation:\n\n1.  **Spatial Point Patterns Analysis for School Locations**\n2.  **LISA and HCSA Analysis of Schools**\n3.  **Geographically Weighted Regression Analysis**\n\n# Project Overview and Scope\n\n## Project Goals and Deliverable\n\nThe primary objective of this research is to conduct a comprehensive spatial analysis of Jakarta's educational infrastructure, with findings ultimately presented through an interactive Shiny application. This web-based platform will allow stakeholders to explore and interact with our analytical results, making complex spatial patterns and relationships accessible to policymakers, educators, and the public.\n\n## Collaborative Framework\n\nThis project represents a collaborative effort among three students, with work structured in the following phases:\n\n### Joint Research and Foundation (Team Effort)\n\n-   Initial research and literature review\n\n-   Data acquisition and preprocessing\n\n-   Exploratory Data Analysis (EDA)\n\n-   Problem formulation and methodology selection\n\nThe core analytical work has been distributed among team members, with each focusing on a specific aspect of spatial analysis:\n\n1.  **Spatial Point Patterns Analysis for School Locations**\n    -   <https://is415-gaa-baojieyeo.netlify.app/>\n2.  **LISA and HCSA Analysis of Schools**\n    -   *Current Report Focus*\n    -   The current latest interface design implementation can be accessed via the following link:\n        <https://zcchong415.shinyapps.io/Takehome_Ex3/>\n3.  **Geographically Weighted Regression Analysis**\n    -   <https://hxyap-is415-geospatial-workbook.netlify.app/>\n\n## Scope of Current Report\n\nThis report specifically details the **LISA and HCSA Analysis of Schools** component of the larger project. While this document can be read independently, it is designed to be part of a larger analytical narrative. Readers are encouraged to review all three reports for a complete understanding of Jakarta's educational spatial dynamics. The findings presented here complement and intersect with the other analytical streams.\n\n# Data Sources and Educational Context\n\n## Data Sources\n\nThis study utilizes three primary datasets:\n\n1.  **School Location Dataset** (`complete_data.csv`)\n    -   Source: Kaggle - Indonesia School Dataset with Province Data\n    -   URL: <https://www.kaggle.com/datasets/marchotridyo/indonesia-school-dataset-with-province-data>\n    -   Content: Comprehensive information about schools including:\n        -   Geographic coordinates\n        -   School type classification\n        -   Operational status\n        -   Administrative information\n2.  **Administrative Boundaries** (`geoBoundaries-IDN-ADM2_simplified`)\n    -   Source: Humanitarian Data Exchange (HDX)\n    -   URL: <https://data.humdata.org/dataset/geoboundaries-admin-boundaries-for-indonesia>\n    -   Content: Simplified boundary data for:\n        -   Administrative level 2 (ADM2) regions\n        -   Provincial divisions\n        -   District demarcations\n3.  **Village-Level Boundaries** (`BATAS_DESA_DESEMBER_2019_DUKCAPIL_DKI_JAKARTA`)\n    -   Source: Indonesia Geospatial Portal\n    -   URL: <https://www.indonesia-geospasial.com>\n    -   Content: Detailed boundary data for:\n        -   Village (desa) level administrative units\n\n        -   Jakarta metropolitan area\n\n## Indonesian Education System Context\n\nThe Indonesian education system comprises several distinct school types, each serving specific educational needs and age groups:\n\n### Primary Education\n\n-   **SD (Sekolah Dasar)**\n    -   Elementary school for ages 6-12\n    -   Grades 1-6\n    -   Mandatory basic education\n    -   Core subjects: mathematics, science, language, social studies\n-   **SDLB (Sekolah Dasar Luar Biasa)**\n    -   Special needs elementary school\n    -   Adapted curriculum for disabled students\n    -   Equivalent to SD grades 1-6\n    -   Individualized education programs\n\n### Secondary Education\n\n-   **SMP (Sekolah Menengah Pertama)**\n    -   Junior high school for ages 12-15\n    -   Grades 7-9\n    -   Advanced curriculum building on SD foundation\n-   **SMPLB (Sekolah Menengah Pertama Luar Biasa)**\n    -   Special needs junior high school\n    -   Modified curriculum for disabled students\n    -   Equivalent to SMP grades 7-9\n\n### Upper Secondary Education\n\n-   **SMA (Sekolah Menengah Atas)**\n    -   Academic senior high school for ages 15-18\n    -   Grades 10-12\n    -   Streams: Natural Sciences (IPA), Social Sciences (IPS), Language\n    -   University preparation focus\n-   **SMK (Sekolah Menengah Kejuruan)**\n    -   Vocational high school\n    -   Ages 15-18\n    -   Career-oriented curriculum\n    -   Direct workforce preparation\n\n### Special Education\n\n-   **SMLB (Sekolah Menengah Luar Biasa)**\n\n    -   Special needs senior high school\n    -   Equivalent to SMA/SMK grades 10-12\n    -   Customized curriculum\n\n-   **SLB (Sekolah Luar Biasa)**\n\n    -   Comprehensive special education\n    -   Covers all education levels\n    -   Specialized support services\n    -   Individualized learning programs\n\n# Data Loading and Processing\n\nThe foundation of our spatial analysis rests on the careful preparation and integration of multiple datasets that capture Jakarta's educational landscape. This section details the systematic process of loading, cleaning, and standardizing three key data sources:\n\n1.  A comprehensive database of Indonesian schools from Kaggle\n2.  Administrative boundary data at the city level (ADM2)\n3.  Detailed village-level (kelurahan) boundary data\n\nOur primary objectives in this data processing phase were to:\n\n-   Isolate and clean Jakarta's school data while excluding the Thousand Islands region\n\n-   Standardize administrative boundary information across different geographic scales\n\n-   Ensure consistent naming conventions across all datasets\n\n-   Establish proper spatial relationships through coordinate system alignment\n\nParticular attention was paid to creating meaningful categorical variables for school types and levels, while also incorporating crucial demographic information at the village level. This processed data provides the structured foundation necessary for our subsequent LISA and HCSA analyses, enabling us to meaningfully investigate spatial patterns in Jakarta's educational infrastructure.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required packages\npacman::p_load(\n  sf,              # For spatial data handling\n  tidyverse,       # Data manipulation and visualization\n  knitr,           # For report generation\n  viridis,         # Color palettes\n  patchwork,       # Combine multiple plots\n  gridExtra,       # Arrange multiple plots\n  kableExtra,      # Enhanced tables\n  sfdep,           # Spatial dependence functions\n  tmap,            # Thematic mapping\n  tmaptools,       # Additional mapping tools\n  scales,          # Scale functions for visualization\n  spdep,           # Spatial dependence testing\n  ggrepel,         # Text and label repulsion\n  spatstat,        # Point pattern analysis\n  GWmodel,         # Geographically weighted models\n  gtsummary,       # Summary statistics\n  olsrr,           # OLS regression\n  ClustGeo         # Geographical clustering\n)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load raw school data from Kaggle dataset\nindo_schools_kaggle <- read_csv(\"data/aspatial/complete_data.csv\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Process Jakarta schools data\njakarta_schools <- indo_schools_kaggle %>% \n  # Filter for Jakarta province, excluding Thousand Islands\n  filter(province_name == \"DKI JAKARTA\",\n         city_name != \"Kab. Kepulauan Seribu\") %>%\n  # Remove entries with missing coordinates\n  filter(!is.na(long) & !is.na(lat)) %>%\n  # Convert to spatial features (sf) object\n  st_as_sf(coords = c(\"long\", \"lat\"), crs = 4326) %>%\n  # Create new categorical variables for school level and type\n  mutate(\n      school_level = case_when(\n        stage %in% c(\"SD\", \"SDLB\") ~ \"Elementary\",\n        stage %in% c(\"SMP\", \"SMPLB\") ~ \"Junior High\",\n        stage %in% c(\"SMA\", \"SMK\", \"SMLB\") ~ \"Senior High\",\n        TRUE ~ \"Special Education\"\n      ),\n      school_type = if_else(status == \"N\", \"Public\", \"Private\")\n    )\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load and filter administrative boundary data (ADM2 level)\nadm2 <- st_read(\"data/geospatial\", layer = \"geoBoundaries-IDN-ADM2_simplified\") %>%\n  # Select only Jakarta's five administrative cities\n  filter(shapeName %in% c(\n      \"Kota Jakarta Barat\", \"Kota Jakarta Pusat\",\n      \"Kota Jakarta Selatan\", \"Kota Jakarta Timur\",\n      \"Kota Jakarta Utara\"\n    ))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `geoBoundaries-IDN-ADM2_simplified' from data source \n  `C:\\zcchong\\IS415\\Takehome_Ex\\Takehome_Ex3\\data\\geospatial' \n  using driver `ESRI Shapefile'\nSimple feature collection with 519 features and 5 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 95.01115 ymin: -11.00762 xmax: 141.0194 ymax: 6.07693\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load and process detailed village-level boundary data\nbatas <- st_read(\"data/geospatial\", layer = \"BATAS_DESA_DESEMBER_2019_DUKCAPIL_DKI_JAKARTA\")  %>%\n    # Select relevant columns and rename for clarity\n    select(OBJECT_ID, PROVINSI, KAB_KOTA, KECAMATAN, DESA_KELUR, \n         JUMLAH_PEN, JUMLAH_KK, LUAS_WILAY, KEPADATAN, geometry) %>%\n    rename(\n      province = PROVINSI,\n      city = KAB_KOTA,\n      district = KECAMATAN,\n      subdistrict = DESA_KELUR,\n      population = JUMLAH_PEN,\n      total_families = JUMLAH_KK,\n      area_size = LUAS_WILAY,\n      popn_density = KEPADATAN\n    ) %>%\n    # Remove Thousand Islands and missing values\n    filter(!is.na(city) & city != \"KEPULAUAN SERIBU\") %>%\n    # Standardize city names\n    mutate(city = case_when(\n      city == \"JAKARTA BARAT\" ~ \"Kota Jakarta Barat\",\n      city == \"JAKARTA PUSAT\" ~ \"Kota Jakarta Pusat\",\n      city == \"JAKARTA SELATAN\" ~ \"Kota Jakarta Selatan\",\n      city == \"JAKARTA TIMUR\" ~ \"Kota Jakarta Timur\",\n      city == \"JAKARTA UTARA\" ~ \"Kota Jakarta Utara\",\n      TRUE ~ city\n    ))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `BATAS_DESA_DESEMBER_2019_DUKCAPIL_DKI_JAKARTA' from data source \n  `C:\\zcchong\\IS415\\Takehome_Ex\\Takehome_Ex3\\data\\geospatial' \n  using driver `ESRI Shapefile'\nSimple feature collection with 269 features and 161 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 106.3831 ymin: -6.370815 xmax: 106.9728 ymax: -5.184322\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create district name mapping for standardization\ndistrict_mapping <- c(\n    \"TAMAN SARI\" = \"Kec. Taman Sari\",\n    \"KEMAYORAN\" = \"Kec. Kemayoran\",\n    \"SAWAH BESAR\" = \"Kec. Sawah Besar\",\n    \"GAMBIR\" = \"Kec. Gambir\",\n    \"SENEN\" = \"Kec. Senen\",\n    \"CEMPAKA PUTIH\" = \"Kec. Cempaka Putih\",\n    \"MENTENG\" = \"Kec. Menteng\",\n    \"TANAH ABANG\" = \"Kec. Tanah Abang\",\n    \"JOHAR BARU\" = \"Kec. Johar Baru\",\n    \"KOJA\" = \"Kec. Koja\",\n    \"PENJARINGAN\" = \"Kec. Penjaringan\",\n    \"TANJUNG PRIOK\" = \"Kec. Tanjung Priok\",\n    \"CILINCING\" = \"Kec. Cilincing\",\n    \"GROGOL PETAMBURAN\" = \"Kec. Grogol Petamburan\",\n    \"PADEMANGAN\" = \"Kec. Pademangan\",\n    \"KELAPA GADING\" = \"Kec. Kelapa Gading\",\n    \"CENGKARENG\" = \"Kec. Cengkareng\",\n    \"TAMBORA\" = \"Kec. Tambora\",\n    \"KEBON JERUK\" = \"Kec. Kebon Jeruk\",\n    \"KALIDERES\" = \"Kec. Kali Deres\",\n    \"PAL MERAH\" = \"Kec. Palmerah\",\n    \"JATINEGARA\" = \"Kec. Jatinegara\",\n    \"KEMBANGAN\" = \"Kec. Kembangan\",\n    \"TEBET\" = \"Kec. Tebet\",\n    \"SETIABUDI\" = \"Kec. Setia Budi\",\n    \"MAMPANG PRAPATAN\" = \"Kec. Mampang Prapatan\",\n    \"PASAR MINGGU\" = \"Kec. Pasar Minggu\",\n    \"KEBAYORAN LAMA\" = \"Kec. Kebayoran Lama\",\n    \"KEBAYORAN BARU\" = \"Kec. Kebayoran Baru\",\n    \"CILANDAK\" = \"Kec. Cilandak\",\n    \"PESANGGRAHAN\" = \"Kec. Pesanggrahan\",\n    \"PANCORAN\" = \"Kec. Pancoran\",\n    \"JAGAKARSA\" = \"Kec. Jagakarsa\",\n    \"MATRAMAN\" = \"Kec. Matraman\",\n    \"PULOGADUNG\" = \"Kec. Pulo Gadung\",\n    \"KRAMATJATI\" = \"Kec. Kramat Jati\",\n    \"PASAR REBO\" = \"Kec. Pasar Rebo\",\n    \"DUREN SAWIT\" = \"Kec. Duren Sawit\",\n    \"MAKASAR\" = \"Kec. Makasar\",\n    \"CIRACAS\" = \"Kec. Ciracas\",\n    \"CIPAYUNG\" = \"Kec. Cipayung\",\n    \"CAKUNG\" = \"Kec. Cakung\"\n)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Apply district name standardization\nbatas <- batas %>%\n  mutate(district = district_mapping[district])\n```\n:::\n\n\n# Exploratory Data Analysis at the Provincial Level\n\nBefore diving into complex spatial statistics, we begin with an exploratory data analysis (EDA) at the provincial level to understand the basic distribution patterns of schools across Jakarta.\n\nThis initial exploration focuses on four key aspects:\n\n-   The overall distribution of schools across Jakarta's administrative cities,\n\n-   The composition of different school levels in each city,\n\n-   The spatial density of schools,\n\n-   The relationship between school distribution and population density.\n\n## Overall Distribution of Schools\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot 1: Basic distribution of schools across cities\nggplot(data = jakarta_schools) +\n  # Create bar chart counting schools per city\n  geom_bar(aes(x = city_name, fill = city_name)) +\n  # Use plasma color palette for distinction\n  scale_fill_viridis_d(option = \"plasma\") +\n  theme_minimal() +\n  theme(\n    # Rotate x-axis labels for better readability\n    axis.text.x = element_text(angle = 45, hjust = 1),\n    plot.title = element_text(size = 12, face = \"bold\"),\n    # Remove redundant legend\n    legend.position = \"none\"\n  ) +\n  labs(\n    title = \"Distribution of Schools Across Jakarta\",\n    x = \"City\",\n    y = \"Number of Schools\"\n  )\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex3_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n## Distribution of School Levels\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot 2: Distribution of school levels by city\nggplot(data = jakarta_schools) +\n  # Stacked bar chart showing school level composition\n  geom_bar(aes(x = city_name, fill = school_level)) +\n  scale_fill_viridis_d(option = \"plasma\") +\n  theme_minimal() +\n  theme(\n    axis.text.x = element_text(angle = 45, hjust = 1),\n    plot.title = element_text(size = 12, face = \"bold\")\n  ) +\n  labs(\n    title = \"Distribution of School Levels Across Jakarta\",\n    x = \"City\",\n    y = \"Number of Schools\",\n    fill = \"School Level\"\n  )\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex3_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n## School Density Across Jakarta\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot 3: Spatial distribution of schools\nggplot() +\n  # Create choropleth map using administrative boundaries\n  geom_sf(data = adm2, \n          # Count number of schools in each administrative region\n          aes(fill = lengths(st_intersects(adm2, jakarta_schools)))) +\n  scale_fill_viridis_c(option = \"plasma\") +\n  theme_minimal() +\n  labs(\n    title = \"School Density Across Jakarta\",\n    fill = \"Number of\\nSchools\"\n  )\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex3_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n## Population Density in Jakarta\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot 4: Population density distribution\nggplot() +\n  # Create choropleth map of population density\n  geom_sf(data = batas, aes(fill = popn_density)) +\n  scale_fill_viridis_c(\n    option = \"plasma\",\n    # Format large numbers with commas\n    labels = scales::comma_format()\n  ) +\n  theme_minimal() +\n  labs(\n    title = \"Population Density in Jakarta\",\n    fill = \"Population\\nDensity\\n(per km²)\"\n  )\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex3_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n### Key Insights\n\n1.  **Geographic Disparities**: There are clear disparities in school distribution across Jakarta's regions, which may require attention from educational planners.\n\n2.  **Educational Level Balance**: While elementary schools dominate, there appears to be a reasonable distribution across educational levels, though some areas might benefit from more balanced development.\n\n# Kernel Density Estimation Analysis at Provincial Level\n\nFollowing our initial exploratory analysis, we employ Kernel Density Estimation (KDE) to gain a more nuanced understanding of school distribution patterns across Jakarta. KDE is particularly valuable for this analysis as it helps identify areas of high and low school concentration by creating a continuous surface of density estimates.\\\n\nThis technique goes beyond simple point mapping by considering the spatial influence of each school location on its surroundings, effectively highlighting clusters and gaps in educational infrastructure. By converting our data to UTM projection and applying appropriate edge corrections, we ensure accurate distance calculations and reliable density estimates, especially near the study area boundaries.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert coordinate systems for accurate distance measurement\n# UTM Zone 48S (EPSG:32748) is appropriate for Jakarta\njakarta_schools_utm <- st_transform(jakarta_schools, 32748)\nadm2_utm <- st_transform(adm2, 32748)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract coordinates and add small random noise to prevent exact duplicates\n# This helps avoid computational issues in point pattern analysis\ncoords <- st_coordinates(jakarta_schools_utm)\njittered_coords <- coords + matrix(\n  runif(nrow(coords) * 2, -0.1, 0.1),  # Add noise between -0.1 and 0.1 meters\n  ncol = 2\n)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create observation window from administrative boundary\n# This defines the study area for the point pattern analysis\nwindow <- as.owin(st_union(adm2_utm))\n\n# Filter points to ensure they fall within the study area\n# This step is crucial for accurate density estimation\ninside <- inside.owin(x = jittered_coords[,1], \n                     y = jittered_coords[,2], \n                     w = window)\nvalid_coords <- jittered_coords[inside,]\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create point pattern object for spatial statistics\npoints <- ppp(\n  x = valid_coords[,1],\n  y = valid_coords[,2],\n  window = window\n)\n\n# Diagnostic prints to verify data integrity\nprint(paste(\"Original points:\", nrow(coords)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Original points: 4762\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(paste(\"Points in window:\", sum(inside)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Points in window: 4734\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(paste(\"Duplicated points:\", sum(duplicated(valid_coords))))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Duplicated points: 0\"\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Perform kernel density estimation\n# bw.diggle provides data-driven bandwidth selection\n# edge=TRUE applies edge correction for boundary effects\nkde <- density.ppp(points, \n                  sigma = bw.diggle(points),\n                  edge = TRUE)\n\n# Convert KDE results to data frame for further analysis/visualization\nkde_df <- as.data.frame(kde)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot() +\n  geom_sf(data = adm2_utm, fill = \"transparent\") +\n  geom_tile(data = kde_df, aes(x = x, y = y, fill = value)) +\n  scale_fill_viridis_c(option = \"plasma\") +\n  theme_minimal() +\n  labs(\n    title = \"Kernel Density Estimation of All Schools\",\n    subtitle = paste0(\"Based on \", sum(inside), \" school locations\"),\n    fill = \"Density\"\n  )\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex3_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n# \n\n### Distribution Patterns\n\nThe KDE analysis of 4,734 schools across Jakarta shows:\n\n1.  **High-Density Clusters (Yellow/Orange)**\n    -   Several distinct hotspots visible across the map\n    -   Particularly noticeable in scattered locations across the northern and central regions\n    -   Maximum density reaches 0.00015 schools per square meter\n2.  **Medium-Density Areas (Pink/Light Purple)**\n    -   Form connecting networks between the high-density clusters\n    -   More prevalent in the central portions of the map\n3.  **Low-Density Regions (Dark Purple)**\n    -   Large portions of Jakarta, especially in the southern regions\n    -   Shows minimal school presence compared to other areas\n\nThe distribution appears notably clustered rather than uniform, suggesting spatial variations in school accessibility across different parts of Jakarta.\n\n#### 1.2.2 KDE by School Level\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create an empty list to store KDE plots for each school level\nkde_plots <- list()\n\n# Iterate through each unique school level in the dataset\nfor(level in unique(jakarta_schools_utm$school_level)) {\n  # Filter schools for current level\n  schools_subset <- jakarta_schools_utm[jakarta_schools_utm$school_level == level,]\n  \n  # Extract coordinates from spatial data\n  coords <- st_coordinates(schools_subset)\n  \n  # Add small random noise to prevent exact duplicates\n  # Important for computational stability\n  jittered_coords <- coords + matrix(\n    runif(nrow(coords) * 2, -0.1, 0.1),  # Random noise between -0.1 and 0.1 meters\n    ncol = 2\n  )\n  \n  # Check which points fall within study area boundary\n  inside <- inside.owin(x = jittered_coords[,1],\n                       y = jittered_coords[,2],\n                       w = window)\n  valid_coords <- jittered_coords[inside,]\n  \n  # Create point pattern object for spatial analysis\n  points_subset <- ppp(\n    x = valid_coords[,1],\n    y = valid_coords[,2],\n    window = window\n  )\n  \n  # Perform kernel density estimation\n  # Using Diggle's method for bandwidth selection\n  # Edge correction applied for boundary effects\n  kde_level <- density.ppp(points_subset,\n                          sigma = bw.diggle(points_subset),\n                          edge = TRUE)\n  \n  # Convert KDE results to data frame for plotting\n  kde_df <- as.data.frame(kde_level)\n  \n  # Create density plot using ggplot2\n  kde_plots[[level]] <- ggplot() +\n    # Add administrative boundaries\n    geom_sf(data = adm2_utm, fill = \"transparent\") +\n    # Add density heatmap\n    geom_tile(data = kde_df, aes(x = x, y = y, fill = value)) +\n    # Use plasma color scheme for density visualization\n    scale_fill_viridis_c(option = \"plasma\") +\n    theme_minimal() +\n    labs(\n      title = paste(\"School Density:\", level),\n      # Show number of schools included in analysis\n      subtitle = paste0(\"Based on \", sum(inside), \" school locations\"),\n      fill = \"Density\"\n    )\n}\n\nwalk(kde_plots, print)\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex3_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex3_files/figure-html/unnamed-chunk-18-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex3_files/figure-html/unnamed-chunk-18-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex3_files/figure-html/unnamed-chunk-18-4.png){width=672}\n:::\n:::\n\n\n### Numbers and Coverage\n\n-   Elementary (2,585 schools): Most widely distributed, showing small scattered hotspots across Jakarta\n-   Junior High (1,025 schools): Strong clustering pattern, with prominent hotspots in central areas\n-   Senior High (1,044 schools): Concentrated clusters, particularly in northern and central regions\n-   Special Education (80 schools): Limited coverage with sparse distribution\n\n### \n\n# Exploratory Data Analysis at the City Level\n\n## School Distribution by City\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert boundaries to UTM projection for accurate spatial operations\nbatas_utm <- st_transform(batas, 32748)\n\n# Initialize list to store individual city maps\ncity_maps <- list()\n\n# Create separate maps for each city\nfor(city in unique(batas$city)) {\n  # Extract boundary for current city\n  city_boundary <- batas_utm[batas_utm$city == city,]\n  \n  # Find schools within current city boundary\n  city_schools <- jakarta_schools_utm[st_intersects(jakarta_schools_utm, \n                                                   st_union(city_boundary)) %>% \n                                      lengths > 0,]\n  \n  # Create map for current city\n  city_maps[[city]] <- ggplot() +\n    # Add population density choropleth\n    geom_sf(data = city_boundary, \n            aes(fill = popn_density)) +\n    # Add school points colored by level\n    geom_sf(data = city_schools,\n            aes(color = school_level),\n            size = 2,\n            alpha = 0.6) +\n    # Set color scales\n    scale_fill_viridis_c(\n      option = \"plasma\",\n      name = \"Population\\nDensity\",\n      labels = scales::comma_format()\n    ) +\n    scale_color_viridis_d(\n      option = \"plasma\",\n      name = \"School Level\"\n    ) +\n    # Customize theme\n    theme_minimal() +\n    theme(\n      plot.title = element_text(size = 14, face = \"bold\"),\n      plot.subtitle = element_text(size = 12),\n      legend.title = element_text(size = 10),\n      legend.text = element_text(size = 8),\n      plot.margin = margin(10, 10, 10, 10)\n    ) +\n    labs(\n      title = paste(\"Schools Distribution in\", city)\n    )\n}\n\n# Display all city maps\nwalk(names(city_maps), function(city) {\n  print(city_maps[[city]])\n})\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex3_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex3_files/figure-html/unnamed-chunk-19-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex3_files/figure-html/unnamed-chunk-19-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex3_files/figure-html/unnamed-chunk-19-4.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex3_files/figure-html/unnamed-chunk-19-5.png){width=672}\n:::\n:::\n\n\n## Public School Ratio by City\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate the proportion of public schools for each city\npublic_ratio <- jakarta_schools_utm %>%\n  # Group data by city\n  group_by(city_name) %>%\n  # Calculate summary statistics\n  summarise(\n    total_schools = n(),                                    # Total number of schools\n    public_schools = sum(school_type == \"Public\"),          # Count of public schools\n    public_ratio = public_schools / total_schools,          # Calculate proportion\n    .groups = \"drop\"                                        # Drop grouping\n  )\n\n# Create bar plot of public school ratios\nggplot(public_ratio) +\n  # Create bars, reordered by public_ratio\n  geom_bar(aes(x = reorder(city_name, public_ratio),       # Order bars by ratio\n               y = public_ratio, \n               fill = city_name), \n           stat = \"identity\") +\n  # Use plasma color palette from viridis\n  scale_fill_viridis_d(option = \"plasma\") +\n  # Apply minimal theme\n  theme_minimal() +\n  # Customize theme elements\n  theme(\n    axis.text.x = element_text(angle = 45, hjust = 1),     # Rotate x-axis labels\n    legend.position = \"none\",                               # Remove legend\n    plot.title = element_text(size = 14, face = \"bold\"),   # Format title\n    plot.subtitle = element_text(size = 12)                 # Format subtitle\n  ) +\n  # Add plot labels\n  labs(\n    title = \"Public School Ratio by City\",\n    subtitle = \"Proportion of public schools to total schools\",\n    x = \"City\",\n    y = \"Proportion of Public Schools\"\n  )\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex3_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n### Public School Ratio Analysis - Key Findings\n\n#### Distribution Across Cities\n\n-   **Highest Ratio**: Kota Jakarta Selatan (\\~52% public schools)\n-   **Lowest Ratio**: Kota Jakarta Utara (\\~38% public schools)\n-   **Overall Range**: \\~14% difference between highest and lowest\n\n#### City-Specific Breakdown\n\n1.  **Kota Jakarta Selatan** (Pink)\n    -   Highest proportion of public schools (\\~52%)\n    -   Suggests strongest public education presence\n2.  **Kota Jakarta Timur** (Orange)\n    -   Second-highest ratio (\\~51%)\n    -   Nearly matches South Jakarta's public school proportion\n3.  **Kota Jakarta Pusat** (Purple)\n    -   Middle range (\\~50%)\n    -   Shows balanced public-private distribution\n4.  **Kota Jakarta Barat** (Dark Blue)\n    -   Lower ratio (\\~40%)\n    -   Shows stronger private school presence\n5.  **Kota Jakarta Utara** (Yellow)\n    -   Lowest public school ratio (\\~38%)\n    -   Indicates dominance of private education providers\n\n# Kernel Density Estimation Analysis at City Level\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Initialize list to store KDE results for each city\nkde_city_level <- list()\n\n# Perform KDE analysis for each city\nfor(city in unique(jakarta_schools_utm$city_name)) {\n  # Filter data for current city\n  city_schools <- jakarta_schools_utm[jakarta_schools_utm$city_name == city,]\n  city_boundary <- adm2_utm[adm2_utm$shapeName == city,]\n  city_window <- as.owin(st_union(city_boundary))\n  \n  # Calculate window size for bandwidth consideration\n  win_size <- sqrt(area.owin(city_window))\n  \n  kde_city_level[[city]] <- list()\n  \n  # Process all schools in city\n  coords <- st_coordinates(city_schools)\n  jittered_coords <- coords + matrix(\n    runif(nrow(coords) * 2, -0.1, 0.1),  # Add small random noise\n    ncol = 2\n  )\n  \n  # Filter valid points\n  inside <- inside.owin(x = jittered_coords[,1],\n                       y = jittered_coords[,2],\n                       w = city_window)\n  valid_coords <- jittered_coords[inside,]\n  \n  # Perform KDE if enough points available\n  if(nrow(valid_coords) >= 4) {\n    points_ppp <- ppp(\n      x = valid_coords[,1],\n      y = valid_coords[,2],\n      window = city_window\n    )\n    \n    # Calculate bandwidth using Scott's rule\n    h <- bw.scott(points_ppp)\n    kde <- density.ppp(points_ppp, \n                      sigma = h,\n                      edge = TRUE,\n                      at = \"pixels\",\n                      dimyx = c(128, 128))\n    \n    kde_city_level[[city]][[\"All\"]] <- list(\n      kde = kde,\n      n_points = nrow(valid_coords),\n      bandwidth = h\n    )\n  }\n  \n  # Repeat analysis for each school level\n  for(level in unique(city_schools$school_level)) {\n    level_schools <- city_schools[city_schools$school_level == level,]\n    coords <- st_coordinates(level_schools)\n    \n    # Add jitter and filter points\n    jittered_coords <- coords + matrix(\n      runif(nrow(coords) * 2, -0.1, 0.1),\n      ncol = 2\n    )\n    \n    inside <- inside.owin(x = jittered_coords[,1],\n                         y = jittered_coords[,2],\n                         w = city_window)\n    valid_coords <- jittered_coords[inside,]\n    \n    # Perform KDE if enough points\n    if(nrow(valid_coords) >= 4) {\n      points_ppp <- ppp(\n        x = valid_coords[,1],\n        y = valid_coords[,2],\n        window = city_window\n      )\n      \n      h <- bw.scott(points_ppp)\n      kde <- density.ppp(points_ppp, \n                        sigma = h,\n                        edge = TRUE,\n                        at = \"pixels\",\n                        dimyx = c(128, 128))\n      \n      kde_city_level[[city]][[level]] <- list(\n        kde = kde,\n        n_points = nrow(valid_coords),\n        bandwidth = h\n      )\n    }\n  }\n}\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate and store density metrics\ndensity_metrics <- data.frame(\n  city = character(),\n  level = character(),\n  max_density = numeric(),\n  mean_density = numeric(),\n  relative_density = numeric(),\n  stringsAsFactors = FALSE\n)\n\n# Calculate relative densities for each city and school level\nfor(city in names(kde_city_level)) {\n  city_max <- max(kde_city_level[[city]][[\"All\"]]$kde$v, na.rm = TRUE)\n  \n  for(level in names(kde_city_level[[city]])) {\n    if(level != \"All\") {\n      kde_data <- kde_city_level[[city]][[level]]\n      \n      density_metrics <- rbind(density_metrics, data.frame(\n        city = city,\n        level = level,\n        max_density = max(kde_data$kde$v, na.rm = TRUE),\n        mean_density = mean(kde_data$kde$v, na.rm = TRUE),\n        relative_density = max(kde_data$kde$v, na.rm = TRUE) / city_max,\n        stringsAsFactors = FALSE\n      ))\n    }\n  }\n}\n\n# Create visualization of relative densities\nggplot(density_metrics, \n       aes(x = level, y = relative_density, fill = city)) +\n  geom_bar(stat = \"identity\", position = \"dodge\") +\n  scale_fill_viridis_d(option = \"plasma\") +\n  theme_minimal() +\n  theme(\n    axis.text.x = element_text(angle = 45, hjust = 1),\n    plot.title = element_text(size = 16, face = \"bold\"),\n    axis.title = element_text(size = 12),\n    legend.title = element_text(size = 12),\n    legend.text = element_text(size = 10),\n    plot.margin = margin(20, 20, 20, 20)\n  ) +\n  labs(\n    title = \"Relative Density of School Types by City\",\n    subtitle = \"Maximum density relative to overall school density\",\n    x = \"School Level\",\n    y = \"Relative Density\",\n    fill = \"City\"\n  )\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex3_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n## \n\n## Key Findings - Relative Density Analysis\n\n### School Level Patterns\n\n1.  **Elementary Schools**\n    -   Highest relative density across all cities (\\~0.6-0.7)\n    -   Kota Jakarta Pusat shows highest concentration\n    -   Relatively consistent across cities\n2.  **Secondary Education**\n    -   Junior High: Moderate density (\\~0.2) across all cities\n    -   Senior High: Similar pattern to Junior High but slightly lower\n    -   Consistent pattern across cities\n3.  **Special Education**\n    -   Lowest relative density (\\<0.1) in all cities\n    -   Minimal variation between cities\n\n### Overall Observations\n\n-   Clear hierarchical pattern: Elementary \\> Junior High \\> Senior High \\> Special Education\n-   Remarkably consistent patterns across all five cities\n-   Central Jakarta (Pusat) shows slightly higher densities across most school levels\n\n## \n\n# LISA Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Correct aggregation to maintain separate districts\ndistrict_boundaries <- batas_utm %>%\n  group_by(city, district) %>%\n  summarise(\n    total_population = sum(population),\n    total_area = sum(area_size),\n    popn_density = total_population / total_area,\n    # Maintain separate geometries for each district\n    do_union = TRUE,\n    .groups = 'drop'\n  )\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Spatial Analysis of Jakarta Educational Infrastructure\n\n# 1. Join school data with district boundaries\n# Purpose: Aggregate school-level data to district level\n# Input: jakarta_schools_utm (school points), district_boundaries (polygons)\n# Output: District-level summary statistics\ndistrict_schools <- st_join(jakarta_schools_utm, \n                           st_transform(district_boundaries, st_crs(jakarta_schools_utm))) %>%\n  st_drop_geometry() %>%\n  group_by(district) %>%\n  summarise(\n    # Count total schools and public schools\n    total_schools = n(),\n    public_schools = sum(school_type == \"Public\"),\n    \n    # Count schools by education level\n    elementary_count = sum(school_level == \"Elementary\"),\n    junior_high_count = sum(school_level == \"Junior High\"),\n    senior_high_count = sum(school_level == \"Senior High\"),\n    special_ed_count = sum(school_level == \"Special Education\")\n  )\n\n# 2. Calculate district-level metrics\n# Purpose: Compute density and ratio metrics for analysis\n# Output: District boundaries with added metrics\ndistrict_metrics <- district_boundaries %>%\n  left_join(district_schools, by = \"district\") %>%\n  mutate(\n    # Calculate school density (schools per square km)\n    school_density = total_schools / total_area,\n    elementary_density = elementary_count / total_area,\n    junior_high_density = junior_high_count / total_area,\n    senior_high_density = senior_high_count / total_area,\n    special_ed_density = special_ed_count / total_area,\n    \n    # Calculate public school ratio\n    public_ratio = public_schools / total_schools\n  )\n\n# 3. Create spatial weights matrix\n# Purpose: Define spatial relationships between districts\n# Method: Queen contiguity (districts sharing any boundary point are neighbors)\ndistrict_neighbors <- poly2nb(district_metrics, queen = TRUE)\ndistrict_weights <- nb2listw(district_neighbors, style = \"W\")\n\n# 4. Define metrics for analysis\n# List of variables to be analyzed with LISA statistics\nmetrics_to_analyze <- c(\n    \"school_density\",\n    \"elementary_density\",\n    \"junior_high_density\",\n    \"senior_high_density\",\n    \"special_ed_density\",\n    \"public_ratio\"\n)\n\n# 5. Calculate LISA statistics\n# Purpose: Identify spatial clusters and outliers\n# Method: Local Moran's I with significance testing\nlisa_results <- lapply(metrics_to_analyze, function(metric) {\n    # Calculate Local Moran's I\n    local_moran <- localmoran(district_metrics[[metric]], district_weights)\n    \n    # Calculate spatial lag for clustering\n    lag_var <- lag.listw(district_weights, district_metrics[[metric]])\n    \n    # Standardize variables for comparison\n    z_var <- scale(district_metrics[[metric]])\n    z_lag <- scale(lag_var)\n    \n    # Classify clusters based on significance (p < 0.05)\n    clusters <- rep(\"Not Significant\", length(z_var))\n    sig_indices <- which(local_moran[, \"Pr(z != E(Ii))\"] < 0.05)\n    \n    # Determine cluster types:\n    # High-High: High values surrounded by high values (hot spots)\n    # Low-Low: Low values surrounded by low values (cold spots)\n    # High-Low: High values surrounded by low values (spatial outliers)\n    # Low-High: Low values surrounded by high values (spatial outliers)\n    for(i in sig_indices) {\n        if(z_var[i] > 0 && z_lag[i] > 0) clusters[i] <- \"High-High\"\n        else if(z_var[i] < 0 && z_lag[i] < 0) clusters[i] <- \"Low-Low\"\n        else if(z_var[i] > 0 && z_lag[i] < 0) clusters[i] <- \"High-Low\"\n        else if(z_var[i] < 0 && z_lag[i] > 0) clusters[i] <- \"Low-High\"\n    }\n    \n    return(list(\n        clusters = clusters,\n        local_i = local_moran[, \"Ii\"],\n        p_values = local_moran[, \"Pr(z != E(Ii))\"]\n    ))\n})\nnames(lisa_results) <- metrics_to_analyze\n\n# 6. Create LISA maps\n# Purpose: Visualize spatial clusters and outliers\n# Output: ggplot maps for each metric\nlisa_maps <- lapply(metrics_to_analyze, function(metric) {\n    district_metrics$cluster <- lisa_results[[metric]]$clusters\n    \n    ggplot(district_metrics) +\n        geom_sf(aes(fill = cluster)) +\n        scale_fill_manual(values = c(\n            \"High-High\" = \"#FF0000\",    # Hot spots (red)\n            \"Low-Low\" = \"#0000FF\",      # Cold spots (blue)\n            \"High-Low\" = \"#FF69B4\",     # High outliers (pink)\n            \"Low-High\" = \"#87CEEB\",     # Low outliers (light blue)\n            \"Not Significant\" = \"#CCCCCC\" # Not significant (gray)\n        )) +\n        theme_minimal() +\n        labs(\n            title = paste(\"LISA Cluster Map:\", gsub(\"_\", \" \", metric)),\n            fill = \"Cluster Type\"\n        )\n})\nnames(lisa_maps) <- metrics_to_analyze\n\n# 7. Display maps\n# Print individual maps for each metric\nprint(lisa_maps$school_density)\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex3_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n\n```{.r .cell-code}\nprint(lisa_maps$elementary_density)\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex3_files/figure-html/unnamed-chunk-24-2.png){width=672}\n:::\n\n```{.r .cell-code}\nprint(lisa_maps$junior_high_density)\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex3_files/figure-html/unnamed-chunk-24-3.png){width=672}\n:::\n\n```{.r .cell-code}\nprint(lisa_maps$senior_high_density)\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex3_files/figure-html/unnamed-chunk-24-4.png){width=672}\n:::\n\n```{.r .cell-code}\nprint(lisa_maps$special_ed_density)\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex3_files/figure-html/unnamed-chunk-24-5.png){width=672}\n:::\n\n```{.r .cell-code}\nprint(lisa_maps$public_ratio)\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex3_files/figure-html/unnamed-chunk-24-6.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a summary of LISA cluster patterns for each metric\nlisa_summary <- lapply(metrics_to_analyze, function(metric) {\n    # Get cluster counts\n    cluster_counts <- table(lisa_results[[metric]]$clusters)\n    \n    # Calculate percentages\n    cluster_percentages <- prop.table(cluster_counts) * 100\n    \n    # Identify significant districts\n    significant_districts <- district_metrics$district[lisa_results[[metric]]$clusters != \"Not Significant\"]\n    \n    # Calculate global Moran's I\n    global_moran <- moran.test(district_metrics[[metric]], district_weights)\n    \n    # Return summary\n    list(\n        metric = metric,\n        cluster_counts = cluster_counts,\n        cluster_percentages = cluster_percentages,\n        significant_districts = significant_districts,\n        global_moran = global_moran\n    )\n})\nnames(lisa_summary) <- metrics_to_analyze\n\n# Print comprehensive analysis for each metric\nfor(metric in metrics_to_analyze) {\n    cat(\"\\n\\n=== Analysis for\", gsub(\"_\", \" \", metric), \"===\\n\")\n    \n    # Global spatial autocorrelation\n    cat(\"\\nGlobal Moran's I:\\n\")\n    cat(\"Value:\", round(lisa_summary[[metric]]$global_moran$estimate[1], 4), \"\\n\")\n    cat(\"p-value:\", round(lisa_summary[[metric]]$global_moran$p.value, 4), \"\\n\")\n    \n    # Cluster distribution\n    cat(\"\\nCluster Distribution:\\n\")\n    print(round(lisa_summary[[metric]]$cluster_percentages, 2))\n    \n    # List significant clusters\n    cat(\"\\nSignificant Districts:\\n\")\n    for(district in lisa_summary[[metric]]$significant_districts) {\n        cluster_type <- lisa_results[[metric]]$clusters[district_metrics$district == district]\n        cat(sprintf(\"%s: %s\\n\", district, cluster_type))\n    }\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\n=== Analysis for school density ===\n\nGlobal Moran's I:\nValue: 0.2536 \np-value: 0.0013 \n\nCluster Distribution:\n\n      High-High        Low-High Not Significant \n           7.14            4.76           88.10 \n\nSignificant Districts:\nKec. Cempaka Putih: High-High\nKec. Gambir: Low-High\nKec. Johar Baru: High-High\nKec. Senen: High-High\nKec. Pademangan: Low-High\n\n\n=== Analysis for elementary density ===\n\nGlobal Moran's I:\nValue: 0.2306 \np-value: 0.0024 \n\nCluster Distribution:\n\n      High-High        Low-High Not Significant \n           4.76            7.14           88.10 \n\nSignificant Districts:\nKec. Cempaka Putih: Low-High\nKec. Gambir: Low-High\nKec. Johar Baru: High-High\nKec. Senen: High-High\nKec. Pademangan: Low-High\n\n\n=== Analysis for junior high density ===\n\nGlobal Moran's I:\nValue: 0.2588 \np-value: 0.0011 \n\nCluster Distribution:\n\n      High-High        Low-High         Low-Low Not Significant \n           7.14            4.76            2.38           85.71 \n\nSignificant Districts:\nKec. Gambir: High-High\nKec. Johar Baru: High-High\nKec. Senen: High-High\nKec. Kramat Jati: Low-Low\nKec. Pademangan: Low-High\nKec. Penjaringan: Low-High\n\n\n=== Analysis for senior high density ===\n\nGlobal Moran's I:\nValue: 0.2148 \np-value: 0.0051 \n\nCluster Distribution:\n\n      High-High        Low-High Not Significant \n           9.52            2.38           88.10 \n\nSignificant Districts:\nKec. Cempaka Putih: High-High\nKec. Gambir: High-High\nKec. Sawah Besar: High-High\nKec. Senen: High-High\nKec. Pademangan: Low-High\n\n\n=== Analysis for special ed density ===\n\nGlobal Moran's I:\nValue: -0.0218 \np-value: 0.4891 \n\nCluster Distribution:\n\n       High-Low        Low-High Not Significant \n           2.38            2.38           95.24 \n\nSignificant Districts:\nKec. Kemayoran: High-Low\nKec. Jatinegara: Low-High\n\n\n=== Analysis for public ratio ===\n\nGlobal Moran's I:\nValue: 0.2126 \np-value: 0.0053 \n\nCluster Distribution:\n\n      High-High        High-Low         Low-Low Not Significant \n           2.38            4.76            7.14           85.71 \n\nSignificant Districts:\nKec. Cengkareng: Low-Low\nKec. Gambir: Low-Low\nKec. Kramat Jati: High-High\nKec. Koja: High-Low\nKec. Pademangan: High-Low\nKec. Penjaringan: Low-Low\n```\n\n\n:::\n\n```{.r .cell-code}\n# Create numeric dataframe for correlation\nmetric_data <- data.frame(\n    school_density = as.numeric(district_metrics$school_density),\n    elementary_density = as.numeric(district_metrics$elementary_density),\n    junior_high_density = as.numeric(district_metrics$junior_high_density),\n    senior_high_density = as.numeric(district_metrics$senior_high_density),\n    special_ed_density = as.numeric(district_metrics$special_ed_density),\n    public_ratio = as.numeric(district_metrics$public_ratio)\n)\n\n# Calculate correlation matrix\ncorrelation_matrix <- cor(metric_data, use = \"complete.obs\")\nprint(round(correlation_matrix, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                    school_density elementary_density junior_high_density\nschool_density               1.000              0.978               0.898\nelementary_density           0.978              1.000               0.817\njunior_high_density          0.898              0.817               1.000\nsenior_high_density          0.849              0.740               0.803\nspecial_ed_density           0.306              0.266               0.211\npublic_ratio                 0.150              0.284              -0.151\n                    senior_high_density special_ed_density public_ratio\nschool_density                    0.849              0.306        0.150\nelementary_density                0.740              0.266        0.284\njunior_high_density               0.803              0.211       -0.151\nsenior_high_density               1.000              0.324       -0.102\nspecial_ed_density                0.324              1.000        0.175\npublic_ratio                     -0.102              0.175        1.000\n```\n\n\n:::\n:::\n\n\n## Key Findings from Spatial Analysis\n\n-   All school density metrics (except special education) show significant positive spatial autocorrelation (p \\< 0.01)\n-   Strongest clustering in:\n    -   Junior high density (Moran's I = 0.2588, p = 0.0011)\n    -   Overall school density (Moran's I = 0.2536, p = 0.0013)\n-   Special education shows no significant spatial pattern (Moran's I = -0.0218, p = 0.4891)\n\n## Cluster Patterns\n\n-   Central Jakarta districts consistently form hot spots:\n    -   Senen appears as High-High in school, elementary, junior high, and senior high density\n    -   Gambir shifts from Low-High in elementary to High-High in junior and senior high\n    -   Cempaka Putih shows mixed patterns across different school levels\n-   Pademangan consistently appears as a Low-High outlier across multiple metrics\n-   Very few High-Low outliers except in public ratio distribution\n\n## Correlation Analysis\n\n**Strong correlations:**\n\n-   Elementary and overall school density (r = 0.978)\n\n-   Junior high and overall school density (r = 0.898)\n\n-   Senior high and overall school density (r = 0.849)\n\n**Weak correlations:**\n\n-   Special education density with all other metrics (r \\< 0.35)\n\n-   Public ratio with all density metrics (r ranges from -0.151 to 0.284)\n\n# Getis-Ord G\\*\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate Getis-Ord G* statistics for each metric\ncalculate_g_star <- function(x, weights) {\n    # Standardize the variable\n    x_std <- scale(x)\n    \n    # Calculate G* statistic\n    g_star <- lag.listw(weights, x) / scale(x)[,1]\n    \n    # Calculate z-scores\n    n <- length(x)\n    W <- listw2mat(weights)\n    W2 <- W * W\n    S1 <- sum(W2)\n    \n    mean_g <- sum(W %*% x) / n\n    var_g <- S1 * (n - 1) / (n * n - 1)\n    z_scores <- (g_star - mean_g) / sqrt(var_g)\n    \n    # Calculate p-values\n    p_values <- 2 * pnorm(-abs(z_scores))\n    \n    # Classify hot and cold spots\n    classification <- rep(\"Not Significant\", length(z_scores))\n    classification[z_scores > 1.96 & p_values < 0.05] <- \"Hot Spot (95%)\"\n    classification[z_scores > 2.58 & p_values < 0.01] <- \"Hot Spot (99%)\"\n    classification[z_scores < -1.96 & p_values < 0.05] <- \"Cold Spot (95%)\"\n    classification[z_scores < -2.58 & p_values < 0.01] <- \"Cold Spot (99%)\"\n    \n    return(list(\n        g_star = g_star,\n        z_scores = z_scores,\n        p_values = p_values,\n        classification = classification\n    ))\n}\n\n# Apply G* analysis to each metric\ng_star_results <- lapply(metrics_to_analyze, function(metric) {\n    calculate_g_star(district_metrics[[metric]], district_weights)\n})\nnames(g_star_results) <- metrics_to_analyze\n\n# Create maps for G* results\ng_star_maps <- lapply(metrics_to_analyze, function(metric) {\n    district_metrics$hot_cold <- g_star_results[[metric]]$classification\n    \n    ggplot(district_metrics) +\n        geom_sf(aes(fill = hot_cold)) +\n        scale_fill_manual(values = c(\n            \"Hot Spot (99%)\" = \"#FF0000\",\n            \"Hot Spot (95%)\" = \"#FF6666\",\n            \"Cold Spot (99%)\" = \"#0000FF\",\n            \"Cold Spot (95%)\" = \"#6666FF\",\n            \"Not Significant\" = \"#CCCCCC\"\n        )) +\n        theme_minimal() +\n        labs(\n            title = paste(\"Hot Spot Analysis:\", gsub(\"_\", \" \", metric)),\n            subtitle = \"Getis-Ord G* Statistics\",\n            fill = \"Significance Level\"\n        )\n})\nnames(g_star_maps) <- metrics_to_analyze\n\n# Print maps\nfor(metric in metrics_to_analyze) {\n    print(g_star_maps[[metric]])\n}\n```\n\n::: {.cell-output-display}\n![](Takehome_Ex3_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex3_files/figure-html/unnamed-chunk-26-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex3_files/figure-html/unnamed-chunk-26-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex3_files/figure-html/unnamed-chunk-26-4.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex3_files/figure-html/unnamed-chunk-26-5.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Takehome_Ex3_files/figure-html/unnamed-chunk-26-6.png){width=672}\n:::\n\n```{.r .cell-code}\n# Print summary statistics\nfor(metric in metrics_to_analyze) {\n    cat(\"\\n\\n=== Hot Spot Analysis for\", gsub(\"_\", \" \", metric), \"===\\n\")\n    \n    # Print cluster counts\n    cluster_counts <- table(g_star_results[[metric]]$classification)\n    cluster_percentages <- prop.table(cluster_counts) * 100\n    \n    cat(\"\\nCluster Distribution:\\n\")\n    print(round(cluster_percentages, 2))\n    \n    # List significant districts\n    cat(\"\\nSignificant Districts:\\n\")\n    sig_districts <- district_metrics$district[g_star_results[[metric]]$classification != \"Not Significant\"]\n    sig_types <- g_star_results[[metric]]$classification[g_star_results[[metric]]$classification != \"Not Significant\"]\n    \n    for(i in seq_along(sig_districts)) {\n        cat(sprintf(\"%s: %s\\n\", sig_districts[i], sig_types[i]))\n    }\n    \n    # Print range of z-scores\n    cat(\"\\nZ-score range:\", \n        round(min(g_star_results[[metric]]$z_scores), 3), \"to\",\n        round(max(g_star_results[[metric]]$z_scores), 3), \"\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\n=== Hot Spot Analysis for school density ===\n\nCluster Distribution:\n\nCold Spot (99%)  Hot Spot (99%) Not Significant \n          76.19           21.43            2.38 \n\nSignificant Districts:\nKec. Cengkareng: Cold Spot (99%)\nKec. Grogol Petamburan: Hot Spot (99%)\nKec. Kali Deres: Cold Spot (99%)\nKec. Kebon Jeruk: Cold Spot (99%)\nKec. Kembangan: Cold Spot (99%)\nKec. Palmerah: Hot Spot (99%)\nKec. Taman Sari: Cold Spot (99%)\nKec. Tambora: Cold Spot (99%)\nKec. Cempaka Putih: Hot Spot (99%)\nKec. Gambir: Cold Spot (99%)\nKec. Johar Baru: Cold Spot (99%)\nKec. Kemayoran: Cold Spot (99%)\nKec. Menteng: Cold Spot (99%)\nKec. Sawah Besar: Hot Spot (99%)\nKec. Tanah Abang: Cold Spot (99%)\nKec. Cilandak: Cold Spot (99%)\nKec. Jagakarsa: Cold Spot (99%)\nKec. Kebayoran Baru: Cold Spot (99%)\nKec. Kebayoran Lama: Cold Spot (99%)\nKec. Mampang Prapatan: Cold Spot (99%)\nKec. Pancoran: Cold Spot (99%)\nKec. Pasar Minggu: Cold Spot (99%)\nKec. Pesanggrahan: Cold Spot (99%)\nKec. Setia Budi: Cold Spot (99%)\nKec. Tebet: Hot Spot (99%)\nKec. Cakung: Cold Spot (99%)\nKec. Cipayung: Cold Spot (99%)\nKec. Ciracas: Cold Spot (99%)\nKec. Duren Sawit: Hot Spot (99%)\nKec. Jatinegara: Hot Spot (99%)\nKec. Kramat Jati: Cold Spot (99%)\nKec. Makasar: Cold Spot (99%)\nKec. Matraman: Cold Spot (99%)\nKec. Pasar Rebo: Cold Spot (99%)\nKec. Pulo Gadung: Hot Spot (99%)\nKec. Cilincing: Cold Spot (99%)\nKec. Kelapa Gading: Cold Spot (99%)\nKec. Koja: Hot Spot (99%)\nKec. Pademangan: Cold Spot (99%)\nKec. Penjaringan: Cold Spot (99%)\nKec. Tanjung Priok: Cold Spot (99%)\n\nZ-score range: -939.718 to 721.451 \n\n\n=== Hot Spot Analysis for elementary density ===\n\nCluster Distribution:\n\nCold Spot (95%) Cold Spot (99%)  Hot Spot (99%) Not Significant \n           2.38           76.19           14.29            7.14 \n\nSignificant Districts:\nKec. Cengkareng: Cold Spot (99%)\nKec. Grogol Petamburan: Hot Spot (99%)\nKec. Kali Deres: Cold Spot (99%)\nKec. Kebon Jeruk: Cold Spot (99%)\nKec. Kembangan: Cold Spot (99%)\nKec. Palmerah: Hot Spot (99%)\nKec. Tambora: Cold Spot (99%)\nKec. Cempaka Putih: Cold Spot (99%)\nKec. Gambir: Cold Spot (99%)\nKec. Johar Baru: Cold Spot (99%)\nKec. Kemayoran: Cold Spot (99%)\nKec. Menteng: Cold Spot (99%)\nKec. Sawah Besar: Hot Spot (99%)\nKec. Tanah Abang: Cold Spot (99%)\nKec. Cilandak: Cold Spot (99%)\nKec. Jagakarsa: Cold Spot (99%)\nKec. Kebayoran Baru: Cold Spot (99%)\nKec. Kebayoran Lama: Cold Spot (99%)\nKec. Mampang Prapatan: Cold Spot (99%)\nKec. Pancoran: Cold Spot (99%)\nKec. Pasar Minggu: Cold Spot (99%)\nKec. Pesanggrahan: Cold Spot (99%)\nKec. Setia Budi: Cold Spot (99%)\nKec. Tebet: Hot Spot (99%)\nKec. Cakung: Cold Spot (99%)\nKec. Cipayung: Cold Spot (99%)\nKec. Ciracas: Cold Spot (99%)\nKec. Duren Sawit: Hot Spot (99%)\nKec. Jatinegara: Hot Spot (99%)\nKec. Kramat Jati: Cold Spot (99%)\nKec. Makasar: Cold Spot (99%)\nKec. Matraman: Cold Spot (95%)\nKec. Pasar Rebo: Cold Spot (99%)\nKec. Pulo Gadung: Cold Spot (99%)\nKec. Cilincing: Cold Spot (99%)\nKec. Kelapa Gading: Cold Spot (99%)\nKec. Pademangan: Cold Spot (99%)\nKec. Penjaringan: Cold Spot (99%)\nKec. Tanjung Priok: Cold Spot (99%)\n\nZ-score range: -117.542 to 103.285 \n\n\n=== Hot Spot Analysis for junior high density ===\n\nCluster Distribution:\n\nCold Spot (99%)  Hot Spot (99%) Not Significant \n          64.29           14.29           21.43 \n\nSignificant Districts:\nKec. Cengkareng: Hot Spot (99%)\nKec. Kali Deres: Cold Spot (99%)\nKec. Kebon Jeruk: Hot Spot (99%)\nKec. Kembangan: Cold Spot (99%)\nKec. Palmerah: Cold Spot (99%)\nKec. Tambora: Cold Spot (99%)\nKec. Gambir: Hot Spot (99%)\nKec. Menteng: Cold Spot (99%)\nKec. Tanah Abang: Cold Spot (99%)\nKec. Cilandak: Cold Spot (99%)\nKec. Jagakarsa: Cold Spot (99%)\nKec. Kebayoran Baru: Cold Spot (99%)\nKec. Kebayoran Lama: Cold Spot (99%)\nKec. Mampang Prapatan: Cold Spot (99%)\nKec. Pancoran: Cold Spot (99%)\nKec. Pasar Minggu: Cold Spot (99%)\nKec. Pesanggrahan: Cold Spot (99%)\nKec. Setia Budi: Cold Spot (99%)\nKec. Tebet: Hot Spot (99%)\nKec. Cakung: Cold Spot (99%)\nKec. Cipayung: Cold Spot (99%)\nKec. Ciracas: Cold Spot (99%)\nKec. Duren Sawit: Cold Spot (99%)\nKec. Kramat Jati: Cold Spot (99%)\nKec. Makasar: Cold Spot (99%)\nKec. Matraman: Hot Spot (99%)\nKec. Pasar Rebo: Cold Spot (99%)\nKec. Pulo Gadung: Hot Spot (99%)\nKec. Cilincing: Cold Spot (99%)\nKec. Kelapa Gading: Cold Spot (99%)\nKec. Pademangan: Cold Spot (99%)\nKec. Penjaringan: Cold Spot (99%)\nKec. Tanjung Priok: Cold Spot (99%)\n\nZ-score range: -2152.013 to 80.335 \n\n\n=== Hot Spot Analysis for senior high density ===\n\nCluster Distribution:\n\nCold Spot (95%) Cold Spot (99%)  Hot Spot (95%)  Hot Spot (99%) Not Significant \n           4.76           54.76            4.76           26.19            9.52 \n\nSignificant Districts:\nKec. Cengkareng: Cold Spot (99%)\nKec. Kali Deres: Cold Spot (99%)\nKec. Kebon Jeruk: Cold Spot (99%)\nKec. Kembangan: Cold Spot (99%)\nKec. Palmerah: Hot Spot (95%)\nKec. Tambora: Cold Spot (95%)\nKec. Cempaka Putih: Hot Spot (99%)\nKec. Gambir: Hot Spot (99%)\nKec. Johar Baru: Hot Spot (99%)\nKec. Menteng: Hot Spot (99%)\nKec. Sawah Besar: Hot Spot (95%)\nKec. Tanah Abang: Cold Spot (99%)\nKec. Cilandak: Cold Spot (99%)\nKec. Jagakarsa: Cold Spot (99%)\nKec. Kebayoran Baru: Hot Spot (99%)\nKec. Kebayoran Lama: Cold Spot (99%)\nKec. Mampang Prapatan: Cold Spot (99%)\nKec. Pancoran: Cold Spot (99%)\nKec. Pasar Minggu: Cold Spot (99%)\nKec. Pesanggrahan: Cold Spot (99%)\nKec. Setia Budi: Cold Spot (99%)\nKec. Tebet: Hot Spot (99%)\nKec. Cakung: Cold Spot (99%)\nKec. Cipayung: Cold Spot (99%)\nKec. Ciracas: Cold Spot (99%)\nKec. Duren Sawit: Hot Spot (99%)\nKec. Jatinegara: Hot Spot (99%)\nKec. Kramat Jati: Cold Spot (99%)\nKec. Makasar: Cold Spot (99%)\nKec. Matraman: Cold Spot (95%)\nKec. Pasar Rebo: Hot Spot (99%)\nKec. Pulo Gadung: Hot Spot (99%)\nKec. Cilincing: Cold Spot (99%)\nKec. Kelapa Gading: Cold Spot (99%)\nKec. Koja: Hot Spot (99%)\nKec. Pademangan: Cold Spot (99%)\nKec. Penjaringan: Cold Spot (99%)\nKec. Tanjung Priok: Cold Spot (99%)\n\nZ-score range: -1891.829 to 55.52 \n\n\n=== Hot Spot Analysis for special ed density ===\n\nCluster Distribution:\n\nCold Spot (95%)  Hot Spot (99%) Not Significant \n           2.38            9.52           88.10 \n\nSignificant Districts:\nKec. Menteng: Hot Spot (99%)\nKec. Jagakarsa: Cold Spot (95%)\nKec. Kebayoran Baru: Hot Spot (99%)\nKec. Kramat Jati: Hot Spot (99%)\nKec. Pasar Rebo: Hot Spot (99%)\n\nZ-score range: -2.134 to 9.612 \n\n\n=== Hot Spot Analysis for public ratio ===\n\nCluster Distribution:\n\nCold Spot (95%) Cold Spot (99%)  Hot Spot (99%) Not Significant \n           9.52           26.19            9.52           54.76 \n\nSignificant Districts:\nKec. Cengkareng: Cold Spot (95%)\nKec. Kali Deres: Cold Spot (95%)\nKec. Kebon Jeruk: Cold Spot (99%)\nKec. Kembangan: Cold Spot (99%)\nKec. Taman Sari: Cold Spot (95%)\nKec. Cempaka Putih: Cold Spot (99%)\nKec. Gambir: Cold Spot (99%)\nKec. Sawah Besar: Cold Spot (99%)\nKec. Senen: Cold Spot (99%)\nKec. Tanah Abang: Hot Spot (99%)\nKec. Cilandak: Cold Spot (99%)\nKec. Jagakarsa: Cold Spot (99%)\nKec. Kebayoran Baru: Cold Spot (99%)\nKec. Mampang Prapatan: Hot Spot (99%)\nKec. Pesanggrahan: Hot Spot (99%)\nKec. Cakung: Cold Spot (99%)\nKec. Duren Sawit: Hot Spot (99%)\nKec. Pulo Gadung: Cold Spot (95%)\nKec. Cilincing: Cold Spot (99%)\n\nZ-score range: -34.473 to 19.211 \n```\n\n\n:::\n:::\n\n\n## \n\n## Analysis of School Distribution Patterns in Jakarta\n\n### Junior High & Senior High School Patterns\n\n-   **Observed Pattern**: Both show central concentration (hot spots) but senior high schools have a more dispersed pattern with more transition zones\n-   **This could be because**:\n    -   Junior high students typically travel shorter distances, requiring more evenly spread schools\n    -   Senior high schools might be larger facilities serving wider areas\n    -   Senior high schools might be more specialized (science, vocational, etc.) leading to more varied locations\n\n### Special Education vs Regular Schools\n\n-   **Observed Pattern**: Special education shows minimal clustering with isolated hot spots, contrasting sharply with the clustered patterns of regular schools\n-   **This could be because**:\n    -   Special education facilities might be strategically placed to serve larger catchment areas\n    -   Each facility might be specialized for different needs, requiring broader distribution\n    -   Smaller target population might not require dense clustering\n\n### Public School Ratio Distribution\n\n-   **Observed Pattern**: Western districts show significant cold spots (low public ratio), while public school hot spots are scattered\n-   **This could be because**:\n    -   Different administrative approaches to school provision across districts\n    -   Private schools might be filling gaps in certain areas\n        -   Historical development patterns of school establishment\n\n### Transition Zones\n\n-   **Observed Pattern**: Areas of \"not significant\" clustering often appear between hot and cold spots, particularly in senior high and public ratio maps\n\n# Storyboard: Jakarta Schools Spatial Analysis Dashboard\n\n#### Background & Significance\n\nThe spatial distribution of schools across Jakarta, Indonesia's capital city, represents a critical aspect of educational accessibility and urban planning. Our proposed web application aims to provide interactive spatial analysis tools that enable stakeholders to understand and optimize educational resource distribution through Local Indicators of Spatial Association (LISA) and Hot-Spot Cold-Spot Analysis (HCSA).\n\n#### Motivation\n\nThis spatial analysis dashboard serves two critical purposes: identifying gaps in educational access across districts and providing data-driven insights for policy decisions.These capabilities directly enable stakeholders in:\n\n1.  **Achieving Educational Equity**\n\n    -   Helps identify areas of educational resource concentration and scarcity\n    -   Reveals potential gaps in school accessibility across different districts\n    -   Supports evidence-based decision making for new school placement\n    -   Highlights disparities between public and private school distribution\n\n2.  **Policy Implementation**\n\n    -   Supports data-driven educational policy decisions\n    -   Identifies priority areas for educational infrastructure development\n    -   Helps evaluate the effectiveness of current school distribution policies\n    -   Facilitates monitoring of educational access initiatives\n\n# UI Design\n\nThe latest interface design implementation can be accessed via the following link:\n<https://zcchong415.shinyapps.io/Takehome_Ex3/>\n\nThe corresponding source code and associated Shiny application files are located within the mockup directory on elearn.\n\n## Design Philosophy & Objectives\n\n### Design Philosophy\n\nThe district-level spatial analysis interface integrates Local Indicators of Spatial Association (LISA) and Hot-Spot Cold-Spot Analysis (HCSA) methodologies to enable comprehensive understanding of educational facility distribution patterns across Jakarta's districts, emphasizing analytical clarity while maintaining statistical rigor in the visualization and analysis process.\n\n### Core Design Objectives\n\n1.  The interface must deliver clear spatial visualizations that effectively communicate complex clustering patterns of educational facilities, enabling stakeholders to identify significant concentrations and gaps in educational resource distribution at the district level.\n\n2.  Statistical analysis tools need to be presented in an intuitive manner that allows users to seamlessly transition between LISA and HCSA methodologies while maintaining a clear understanding of the statistical significance and implications of their findings.\n\n3.  The visualization system must effectively represent cross-district relationships and boundary effects through clear color schemes and interactive elements, enabling users to understand how educational resource distribution patterns extend beyond individual district boundaries.\n\n4.  Parameter controls for both LISA and HCSA analyses must be designed to provide precise analytical control while remaining accessible to users with varying levels of statistical expertise, ensuring the interface serves both technical and policy-focused users.\n\n### Interactive Components & Controls\n\nThe interface incorporates three primary interactive control components designed to facilitate spatial analysis:\n\n1.  **Analysis Method Toggle**\n\n    \\- Enables users to switch between LISA and Hotspot (Getis-Ord) analysis methodologies\n\n    \\- Provides clear visual indication of currently selected analysis type\n\n2.  **Metric Selection**\n\n    \\- Offers multiple educational facility metrics for analysis\n\n    \\- Allows for single metric selection to maintain analysis clarity\n\n3.  **Significance Level Control**\n\n    \\- Enables adjustment of statistical significance threshold\n\n    \\- Includes visual feedback showing impact on result confidence\n\n    \\- Displays clear numerical representation of current significance level\n\n## Layout Architecture - Mock up 1\n\n### Spatial Organization\n\nThe interface utilizes a two-panel design structure that optimizes the analytical workflow while maintaining clear visual hierarchy and relationships between interface elements:\n\n```         \n+------------------------------------------+\n|          Jakarta Schools Analysis        |\n+------------------------------------------+\n|                |                         |\n| Control Panel  |    Spatial              |\n| • Analysis     |    Visualization        |\n| • Metrics      |    Window               |\n| • Parameters   |                         |\n|                |                         |\n| Analysis       |                         |\n| Summary        |                         |\n| • Statistics   |                         |\n| • Results      |                         |\n|                |                         |\n|                |                         |\n+----------------+-------------------------+\n```\n\n![](Mockup_1_LayoutArchitecture.PNG)\n\n#### Component Relationships\n\nThe spatial organization of the interface establishes clear relationships between analytical elements through a hierarchical structure that guides users through the analysis process:\n\n1.  The Control Panel serves as the primary input interface, containing essential analysis parameters, metric selection options, and statistical controls that directly influence the spatial analysis visualization.\n\n2.  The Analysis Window occupies the majority of the interface space, providing a comprehensive view of district-level spatial patterns and clustering results through color-coded visualizations and interactive elements.\n\n3.  The Statistical Summary Panel provides contextual information and detailed metrics that support the interpretation of spatial patterns observed in the analysis window, offering both global and district-specific statistical measures.\n\n### Control Panel Organization\n\nThe control panel implements a hierarchical organization that reflects the logical progression of spatial analysis.\n\n``` plaintext\n+-----------------------------------+\n|        Analysis Selection         |\n|  Primary Method Choice            |\n+-----------------------------------+\n|        Metric Selection           |\n|  Analysis Variable Choice         |\n+-----------------------------------+\n|      Significance Control         |\n|  Statistical Parameter Tuning     |\n+-----------------------------------+\n|      Analysis Summary             |           \n|                                   |\n+-----------------------------------+\n```\n\n![](Mockup_1_Control_Panel.PNG){width=\"286\"}\n\n### Visualization Organization\n\nThe central visualization component consists of a single interactive map display that renders spatial analysis results for Jakarta's districts\n\n![](Mockup_1_Visualization.PNG)\n\n## Layout Architecture - Mock up 2\n\n### Design Evolution Rationale\n\nThe second mockup iteration proposes a significant shift in how spatial analyses are presented, moving from a toggle-based single view to a simultaneous dual-view layout. This design decision is driven by several key insights:\n\n1.  **Comparative Analysis Enhancement**\n    -   Displaying LISA and Hot-Spot analyses side by side enables immediate visual comparison\n    -   Reduces cognitive load by eliminating the need to mentally retain patterns while switching between views\n    -   Facilitates deeper understanding of how different spatial statistics complement each other\n2.  **Workflow Efficiency**\n    -   Eliminates the friction of switching between analysis types\n    -   Enables real-time parameter adjustments with immediate visual feedback across both methods\n    -   Streamlines the decision-making process by providing comprehensive spatial information at a glance\n\n### Proposed Layout Structure\n\n```         \n+------------------------------------------+\n|          Jakarta Schools Analysis        |\n+------------------------------------------+\n|          |              |                |\n| Control  |    LISA      |   Hot-Spot     |\n| Panel    |    Analysis  |   Analysis     |\n| (20%)    |    (40%)     |   (40%)        |\n|          |              |                |\n|          |              |                |\n+----------+              |                |\n| Summary  |              |                |\n+------------------------------------------+\n```\n\n### ![](Mockup_2_diagram.PNG)\n\n### Design Limitations and Future Considerations\n\nWhile the side-by-side visualization approach offers valuable comparative insights, several significant limitations have emerged during testing:\n\n1.  **Map Size Constraints**\n    -   Smaller map sizes make it difficult to discern fine details in Jakarta's complex district structure\n    -   Reduced visualization area impacts the overall user experience when analyzing spatial patterns\n\nBased on these findings, we will be returning to the single-map toggle design for the Jakarta schools analysis dashboard. However, the dual-view concept could be retained for future applications where rapid comparative analysis takes precedence over detailed spatial examination.\n\n## Layout Architecture - Mock up 3\n\n### Design Evolution Rationale\n\nAfter evaluating the limitations of Mock-up 2's side-by-side approach, Mock-up 3 returns to the successful single-map toggle design from Mock-up 1, while introducing a key structural improvement to enhance data comprehension and workflow efficiency.\n\n### Key Innovation: Repositioned Summary Panel\n\nThe primary modification in Mock-up 3 is the relocation of the statistical summary from within the control panel to a dedicated horizontal panel at the bottom of the interface. This design decision is driven by several important considerations:\n\n1.  **Enhanced Control Panel Focus**\n    -   Provides room for potential additional control options\n    -   Improves overall readability of control parameters\n2.  **Improved Data Context**\n    -   Creates a natural \"analysis flow\" from top to bottom\n    -   Summary statistics become a conclusion rather than a sidebar\n    -   Facilitates easier comparison of statistics across different analysis states\n    -   Provides more horizontal space for detailed statistical presentations\n\n### Proposed Layout Structure\n\n```         \n+------------------------------------------+\n|       Jakarta Schools Analysis           |\n+------------------------------------------+\n|            |                             |\n| Analysis   |     Spatial Analysis        |\n| Controls   |     Visualization           |\n|            |     Window                  |\n|            |                             |\n|            |                             |\n+------------+-----------------------------+\n|           Statistical Summary            |\n|                                          |\n+------------------------------------------+\n```\n\n![](mockup_3_diagram.PNG)\n\n### Component Modifications\n\n1.  **Control Panel Refinements**\n    -   More vertical space for interactive elements\n    -   Improved spacing between controls\n    -   Room for explanatory text or tooltips\n    -   Potential for additional analysis parameters\n2.  **Summary Panel Design**\n    -   Horizontal layout maximizes readable width for statistical data\n    -   Organized in clear sections for different types of statistics\n    -   Option for tabbed or segmented display of different statistical views\n    -   Space for data visualizations like small charts or graphs\n3.  **Visual Hierarchy**\n    -   Clear progression from input (controls) to output (map) to results (summary)\n    -   Maintains strong relationship between controls and visualization\n    -   Creates natural \"story\" flow for data analysis process\n\nThis revised layout maintains the successful elements of Mock-up 1 while improving the organization and presentation of statistical information. The horizontal summary panel provides a natural conclusion to the analysis workflow, enhancing both the user experience and the analytical process.\n\n# References\n\n-   Utilized Claude AI to clarify code concepts and refining responses.\n\n-   Seniors' learning from <https://giniceseah.netlify.app/posts/2021-07-31-storyboard/> and <https://is415-gaa-project-group3.netlify.app/>\n",
    "supporting": [
      "Takehome_Ex3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}